tpm2-software/tpm2-tss

- INSTALL
This is where we document the build and install instructions. Currently
the TPM2.0-tss isn't installable so it's just build instructions for
now.
This resolves #8
> Add INSTALL file.

- test/tpmclient/Makefile.in
This gets rid of an error message output to the console and broken
dependency.
> Fix bad path to resourcemgr directory.

- Makefile.am
This abstraction leaked on account of having to specify SAPI_CLIENT at
compile time for the tpmclient. By removing libcommon.a and specifying
the source files directly through the *_SOURCES variables we compile
individual source files in the common directory with the different
C(XX)?FLAGS for both the resourcemgr and the tpmclient.
Also worth noting is that the headers for libtpm are no longer included
in the *_SOURCES variables for resourcemgr and tpmclient. This dependency
is automagically accounted for by automake.
This resolves #32
Signed-off-by: Philip Tricca <flihp@twobit.us>
> build: Remove libcommon.a, reference common source directly.

- resourcemgr/resourcemgr.c
- sysapi/include/tss2_tcti.h
- sysapi/include/tss2_tcti_util.h
Closes #31 
on cygwin gcc macros can be listed with:
```
~/Documents/TPM/TPM2.0-TSS/sysapi
$ gcc   -dM -E -x c /dev/null |egrep -i "cygwin|unix|win|linux"
#define __WINT_MAX__ 4294967295U
#define __unix__ 1
#define __unix 1
#define __WINT_MIN__ 0U
#define __SIZEOF_WINT_T__ 4
#define unix 1
#define __CYGWIN__ 1
#define __WINT_TYPE__ unsigned int
~/Documents/TPM/TPM2.0-TSS/sysapi
$ g++   -dM -E -x c++ /dev/null |egrep -i "cygwin|unix|win|linux"
#define __WINT_MAX__ 4294967295U
#define __unix__ 1
#define __unix 1
#define __WINT_MIN__ 0U
#define __SIZEOF_WINT_T__ 4
#define unix 1
#define __CYGWIN__ 1
#define __WINT_TYPE__ unsigned int
~/Documents/TPM/TPM2.0-TSS/sysapi
$
```
> cygwin build issue

- bootstrap
Fix spacing in shebang.
Bourne shell 'echo' doesn't understand -e, replace with printf.
Function definition with 'function' is bash specific.
Capture all output to src_vars.mk in a single redirect.
Print output for autotools utilities and set -e to halt on errors.
Resolves #45 
> bootstrap: Fixup bourne shell compatibility & cleanup.

- .gitignore
- INSTALL
- Makefile.am
- bootstrap
- configure.ac
This PR effectively uses libtool to build the sapi as a shared object / library. Additionally we now link the resourcemgr and test programs against this library (static or dynamic depends on options passed to configure). Finally we can now run 'make install' to install sapi headers, library and the resourcemgr. The test programs are not installed.
> build SAPI as a library, use it in bins & install stuf

- .gitignore
- INSTALL
- Makefile.am
- bootstrap
- configure.ac
This PR builds on #60 
It separates the local TPM TCTI into it's own library.
Additionally the resourcemgr now links against this library instead of including the sources directly.
> build local tpm TCTI as library

- Makefile.am
Link test programs to it. Install it along with the right header.
The resourcemgr requires different macros defined at compile time
so we just build this TCTI into the resourcemgr binary directly.
Resolves #59
> build: Build the socket TCTI as a library.

- LICENSE
This file includes the full text of the 2-clause BSD license used
by Intel, as well as the TCG license. Any future changes to the
licenses in play will be reflected in this file as well as the
relevant source files.
This resolves #67
> Add LICENSE file identifying the two licenses in play.

- resourcemgr/resourcemgr.c
Added codes for flushing loaded handles before the resource manager is started.
tboot 1.8.3(TPM 2.0) create an object handle during boot process.
However, the resource manager of TSS seems to presume this handle as abnormal object and returns an error code to client.
To solve this problems, the resource manager is changed to flush all loaded handles before the resource manager is started.
This commit solved issue #83
> Added codes for flushing loaded handles before the resource manager is started.

- resourcemgr/resourcemgr.c
Execute tpmtest with resourcemgr connected to simulator, then follow the hint to run all tests in 2 - STARTUP TESTS, then run all tests in 10 - START_AUTH_SESSION TESTS, will get failure code 0xCF802(TSS2_RESMGR_FIND_FAILED).
The root cause is that the in memory context will be flushed after running savecontext for a session, so the original code try to prevent resourcemgr automatically evicting the context again via setting foundEntryPtr->status.loaded = 0. But this will cause the final call to EvictEntities failed.
The solution is to avoid calling into EvictEntities for Tss2_Sys_ContextSave(session) case while adding more if conditions.
> [resourcemgr]fix for Tss2_Sys_ContextSave(session)

- sysapi/include/tss2_sys_api_marshalUnmarshal.h
- sysapi/include/tss2_tpm2_types.h
- sysapi/sysapi_util/Marshal_TPMS_NV_PIN_COUNTER_PARAMETERS.c
- sysapi/sysapi_util/Unmarshal_TPMS_NV_PIN_COUNTER_PARAMETERS.c
I forgot to accept all revisions.  This resulted in a few weird values
even though everything would still build.
> When previously autogenerating code from 1.26 version of TPM 2.0 spec,

- Makefile.am
- include/tpm2sapi/tss2_sysapi_util.h
- include/tpm2tcti/localtpm.h
- include/tpm2tcti/magic.h
- include/tpm2tcti/tpmsockets.h
- resourcemgr/resourceMgr.vcxproj
- tcti/commonTcti/commonchecks.c
These two values must be specified by clients consuming our TCTI
interface. Currently they reside in the tss2_sapi_util.h file that we
include in the tpm2sapi headers. This is a non-standard file that will
be removed soon and so this value must be moved to keep from breaking
client code. Since these two values are used by both the dev and socket
TCTIs I've put them into a common 'magic.h' file.
This resolves #109
Signed-off-by: Philip Tricca <flihp@twobit.us>
> Move TCTI_MAGIC and TCTI_VERSION values to a common include.

- test/tpmtest/tpmtest.cpp
tpmtest was broken by latest updated TPM2B type size check logic in sapi lib. Fix it.
> fix tpmtest to met updated check in SAPI

- test/tpmtest/tpmtest.cpp
This might cause random failures.
> tpmtest: add a missed size initialization

- include/tcti/tcti_device.h
- include/tcti/tcti_socket.h
- resourcemgr/resourcemgr.c
- resourcemgr/resourcemgr.h
- sysapi/include/tcti_util.h
- tcti/tcti_device.c
- tcti/tcti_socket.cpp
- test/tpmclient/tpmclient.cpp
- test/tpmtest/tpmtest.cpp
In this PR:
Remove the TSS2_TCTI_DRIVER_INFO struct.
Trim unnecessary stuff from Init and Teardown functions.
Replace configuration string and parsing logic with simple structure for both TCTIs.
> Tcti init cfg

- resourcemgr/resourcemgr.h
> resourcemgr: Remove unused rmPrintf.

- include/tcti/tcti_socket.h
- resourcemgr/resourcemgr.c
- tcti/platformcommand.c
The resourcemgr is a better place to filter PlatformCommands. The TCTI
shouldn't care whether or not the resourcemgr is talking to the
simulator or not. We effectively move the check up a level in the call
scope to the resource manager. The check now happens before the resource
manager calls PlatformCommand.
Consuming applications will no longer be required to define this
variable. The socket TCTI will always send platform commands when the
command socket is connected.
This resolves #131
> tcti_socket: Remove simulator flag.

- common/debug.c
- common/debug.h
- common/sockets.cpp
- include/tcti/tcti_socket.h
We also remove the extern declaration of the same function pointer in the
debug header since it's not defined in the debug implementation. This
requires that we move the declaration to the socket TCTI header. This is
a bit ugly as it exposes this global data to clients but at least it's
not misleading. The enumeration we use as the second parameter to this
function must be moved to the socket TCTI header as well.
> debug: Stop using global printfFunction pointer in debug functions.

- include/tcti/tcti_device.h
- include/tcti/tcti_socket.h
Both of these headers reference types from the TSS2 spec. The argument
could be made that programs including a TCTI should include the TSS2
headers first but I've gone for the simple approach.
> headers: Add tpm20.h include to both TCTI headers.

- Makefile.am
This will cause an error if the library has any unresolved symbols.
> tcti_device: Pass -no-undefined flag to linker.

- common/debug.c
- common/debug.h
- common/sockets.cpp
- resourcemgr/resourcemgr.c
- tcti/platformcommand.c
- tcti/tcti_device.c
- tcti/tcti_socket.cpp
- test/tpmclient/tpmclient.cpp
- test/tpmtest/tpmtest.cpp
This global variable seemed to act like an escape hatch overriding the
flag passed to the debug function. As someone coming along and trying to
pick up this code I found it confusing when debug function refused to
print a prefix even though I had asked it to. Not hard to figure out but
global flags like this have the potential to cause unexpected behavior.
IMHO it's better to simplify the code and remove this.
To compensate for the loss of the rmDebugPrefix flag in the
DebugPrintBuffer function I've added another parameter for callers to pass
a printf_type flag to obtain the same behavior as when the rmDebugPrefix
flag was set.
> debug: Remove global variable rmDebugPrefix.

- resourcemgr/resourcemgr.c
This regression brought to you by
6feb976cc62bab3a3ec4687bcf308c4e703f27ce.
> resourcemgr: Default to simulator port when connecting to the simulator.

- common/sockets.cpp
- tcti/platformcommand.c
These slipped through as they're only enabled when DEBUG_SOCKETS is
defined.
> debug: Missed converting a few calls to DebugPrintBuffer.

- Makefile.am
- common/tcti_device_util.c
- common/tcti_device_util.h
- include/tcti/tcti_device.h
- resourcemgr/resourcemgr.c
- tcti/tcti_device.c
- test/tpmclient/tpmclient.cpp
Both the InitDeviceTctiContext and TeardownDeviceTcti functions are not
part of the SAPI/TCTI spec. This commit moves them from the exposed
interface for the device TCTI to common/tcti_device_util.[ch]. AFAIK
these functions were created for convenience in the resourcemgr and test
applications.
This also includes a change to the signatures of these functions adding the name string that's passed into the InitDeviceTcti as a parameter to break coupling with another bit of global data.
> tcti_device: Move convenience functions to common directory.

- Makefile.am
- common/debug.c
- common/debug.h
- include/tcti/common.h
- include/tcti/magic.h
- include/tcti/tcti_socket.h
- resourcemgr/resourcemgr.c
- sysapi/include/tcti_util.h
- tcti/commonchecks.c
- tcti/logging.h
- tcti/tcti_device.c
- test/tcti_device.c
- test/tcti_device_test.c
- test/tcti_device_test.h
This is a significant departure from the way we currently handle the debugging functions in the TCTIs. The way we've done this up till now was to have a global function pointer set at compile time. This was typically controlled by a pre-processor macro. The global data this approach causes a litany of problems.
The refactoring I've been doing has all been leading up to decoupling the TCTIs from the application code (removing this shared global data) while preserving the current debug messages. This PR is an experiment in allowing the application consuming the TCTI to provide a callback function and some data that the TCTI will invoke in place of the global debug function pointer. This PR only addresses the issue in the device TCTI since it's a more simple case. The socket TCTI comes next. …
> Tcti device printf

- common/tcti_device_util.c
- include/tcti/common.h
- include/tcti/tcti_device.h
- include/tcti/tcti_socket.h
- resourcemgr/resourcemgr.c
- sysapi/include/tcti_util.h
- tcti/tcti_device.c
- tcti/tcti_socket.cpp
- test/tpmclient/tpmclient.cpp
- test/tpmtest/tpmtest.cpp
Allowing users to pass these values causes a situation where an unusable
TCTI context is created. There's no real reason to expose this data to
consumers of this library. This internal data has also been moved from the
installed common include file to the private sysapi/include/tcti_util.h.
> tcti: Remove magic & version parameters from the Init functions.

- common/tcti_device_util.c
- include/tcti/tcti_device.h
- include/tcti/tcti_socket.h
- resourcemgr/resourcemgr.c
- tcti/tcti_device.c
- tcti/tcti_socket.cpp
- test/tcti_device_test.c
- test/tpmclient/tpmclient.cpp
- test/tpmtest/tpmtest.cpp
Both the device and socket TCTI init functions take as a final parameter
a string. AFAIK these strings are only used in a debug print function as
a way to track which TCTI is being initialized and when. This is useful
to client code but not something that should be reflected in the API
that we expose.
This patch removes this parameter and the corresponding debug printf
call from both TCTI init functions. An identical debug printf is added
to each client (resourcemgr, tpmclient, tpmtest) to keep the output
consistent. Unit tests are updated as well.
> Remove debug data from TCTI function signature.

- Makefile.am
- tcti/tcti_device.map
- tcti/tcti_socket.map
This codifies the fix for #105 and is a mechanism for keeping it from happening again. We need to do the same for libtss2.so but that's still a ways off.
> Clean up library flags & add export maps for TCTIs.

- Makefile.am
Now that the command code to string conversion mechanism is a function
in the debug code we can build all libraries with the --no-undefined
flag.
> build: Build all libraries with -Wl,--no-undefined.

- include/tss2/tss2_tcti.h
- tcti/tcti_device.c
- tcti/tcti_socket.cpp
Add macros to ease access to fields in the TSS2_TCTI_COMMON_CONTEXT_V1 structure.
Add macros to simplify the invocation of function pointers in from the same context structure.
If we think this is "the right thing to do" I'll take a pass over the repo putting them into use.
> Tcti helper macros

- test/common/sample/DecryptEncrypt.c
- test/common/sample/SessionHmac.c
- test/tpmclient/tpmclient.cpp
- test/tpmtest/tpmtest.cpp
fixed one more bug, and updated to use INIT_SIMPLE_TPM2B_SIZE for the initialization.
> tpmtest: fix simple TPM2B initialization issues

- resourcemgr/resourcemgr.c
First, set persistent flag in evicted entry to make the persistent flag
functioning as designed.
Then in tpm2_Load case, allow using persistent parent created by other
connection.
> RM: allow Load to use persistent parent created by other connection

- test/tcti_device_test.c
This is required to bulid with -Wall -Werror.
> test: Remove unused state variable.

- test/tpmclient/tpmclient.cpp
When compiling with -Wall -Werror these variables cause problems since
they're initialized conditionally and so they may not be set by the time
they're used (-Werror=maybe-uninitialized).
> tpmclient: Initialize a few variables explicitly.

- include/tss2/tss2_tcti.h
The receive, finalize, cancel, getPollHandles and setLocality macros all
had cut / paste errors.
> tcti: Get parameters to TCTI function macros right.

- resourcemgr/resourcemgr.c
- sysapi/include/tcti_util.h
- tcti/tcti_device.c
- tcti/tcti_socket.cpp
- test/tpmclient/tpmclient.cpp
- test/tpmtest/tpmtest.cpp
Added command line control of debug messages in RM
Cleaned up uses of RM prefix.  This prefix is ONLY to be used for
TPM commands/responses generated by the RM itself.
Added debug level for commands sent from application.
Enabled debug level control over TPM commands issued during RM initialization.
Added RM prefix to debug messages for TPM commands issued during RM initialization.
Added control over RM prefix to both local and socket TCTI layers.
> Got debug messages working in RM.

- lib/tcti_device.pc.in
- lib/tcti_socket.pc.in
- lib/tss2.pc.in
I've tested this using the tpm2.0-tools as a use case. I've got patches
ready to go for the tpm2.0-tools build use use these in place of the
AC_CHECK_HEADER macros.
> pkgconfig: Fix bad flags.

- .gitignore
- ChangeLog
- Makefile.am
- common/getcommands.c
- resourcemgr/getcommands.c
- test/getcommands-malloc-mock_unit.c
This patch set removes the last remnants of the SAPI_CLIENT macro.
> No sapi client

- common/sockets.cpp
- resourcemgr/resourcemgr.c
- tcti/platformcommand.c
Fix #288.
Check the exit code after resourcemgr exit, we can see 141, which means SIGPIPE was received. This was caused by send() without MSG_NOSIGNAL flag.
Add MSG_NOSIGNAL flag to avoid this unexpected behavior.
> Fix resourcemgr shutdown caused by client disconnection

- resourcemgr/resourcemgr.c
This is a re-packaging of the commits from PR #296. Specifically I've broken the patch up into two, one that fixes the race condition on the cmdBuffer, and a second that fixes the race on the downstream TCTI context. I've also added descriptive commit messages for each.
See #295 for description of the original issue.
@medition: since these are a re-write of your original patch can you please review this to be sure that you agree with my changes? I'll hold off pushing till you review.
> Resourcemgr races

- CHANGELOG.md
- tcti/tcti_device.c
- test/tcti-device_unit.c
This resolves #297 and adds a unit test for the conditions that trigger the bug.
> Tcti device null deref

- include/sapi/tss2_tpm2_types.h
See part 2 of the spec, table 30. In its previous form any use of the
PCR_LAST macro produced an error since IMPLEMENTATION_PCR1 was
undefined. Should have been IMPLEMENTATION_PCR - 1.
> tss2_tpm2_types: Fix definition of PCR_LAST.

- Makefile.am
- include/sapi/marshal.h
- lib/libmarshal.map
- marshal/base-types.c
- sysapi/include/sys_api_marshalUnmarshal.h
- sysapi/sysapi_util/CommandUtil.c
- test/unit/CopyCommandHeader.c
This commit adds the marshalling functions as well as replaces some
convoluted access to said types in the CommandUtil module.
Use of these functions shows that having the Marshal function take a
reference to the type being marshalled makes using constants awkward. It
requires that the constant be assigned to a variable first which isn't
ideal or necessary. Probably worth fixing the API early if this turns
out to be a good change.
> libmarshal: Add functions to (un)?marshal TPM_ST and use them.

- .gitignore
- configure.ac
- m4/flags.m4
- marshal/base-types.c
- marshal/base-types.h
- resourcemgr/resourcemgr.c
- test/tpmclient/tpmclient.c
- test/unit/UINT32-marshal.c
- test/unit/UINT64-marshal.c
This also includes a fix for a type-punning issue. The CAST_TO_* macros were a convenient way to convert from a primitive type to a byte array. But as we're dialing up the hardening of the compiler / preprocessor / linker flags GCC gets increasingly strict about things like aliasing. Using `memcpy` is the right way to do this regardless.
Note to future self: enable these flags before you write a single line of code.
> More flags fixes

- include/sapi/marshal.h
- marshal/base-types.c
- sysapi/include/sys_api_marshalUnmarshal.h
- sysapi/sysapi_util/CommandUtil.c
- test/unit/UINT16-marshal.c
- test/unit/UINT32-marshal.c
- test/unit/UINT64-marshal.c
- test/unit/UINT8-marshal.c
Passing these by reference made no sense and made using the functions
awkward (couldn't marshal constants).
> libmarshal: Pass source parameter by value for *_Marshal functions.

- include/sapi/marshal.h
- lib/libmarshal.map
- marshal/base-types.c
- tcti/tcti_socket.c
Add functions to marshal / unmarshal TPM_CC types, use them (and clean out CHANGE_ENDIAN_*) from $(srcdir)/tct/tcti_socket.c.
> TPM_CC (Unm|M)arshal

- Makefile.am
- test/unit/tcti-device.c
This required building the device tcti source directly into the unit
test. Linking against libtcti-device borked up the linker wrap magic.
> unit: Add tests for successful calls to device TCTI receive / transmit.

- .gitignore
- Makefile.am
- configure.ac
- test/integration/start-auth-session.c
- test/unit/tcti-device.c
Currently this is a simple test that should execute successfully. Would
be good to get more including failure conditions.
> test: Add integration test for Tss2_Sys_StartAuthSession.

- Makefile.am
- sysapi/include/sysapi_util.h
- sysapi/sysapi/authorizations.c
- sysapi/sysapi/execute.c
- sysapi/sysapi_util/CommandUtil.c
- test/tpmclient/tpmclient.c
First steps toward simplifying the response processing path. These commits add a response header structure to the context to persist the unmarshalled response header. This keeps later code processing the response from having to do a bunch of redundant casting / unmarshalling.
> Rsp header save

- Makefile.am
Without this fix, when cross-compiling for ARMv7, ld complains
`warning: libmarshal.so.0, needed by sysapi/.libs/libsapi.so, not found (try using -rpath or -rpath-link)`
and subsequently fails to build because of undefined references to the marshal functions.
> Makefile.am: Add missing dependency to libmarshal

- common/sockets.c
When send/recv indicate an error (i.e., return -1) because the call was
interrupted, we should not use the return value to adjust the loop
variables representing the bytes send/received and the remaining bytes
to send/receive.
This change moves the modification of the loop variables from the loop
header into the body where they are skipped in case the send/recv calls
were interrupted (that is, they returned an error and errno is set to
EINTR).
> do not adjust loop variables in case of send/recv being interrupted

- tcti/tcti_socket.c
While build using toolchain lib musl the following error exists:
| ../TPM2.0-TSS/tcti/tcti_socket.c: In function 'SocketReceiveTpmResponse':
| ../TPM2.0-TSS/tcti/tcti_socket.c:286:5: error: unknown type name 'fd_set'
|      fd_set readFds;
|      ^~~~~~
| ../TPM2.0-TSS/tcti/tcti_socket.c:287:20: error: storage size of 'tv' isn't known
|      struct timeval tv, *tvPtr;
|                     ^~
this corrects this error.
Signed-off-by: Armin Kuster <akuster@mvista.com>
> tcti_socket: fix musl build issue do to missing header

- bootstrap
The bootstrap script hard-codes the name of the autoreconf binary. This
hard-coding makes it unfeasible to run in a sandboxed environment where
those binaries are located at non-standard paths. Typically in
makefiles, binaries can be overwritten through environment variables.
This change adjusts the bootstrap script to honor the AUTORECONF
variable if present in the environment but is able to fall back to the
previous values if such variables are not present.
> make bootstrap binaries configurable via environment

- include/sapi/sys_api_part3.h
It should be <sapi/tpm20.h> not tcti/tpm20.h
> fix misleading #error comments

- lib/sapi.pc.in
> sapi.pc: Add libmarshal as a library required to build against libsapi.

- .travis.yml
- sysapi/sysapi_util/CommandUtil.c
- test/tpmclient/tpmclient.c
Some people prefer using clang to compile their code.
Some minor modifications are needed to make the code pass the compilers stricter settings.
Once it builds we can also add this new configuration to travis.
> Make TPM2.0-TSS compilable with clang and add clang to travis

- INSTALL
- configure.ac
The resourcemgr was using pthreads but it was removed. No need for this
library any longer.
> configure; Remove dependency / check for pthreads.

- sysapi/sysapi_util/CopySessionData.c
We don't have to check the rspAuthsArray twice
> Remove redundant always-true if check

- test/tpmclient/tpmclient.c
remove command line options that won't be useful when integrated into the test harness
> Tpmclient option cleanup rewrite

- bootstrap
SYSAPI_H is referenced in Makefile, but it is not generated
correctly.
This is a cherry-pick from master
> Generate correct SYSAPI_H list

- Makefile.am
Not sure why but 'distcheck' doesn't run the tests though.
> build: Fixup 'dist' target.

- Dockerfile
Got rid of how the Dockerfile cloned a new repo to build. Now it
builds from the already checked out one on the users machine.
> Dockerfile: Builds from checked out repo

- test/tpmclient/tpmclient.int.cpp
- test/tpmclient/tpmclient_wo_rm.h
The hmac tests only requrie the primary key referenced via the global
'handle2048rsa' handle variable. The hmac tests are run after the
TestCreate function (which loads this required key and one more) but
having this additional key loaded cause the hmac tests to fail with the
RC 0x902 aka 'TPM_RC_OBJECT_MEMORY'. Unloading this additional key manuall
allows the hmac tests to run successfully.
After the hmac tests run we flush the TPM and then re-run the TestCreate
function. This ensures that the keys referenced by the global handle2048rsa
and loadedSha1KeyHandle variables are loaded.
> tpmclient: Fix and enable the hmac tests.

- .travis.yml
Since we do a manual VPATH build the build will already be configured
here.
> travis.yml: remove configure step from coverity config

- Makefile.am
For whatever reason tpmclient when built by clang with FORTIFY_SOURCE
from configure.ac (=2) fails to execute successfully. This has no effect
on the libraries produced by the build.
> tpmclient: Undefine FORTIFY_SOURCE.

- include/sapi/implementation.h
Per the TCG Algorithm Registyry for TPM2.0, the header
implementation.h was missing the following algorithms:
* TPM_ALG_SHA3_256 - 0x27
* TPM_ALG_SHA3_384 - 0x28
* TPM_ALG_SHA3_512 - 0x29
Also, the definition is in table 3 not table 2.
The specification can be found at:
https://trustedcomputinggroup.org/wp-content/uploads/TCG_Algorithm_Registry_Rev_1.24.pdf
Fixes: 476
> add missing algorithms

- man/InitDeviceTcti.3.in
- man/InitSocketTcti.3.in
The man page example implied that these functions connected using the
tabrmd but these are to bypass the tabrmd and go directly to the device
or the socket.
Signed-off-by: Doug Goldstein <cardoe@cardoe.com>
> man: update error message in man page example

- include/sapi/implementation.h
- include/sapi/tss2_tpm2_types.h
- sysapi/sysapi_util/GetDigestSize.c
- sysapi/sysapi_util/Marshal_TPMU_ASYM_SCHEME.c
- sysapi/sysapi_util/Marshal_TPMU_HA.c
- sysapi/sysapi_util/Marshal_TPMU_KDF_SCHEME.c
- sysapi/sysapi_util/Marshal_TPMU_PUBLIC_ID.c
- sysapi/sysapi_util/Marshal_TPMU_PUBLIC_PARMS.c
- sysapi/sysapi_util/Marshal_TPMU_SCHEME_KEYEDHASH.c
- sysapi/sysapi_util/Marshal_TPMU_SENSITIVE_COMPOSITE.c
- sysapi/sysapi_util/Marshal_TPMU_SIGNATURE.c
- sysapi/sysapi_util/Marshal_TPMU_SIG_SCHEME.c
- sysapi/sysapi_util/Marshal_TPMU_SYM_KEY_BITS.c
- sysapi/sysapi_util/Marshal_TPMU_SYM_MODE.c
- sysapi/sysapi_util/Unmarshal_TPMU_ASYM_SCHEME.c
- sysapi/sysapi_util/Unmarshal_TPMU_ATTEST.c
- sysapi/sysapi_util/Unmarshal_TPMU_CAPABILITIES.c
- sysapi/sysapi_util/Unmarshal_TPMU_HA.c
- sysapi/sysapi_util/Unmarshal_TPMU_KDF_SCHEME.c
- sysapi/sysapi_util/Unmarshal_TPMU_PUBLIC_ID.c
- sysapi/sysapi_util/Unmarshal_TPMU_PUBLIC_PARMS.c
- sysapi/sysapi_util/Unmarshal_TPMU_SCHEME_KEYEDHASH.c
- sysapi/sysapi_util/Unmarshal_TPMU_SENSITIVE_COMPOSITE.c
- sysapi/sysapi_util/Unmarshal_TPMU_SIGNATURE.c
- sysapi/sysapi_util/Unmarshal_TPMU_SIG_SCHEME.c
- sysapi/sysapi_util/Unmarshal_TPMU_SYM_KEY_BITS.c
- sysapi/sysapi_util/Unmarshal_TPMU_SYM_MODE.c
The selective enabling / disabling of these things makes little sense for the TSS. Removal greatly simplifies the code.
> Support all algs and commands

- README.md
The travis URL had to be updated as did the local links. Local links
were changed from URLs to relative file paths to make this a bit less
fragile.
> README.md: Update URLs to account for TPM2.0-TSS -> tpm2-tss rename.

- include/sapi/implementation.h
This fixes a bug caused by 01e1e12965d747f5d95760baf931850e69294334
which removed the macro defining TRUE and FALSE but didn't remove the
preceding undef. This causes these macros to be undefined by the TSS2
headers even though they may have been defined by some other header
(like glib in the case of the tabrmd).
> implementation.h: Remove undef of TRUE and FALSE macros.

- sysapi/sysapi/Tss2_Sys_LoadExternal.c
- test/tpmclient/tpmclient.int.c
Commit 60dcc re-places the old marshaling code with the newer
marshaling code. This commit, introduced a breakagae in
tpm2_loadexternal tool when a private key was not specified.
In the case of a NULL private key, the Tss2_Sys_LoadExternal
call should set the size field of the Private Key to 0.
Fixes: #496
> TSS2_Sys_LoadExternal: Fix marshaling error

- Makefile.am
- lib/sapi.pc.in
- lib/tcti-device.pc.in
- lib/tcti-socket.pc.in
fix auto-generated pkgconfig files to allow us to install libsapi.a into a customized directory, e.g. /opt/xxx
> fix auto-generated pkgconfig files for libsapi

- .travis.yml
This gets us a faster turn around time on each build:
https://docs.travis-ci.com/user/reference/overview/#Virtualization-environments
Additionally it allows developers to use a local travis coantainer to
build / test locally.
> build: Switch travis from virtual machine to containers.

- include/sapi/tss2_tpm2_types.h
- sysapi/include/sys_api_marshalUnmarshal.h
- sysapi/sysapi_util/Unmarshal_TPML_INTEL_PTT_PROPERTY.c
- sysapi/sysapi_util/Unmarshal_TPMU_CAPABILITIES.c
The documentation for this feature is now up on the wiki: https://github.com/01org/tpm2-tss/wiki/PTT-GetCapability
This PR includes code provided to us by another Intel team with fixups by myself (required to get it to compile) as well as an additional commit I've added to prevent the unmarshalling function from ignoring properties when multiple are requested.
> Ptt capabilities

- marshal/tpm2b-types.c
The logic in TPM2B_*_Unmashal should be that, when the dest in NULL
and offset is valid, the offset should be updated, and nothing should
be written to the buffer.
Currently the implementation dereferences the dest causing a segfault.
> marshal: Fix null pointer dereference int TPM2B

- .travis.yml
- Makefile.am
- configure.ac
There are a few small changes here but all are required to get proper
release tarballs made by dist / distcheck.
The project name in configure.ac needed to be updated to account for the
project name change from TPM2.0-TSS to tpm2-tss. Also the options passed
to the configure script need to be propagated to the distcheck target.
This is accomplished by setting the DISTCHECK_CONFIGURE_FLAGS when the
configure script generates the Makefile.
In Makefile.am we add all of the log files generated by the test harness
to CLEAN_FILES to ensure they don't end up in the distribution tarball.
We also add the integration test log compilation script to EXTRA_DIST to
ensure it makes it into the distribution. Finally we add the log.h file
to marshal_libmarshal_la_SOURCES as it won't make it into the …
> build: Fix 'dist' and 'distcheck' target.

- CHANGELOG.md
- test/tpmclient/tpmclient.int.c
The word "synchronous" (and variations of it) is lacking an 'h' in a
couple of places. Fix them up.
> fix spelling of "synchronous" in a couple of places

- lib/tcti-device.pc.in
- lib/tcti-socket.pc.in
The dependency on sapi came from the fact that the TCTIs used the type
marshalling functions and they were packaged in libsapi. They were not
standardized and we shouldn't have been exposing them to consumers
really but we did.
Now that this is fixed and we have libmarshal the TCTIs should depend on
it directly and remove the libsapi dependency.
> pkg-config: TCTI libraries depend on libmarshal, not libsapi.

- INSTALL.md
The INSTALL.md file has instructions on how to build tpm2-tss from source
in other distros, add also a note on the steps needed to do it in Fedora.
Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>
> INSTALL.md: Add note on how to build from source in Fedora

- lib/libmarshal.map
There are already too many places to get endian conversion functions
(compiler built-ins, endian.h etc).
> libmarshal.map: Don't expose endian conversion functions.

- configure.ac
- sysapi/include/sysapi_util.h
This reverts commit 82a2ff9cec3169d33e1ad4433b074d399002f1c0.
Packing the public structures causes an ABI mismatch
between consumers of TSS public structures.
Fixes: #531
> Revert "configure: use -fpack-struct instead of pragmas"

- .travis.yml
After travis_ci update, cmocka-1.0.1 build started failing.
Update cmocka to latest version (1.1.1) to fix this problem.
> travis: update cmocka version

- marshal/tpml-types.c
- marshal/tpms-types.c
- test/tpmclient/tpmclient.int.c
While (un)marshalling TPML types the count needs to be
verified before the table is read/written to.
> add check for count in TPML

- test/tpmclient/tpmclient.int.cpp
GCC 7 is much more picky about this stuff.
> tpmclient: Fix misleading indentation.

- marshal/tpmt-types.c
Mhen unmarshalling TPMT type with a TPMU member, in case the dest is null
the selector needs to be unmarshalled into a tmp object to properly
calculate and update the offset.
> marshal: Unmarshal selector to properly calculate offset

- .travis.yml
- m4/flags.m4
Fixing the clang build is necessary to support the tabrmd 1.x branch. These are just infrastructure / build fixups to keep clang happy. b0ec72f should be picked into master as well.
> 1.x travis clang

- test/tpmclient/tpmclient.int.c
Remove double assignment of parameters of rsaDetail.keyBits value in TestCreate()
> Remove double assignment of parameters 

- sysapi/include/tcti_util.h
- sysapi/sysapi/ContextManagement.c
- tcti/commonchecks.c
- tcti/tcti_device.c
- tcti/tcti_socket.c
Use predefined TCTI_CONTEXT_INTEL to access TCTI context fileds.
This makes it the code more readable.
> tcti: use predefined TCTI_CONTEXT_INTEL

- sysapi/include/sysapi_util.h
- sysapi/sysapi/GetCommandCode.c
- sysapi/sysapi_util/CommandUtil.c
- test/tpmclient/SessionHmac.c
- test/tpmclient/TpmCalcPHash.c
The spec says: [1] "This function gets the command code for the command.
The command code is returned as an array of bytes in big endian order.
This array can be used for calculating the cpHash for a command or rpHash
for a response."
The problem is that our current implementation desn't return the command
code in big endian order, although it keeps it in big endian.
What happens is it is swapped three times:
First time in CommonPreparePrologue() in CommandUtil.c, line139:
SYS_CONTEXT->commandCodeSwapped = HOST_TO_BE_32(commandCode);
Then second time in Tss2_Sys_GetCommandCode()
*(UINT32 *)*commandCode = BE_TO_HOST_32(SYS_CONTEXT->commandCodeSwapped);
And the third time in tpmclient (TpmCalcPHash.c) in TpmCalcPHash():
*(UINT32 *)hashInputPtr = BE_TO_HOST_32(*(UINT32 *)cmdCodePtr);
This …
> sysapi: fix Tss2_Sys_GetCommandCode

- test/tpmclient/tpmclient.int.c
The current CompareTPM2B only compares the first byte.
> tpmclient: fix CompareTPM2B

- CHANGELOG.md
This is in preparation for the next minor release from the 1.x branch. The changes are minimal basically adding support for a single command needed by the tools.
> CHANGELOG.md: Add data on changes since 1.2.0.

- test/unit/tcti-device.c
- test/unit/tcti-socket.c
This should / may resolve #603.
> test: Use built-in mock with cast functions instead of manual casting.

- include/sapi/implementation.h
The TPM_ALG_XXX defines cast the values as TPM_ALG_ID types.
There is really no need for this additional layer.
This cast, actually causes compilers to ignore the case when
things are oversized. For example, this code will cause no
overflow warning:
uint16_t x = (uint16_t)0x111111111111;
Where as this code will:
uint16_t x = 0x111111111111;
warning: large integer implicitly truncated to unsigned type [-Woverflow]
> implementation.h: drop the casts and parens on Algs

- configure.ac
This is to keep developers with an old version of cmocka from having to
deal with compile time errors when we can catch this at configure time.
> build: Check for cmocka version >= 1.0 @ configure time.

- sysapi/include/sysapi_util.h
- I'm not sure if anyone remembers what CMD_STAGE_1 was
so remove it.
- Apply ifdef C++ to functions only.
- Update header comment.
> sapi: cleanup sysapi_utils.h

- include/sapi/tpm20.h
- marshal/tpma-types.c
- sysapi/sysapi/authorizations.c
- test/integration/asymmetric-encrypt-decrypt.int.c
- test/integration/create-keyedhash-sha1-hmac.int.c
- test/integration/sapi-util.c
- test/tpmclient/DecryptEncrypt.c
- test/tpmclient/LoadExternalHMACKey.c
- test/tpmclient/tpmclient.int.c
- test/unit/TPMA-marshal.c
- test/unit/TPMS-marshal.c
Per spec this changes TPMAs to be used as flags with defines instead of bitfields throughout the project.
For the moment, applications can -DTPM_BITFIELD_LE to use the old behavior.
TODO: Once they are updated the bitfield structs need to be removed from the headers.
Note: This PR is actually just one patch. It is based off of #626
> tpm-types: Switch TPMAs from structs to defines

- sysapi/include/sysapi_util.h
remove double struct definition of TSS2_SYS_CONTEXT
> remove double struct definition of TSS2_SYS_CONTEXT

- test/integration/asymmetric-encrypt-decrypt.int.c
Add flag that was missed out on the change from structs to flags.
Thanks to Javier Martinez !
> Tests: Fixed mistake from TPMA-patch

- include/sapi/tss2_mu.h
- lib/libmarshal.map
- marshal/base-types.c
- marshal/tpms-types.c
Added marshaling and unmarshaling for TPM2_HANDLE,
TPMI_ALG_HASH, TPM2_SE, TPM2B_NONCE, TPMS_EMPTY, BYTE
> MU: Add missing marshaling functions

- include/sapi/tss2_tpm2_types.h
- marshal/tpmu-types.c
There is no need to add the fake members to TPMU. We can use the
first member of the union instead. That way we don't have to
polute the TPM types.
> marshal: remove the fake na member from TPMU types

- sysapi/include/sysapi_util.h
- sysapi/sysapi/EncryptParam.c
- sysapi/sysapi/GetRpBuffer.c
- sysapi/sysapi_util/CommandUtil.c
GetRpBuffer would return garbage if called before
complete. This patch fixes this.
Also eliminates the field rpBuffer from SYS_CONTEXT along
the way.
> sysapi: fix GetRpBuffer

- bootstrap
The `-n` flag is not supported by the `echo` built-in of some versions
of `sh`. Use the portable `printf` instead.
Signed-off-by: David R. Bild <david.bild@xaptum.com>
> bootstrap: use portable printf instead of echo

- sysapi/sysapi_util/CommandUtil.c
Remove double return in CommonComplete()
> sysapi: Remove double return

- Makefile.am
The LICENSE file that's present in the source code is not distributed in the
tarball generated by the make dist target. Including full license text makes
it easier for people to comply with the desired license terms.
Signed-off-by: Javier Martinez Canillas <javierm@redhat.com>
> Makefile.am: Add LICENSE in tarball generated by the make dist target

- Makefile.am
- configure.ac
IMHO, Make's output is just too cluttered... So I never see any warnings...
RFQ: Would other also like to add silent rules as proposed in this patch ?
P.S. `make V=1` still gives you the old output...
> [RFC] Make: Add silent rules

- marshal/tss2_endian.h
The stdint.h include was missing, and one of the methods referred to a
non-imported typedef.
Signed-off-by: David R. Bild <david.bild@xaptum.com>
> endian: fix manually-defined endian conversions

- include/sapi/tss2_tcti.h
- tcti/sockets.c
- tcti/sockets.h
- tcti/tcti.h
This patch series adds support for building on Mac OS X by cleaning up some imports and using the BSD method for blocking SIGPIPE.
Unit tests (`make check`) do not build because the OS X linker does not support the `--wrap` flag.  Some unit tests depend on symbol wrapping, and there is not an easy way to mimic this behavior on OS X. 
The primary goal of this change is to enable OS X users to experiment with TPM 2 via the TSS and simulator, not to enable development of the TSS itself on OS X. So the lack of unit test support should be acceptable.  Regardless, this patch series does increase portability, at least incrementally.
N.B. Building on OS X requires PRs #647 and #648 as well.
> Support building on OS X

- include/sapi/tss2_sys.h
- sysapi/include/sysapi_util.h
- sysapi/sysapi/GetCommandCode.c
- test/integration/system-api.int.c
- test/tpmclient/SessionHmac.c
- test/tpmclient/TpmCalcPHash.c
This patch updates the function signature to reflect the
latest specification version.
Further, it make the GetCommandCode function safe to use
with non-aligned arrays.
Also it fixes the tests to account for correct endianess.
> sysapi: Fixes about GetCommandCode

- sysapi/sysapi/Tss2_Sys_EvictControl.c
- sysapi/sysapi/Tss2_Sys_LoadExternal.c
- tcti/sockets.c
- tcti/tcti_socket.c
- test/tpmclient/SessionHmac.c
- test/tpmclient/TpmCalcPHash.c
- test/tpmclient/tpmclient.int.c
- test/unit/TPM2B-marshal.c
- test/unit/TPMA-marshal.c
- test/unit/TPML-marshal.c
- test/unit/TPMS-marshal.c
- test/unit/TPMT-marshal.c
- test/unit/TPMU-marshal.c
- test/unit/tcti-device.c
Fix warnings and errors from clang scan-build
Includes 1 actual error of use-after-free and a bunch of unused variables and return code warnings.
> Fix scan-build warnings

- Makefile.am
- configure.ac
- m4/ld-version-script.m4
Some linkers do not support the --version-script flag.  Only include
it if the linker supports it.
Signed-off-by: David R. Bild <david.bild@xaptum.com>
> build: detect ld version-script flag support

- Makefile.am
This seems to have just been an oversight.
> build: Add libmu as a dependency of libtcti-socket.

- test/tpmclient/syscontext.c
> Fix memory leaks on error conditions in InitSysContext & SockServer.

- .travis.yml
- README.md
**This had to come from in internal-to-origin branch inorder to have access to REPO_COVERALLS_TOKEN as encrypted variables are not available for external forked PRs according to: https://docs.travis-ci.com/user/encryption-keys/**
Enable coveralls, which provides:
1. archival of coverage stats.
2. failure thresholds if patches reduce coverage
by a certain amount.
3. public badging of current coverage.
In order to enable it, one must have the coveralls command
installed via pip as well as the COVERALLS_REPO_TOKEN set
as the repo's token encrypted via travis encrypt.
> coveralls: enable coverage stats

- .travis.yml
PRs from 3rd party repos don't have access to encrypted env
variables.
For example, see:
https://travis-ci.org/intel/tpm2-tss/jobs/315268038
> travis: ensure COVERALLS_REPO_TOKEN is set before uploading

- marshal/tpmt-types.c
Compilers that don't support GNU extensions complain about
missing initializer.
> marshal: fix compiler errors for non GNU compatible compilers

- include/sapi/sys_api_part3.h
- sysapi/sysapi/Tss2_Sys_IncrementalSelfTest.c
- sysapi/sysapi/Tss2_Sys_PolicyNvWritten.c
This PR sums up a few minor fixes:
- a missing `const` qualifier
- a misspelled function name
- missing function declarations in header
> SAPI: Minor fixes

- include/tcti/tcti_device.h
These fields have been unused since
43a0d76bf4e8f50b164a8be89102f1de03d46fa6.
> tcti: Remove unused log data from device TCTI config structure.

- include/sapi/tss2_tpm2_types.h
If define as an array with 0 members this causes pedantic C compilers to
complain of the invalid 0 sized array (disallowed by c99).
> Define TPMS_EMPTY structure to have a BYTE array with a single member.

- .travis.yml
- Makefile.am
- configure.ac
- include/sapi/tss2_tcti.h
- include/tcti/tcti_device.h
- include/tcti/tcti_socket.h
- tcti/tcti_device.c
- tcti/tcti_device.map
- tcti/tcti_socket.c
- tcti/tcti_socket.map
This resolves #690. Next step is to remove the old init functions but the test harnesses for the various projects need to be updated first. I've also got some example code in a topic branch for the tools: https://github.com/flihp/tpm2-tools/tree/tcti-init-v3 but for the time the old interface is still in use.
> common TCTI init

- doc/coding_standard_c.md
The TCG specs uses camelCase and Some_Other_Weird_Form heavily. To
maintain compatibility we must make exceptions for this stuff.
> doc: Document exceptions to function and variable naming convention.

- include/sapi/tss2_tcti.h
The TSS2_ prefix is how the TCG specs attempt prevent conflicts with symbols
/ macros from other libraries / headers. Since this macro is in a public
header it should have this prefix.
> tcti: Add 'TSS2_' prefix to TCTI_INFO_SYMBOL macro.

- log/log.h
Compiler macros are handy but only for people using compatible
compilers. This patch wraps our use of these compiler specific keywords
in an additional layer of macros. We detect the compiler type using a
compiler specific macro (only GCC compatible compilers currently) and
define COMPILER_ATTR accordingly.
When we add support for additional compilers we can add additional
tests.
> log: Wrap use of compiler specific attributes in a macro.

- Makefile.am
Bug reported here: https://github.com/intel/tpm2-tss/issues/700. Master
already has these changes.
> build: Add libsapi to LDADD for sapi_util unit tests.

- configure.ac
When using glibc < 2.19, the use of endian.h requires the
old macro _BSD_SOURCE instead of the new one _DEFAULT_SOURCE.
> build: Have supported glibc versions before 2.19.

- marshal/tpmu-types.c
I spent some time recently figuring out how the macros that generate the TPMU_* marshalling functions work. The existing comments around these macros were helpful, but still left a bunch of work to the reader. I'm hoping to save the next person who comes along a bit of time by filling in some of the less obvious details.
> Tpmu doc and format

- log/log.c
- test/unit/tcti-device.c
These are two minor fixes about a pointer cast mixup and an uninitialized string buffer.
> Test and Logging: Minor fixes

- configure.ac
V2:
- Change to define _POSIX_SOURCE instead of _GNU_SOURCE.
The macro HOST_NAME_MAX is defined when _POSIX_SOURCE is defined.
Otherwise, the following build failure may occur.
tcti/tcti_socket.c: In function 'Tss2_Tcti_Socket_Init':
tcti/tcti_socket.c:565:19: error: 'HOST_NAME_MAX' undeclared (first use
in this function)
char hostname[HOST_NAME_MAX + 1] = { 0 };
[This failure only happens in master branch]
Signed-off-by: Jia Zhang <zhang.jia@linux.alibaba.com>
> [V2] tcti-socket: Fix build failure due to undeclared HOST_NAME_MAX

- log/log.c
POSIX.1-2001 classified 'index' as LEGACY and POSIX.1-2008 removes it
completely. It was replaced by strchr and so using that instead is best.
> log: Replace use of 'index' with 'strchr'.

- INSTALL.md
- README.md
Update the INSTALL.md file to include a dependency on liburiparser-dev.
Update the README.md file to correctly point to the INSTALL.md file.
Signed-off-by: Kristen Carlson Accardi <kristen@linux.intel.com>
> update INSTALL and README

- README.md
The instructions for running tpmclient seem outdated. Update the
testing instructions to use make check instead.
Signed-off-by: Kristen Carlson Accardi <kristen@linux.intel.com>
> README: update documentation for testing

- README.md
> doc: Update link to travis-ci with new Github org name.

- include/sapi/tpm20.h
- include/sapi/tss2_mu.h
- include/sapi/tss2_sys.h
- include/tcti/common.h
- include/tcti/tcti_device.h
- include/tcti/tcti_socket.h
- tcti/platformcommand.c
- tcti/tcti.c
- tcti/tcti.h
- test/unit/TPM2B-marshal.c
- test/unit/TPMA-marshal.c
- test/unit/TPML-marshal.c
- test/unit/TPMS-marshal.c
- test/unit/TPMT-marshal.c
- test/unit/TPMU-marshal.c
Modify the source code to use #include "" so that the compiler
will look for the header locally prior to checking the system
include path.
Fixes: #687
Signed-off-by: Kristen Carlson Accardi <kristen@linux.intel.com>
> Include local headers

- README.md
This also updates the branch. It was 'master' for some reason. Should
have always been '1.x'.
> 1.x README.md: Update badge for org move intel -> tpm2-software.

- Makefile.am
- configure.ac
The crypto operations are lin libcrypto, not libssl.
> build: Link against libcrypt, not libssl.

- .appveyor.yml
Pretty straight forward. We need to start looking at Debug / Release builds too. Should just be a matter of adding an equivalent to our `--debug` option to the configure script.
> CI: Add 64bit build to AppVeyor yml.

- Makefile.am
This library uses libcrypto and if we build it when the integration
tests aren't enabled it creates a dependency on libcrypto when one
doesn't really exist.
> build: Build test library only when integration tests are enabled.

- .gitignore
- Makefile.am
- include/tcti/common.h
- include/tcti/tcti_device.h
- include/tcti/tcti_socket.h
- tcti/platformcommand.c
- tcti/sockets.c
- tcti/sockets.h
- tcti/tcti.c
- tcti/tcti.h
- tcti/tcti_device.c
- tcti/tcti_socket.c
- test/unit/tcti-socket.c
- test/unit/util.c
This is the "low hanging fruit" in the TCTI modules. Most of this is re-organizing some of the build bits. The rest implements a common write function shared between the device and socket TCTIs. This is easier than messing with the read path since it's not an async call. The build structure introduced here will make writing and testing the async read stuff easier though.
> TCTI refactor part 1

- Makefile.am
Before this patch we were shipping the man page after our build
transforms. This means running one of the clean targets will put the
source tree in a state where the build will fail since the source files
for the man page get 'cleaned'.
> build: Distribute the source for the InitSocketTcti man page.

- include/sapi/tss2_tcti.h
- tcti/tcti_device.c
This brings our implementation of the 'v1' TCTI context structure up to speed with the current spec. We also add some of the new convenience macros / types from the new draft spec. Next will be an update to the v2 structure in the current draft.
> Spec cleanup

- test/integration/esys-create-primary-hmac.int.c
- test/integration/main-esapi.c
Esapi has handling for TPM_RC_YIELDED included in their finish functions.
This patch adds functionality to the tests to return RC_YIELDED every second invocation of the TPM.
> Esapi testyielded

- configure.ac
- log/log.h
- marshal/tss2-mu.vcxproj
- sysapi/tss2-sapi.vcxproj
- test/tpmclient/tpmclient.int.c
The --with-loglevel configure switch was
not working. Renamed it and made it working
as --with-maxloglevel.
Also fixed an unused variable in tests for
maxloglevel==none.
> Logging: Fix --with-maxloglevel

- test/integration/main-esapi.c
Reverse logic in tcti_proxy_receive. Assign the response size outside of the
if block and reverse the if condition to copy if response buffer is not null.
> test: esapi: reverse logic in tcti_proxy_receive

- include/sapi/tss2_tcti.h
- tcti/tcti_device.c
- tcti/tcti_socket.c
This addresses feedback from TSS2 WG: The INFO structure should be
versioned just like we do the context structure. The two version
structures must be identical for both structures.
> tcti: Generalize version struct and add to INFO struct as first member.

- INSTALL.md
Clarify that uriparser and libgcrypt dependencies require libraries and
header files.
Fix typos in INSTALL.md such as missing blank lines and markup.
Fixes #810.
> INSTALL.md: add missing dependencies and fix formatting

- README.md
Add details about how to enable unit and integ tests separately.
This was requested in #784
> doc: update readme with tests enable info

- Makefile.am
- include/sapi/tss2_tcti.h
- include/sapi/tss2_tpm2_types.h
- include/tcti/tcti_device.h
- man/Tss2_Tcti_Device_Init.3.in
- man/man-postlude.troff
- tcti/tcti.c
- tcti/tcti.h
- tcti/tcti_device.c
- tcti/tcti_device.map
- tcti/tcti_socket.c
- test/integration/main-esapi.c
- test/integration/sys-initialize.int.c
Add the TCTI v2 stuff to the TCTI header, remove the deprecated init functions from the device TCTI and do a bit of cleanup.
> Tcti v2 and cleanup

- configure.ac
In this PR:
* Add license header to configure.ac
* Update URLs in AC_INIT to use new tpm2-software URLs
* Use `with_maxloglevel` variable in configure summary output, not `with_loglevel`
> configure.ac cleanup

- Makefile-test.am
- tcti/tcti.c
- tcti/tcti.h
- tcti/tcti_device.c
- tcti/tcti_socket.c
- test/integration/sys-initialize.int.c
- test/unit/tcti-device.c
- test/unit/tcti-socket.c
This should be the last round of cleanup commits to bring the TCTI stuff in-line with our coding standard & conventions. The second half of this PR starts meddling around with the internals of the TCTI context structure and the state machine that tracks the transmit / receive stuff.
> Tcti cleanup and state machine docs

- include/sapi/tss2_tpm2_types.h
Specification defines them as ranges:
TPM2_PT_PCR_RESERVED1 0x0000000B-0x00000010
TPM2_PT_PCR_RESERVED4 0x00000017-0x00000210
We need to define them as masks.
> sapi: fix definitions in reserved fields of TPM2_PT_PCR

- esapi/esapi/Esys_PolicyCommandCode.c
- esapi/esapi_util/esys_int.h
- include/esapi/tss2_esys.h
The session parameter of PolicyCommandCode was
falsely handled as command parameter instead of
an object handle. Thus it appeard at the wrong
place in the parameter list and also was of the
wrong type.
Fixed to work the same as all the other policy
commands.
> ESAPI: Fixed PolicyCommandCode

- doc/coding_standard_c.md
This adds a minor clarification to the whitespace section as well as additional requirements for the way we include headers.
> Coding standard include

- Makefile-test.am
- sysapi/sysapi/execute.c
- tcti/tcti.h
- tcti/tcti_socket.c
- test/integration/command-cancel.int.c
- test/unit/tcti-socket.c
TCTI receive sends a platform CANCEL_OFF command on every response
read, which isn't necessary. This changes it to only send CANCEL_OFF
if a CANCEL_ON command has been sent beforehand.
> tcti: don't send MS_SIM_CANCEL_OFF on every receive

- Makefile.am
- man/Tss2_Tcti_Socket_Init.3.in
- man/man-postlude.troff
This went stale a while ago when the old initialization function was
deprecated and the standard initialization function added.
> doc: Update manpage for socket TCTI initialization function.;

- tcti/tcti-mssim.c
- test/unit/tcti-mssim.c
When a `NULL` conf string is provided we're supposed to select a "sane"
default for the caller. Instead we're returning an error. This was
caused by a silly mistake made in checking the 'conf' parameter for
`NULL` in the wrong place.
This patch removes that check. We also add a TRACE level logging
statement to make future debugging a bit easier and a test case to
ensure a NULL conf string doesn't cause this regression again.
> libtcti-mssim: Fix regression in default conf string selection.

- src/tss2-esys/esys_context.c
Use calloc instead of malloc and memset. Libc calloc
will perform a malloc + memset under worse case scenarios.
Most OS specific routines, like mmap with map anonymous
will return 0 filled pages, and thus memset will not need
to be done.
> esys: use calloc instead of memset

- Makefile.am
- bootstrap
- include/tss2/tss2_common.h
- src/tss2-esys/esys_crypto.h
- src/tss2-mu/tpm2b-types.c
- src/tss2-sys/sysapi_util.h
- src/util/tpm2b.h
- test/tpmclient/CatSizedByteBuffer.c
- test/tpmclient/CopySizedBuffer.c
- test/tpmclient/tpmclient.h
This type isn't in the common header spec, or any TSS2 spec so it
definitely doesn't belong in any of the headers that get installed.
Since this is a type used by tss2-mu, sys and esys it now lives in
$(srcdir)/src/util/tpm2b.h.
To distribute this header in source tarballs via `make dist` it must be
added to the util library's SOURCE variable. To make this easier in the
future this commit adds code to the `bootstrap` script that populates
the UTIL_SRC variable with all source files under `$(srcdir)/src/util.`
> headers: Move TPM2B type from tss2_common.h to $(srcdir)/src/util.

- include/tss2/tss2_common.h
> tss2_common.h: Fix bad RC definition for TSS2_ESYS_RC_IO_ERROR.

- src/tss2-esys/esys_tcti_default.c
There are multiple problems with the error handling in
tpm2-tss/src/tss2-esys/esys_tcti_default.c get_tcti_default():
1. LOG_ERROR or LOG_WARNING should be used instead of fprintf().
2. Typo: s/Faled/Failed/
3. The rc value returned after calloc() fails is always TSS2_RC_SUCCESS
Fixes #885.
> tss2-esys: Fix Error Handling in get_tcti_default()

- src/tss2-tcti/tcti-device.c
- src/tss2-tcti/tcti-mssim.c
- src/tss2-tcti/tcti.c
- src/tss2-tcti/tcti.h
- test/unit/tcti-device.c
This commit resolves a bug in the device TCTI where the receive function
read the response header from the TPM but neglects to copy this to the
buffer provided by the caller. The unit tests for this module were
unfortunately not catching this misbehavior.
For this fix we add a function to the tcti module to assist in
marshalling the response header back out to the caller provided buffer.
The unit test for the device TCTI has also been updated to compare the
response buffer received by the client to the pre-canned response buffer
that the mock framework uses when mocking the 'read' function.
> tcti-device: Copy response header to output buffer in receive function.

- Makefile-test.am
- Makefile.am
- configure.ac
- src/tss2-esys/esys_crypto.c
- src/tss2-esys/esys_tcti_default.c
- src/util/log.h
- test/unit/esys-default-tcti.c
Two very minor commit first that I just split out before the actual changes.
The ESAPI gains a new behavior for initializing the
default TCTI.
- The configure flag is now interpreted as a file
instead of as a partial symbol name.
- If a default tcti is configured only this file is
loaded.
- If no default tcti is configured, esys will attempt
to load a tcti in the following order
- Search for a libtss2-tcti-default.so
- Search for a libtss2-tcti-tabrmd.so
- Attempt the linked Tcti_Device for "/dev/tpmrm0"
- Attempt the linked Tcti_Device for "/dev/tpm0"
- Attempt the linked Tcti_Mssim for "localhost:2321"
@williamcroberts I'd like to get your opinion from the tpm2-tools perspective as well.
> ESAPI Change the default TCTI initialization

- .gitignore
- Makefile-test.am
- Makefile.am
- script/int-log-compiler.sh
- test/helper/tpm_startup.c
- test/helper/tpm_transientempty.c
- test/integration/asymmetric-encrypt-decrypt.int.c
- test/integration/create-keyedhash-sha1-hmac.int.c
- test/integration/create-primary-rsa-2048-aes-128-cfb.int.c
- test/integration/encrypt-decrypt-2.int.c
- test/integration/encrypt-decrypt.int.c
- test/integration/esys-hmacsequencestart.int.c
- test/integration/esys-policy-password.int.c
- test/integration/esys-quote.int.c
- test/integration/esys-rsa-encrypt-decrypt.int.c
- test/integration/esys-save-and-load-context.int.c
- test/integration/evict-ctrl.int.c
- test/integration/main-esapi.c
- test/integration/main.c
- test/integration/policy-template.int.c
- test/integration/system-api.int.c
- test/tpmclient/tpmclient.int.c
This is the very first step towards having the tests run on actual TPMs.
In this step we
- Fix leaking integration tests
- Move TPM_startup into the simulator test harness
- Add a guard around integrations tests to look for transent objects before  and after the test.
> Rework tests wrt transient objects

- src/tss2-sys/api/Tss2_Sys_SetDecryptParam.c
SetDecryptParam needs the same sequence checking as
the GetDecryptParam counterpart.
> SAPI: Fix sequence checking

- src/tss2-sys/api/Tss2_Sys_Execute.c
- src/tss2-sys/api/Tss2_Sys_GetRpBuffer.c
- src/tss2-sys/api/Tss2_Sys_SetCmdAuths.c
- src/tss2-sys/sysapi_util.c
- src/tss2-sys/sysapi_util.h
Following a NOTE that this should be removed and analyzing
it's use, it appears that it can just be safely deleted.
The commonOneCall and *_Finish code both will never get called
if they experience an error in the synchronous cases.
In the async case, all those API calls return errors
and thus the further stages in the state machine should
not be called.
To reset your sapi context, it appears one can just call
Tss2_Sys_Initialize() on the previously established
sapi context.
> drop the return value from the context structure

- README.md
Fix typos and spelling in README.md:
s/Enhanded/Enhanced/
s/unstalled/installed/
s/integraion/integration/
s/uint/unit/
s/later/latter/
Also fix grammar.
Fixes #895.
> README.md: Fix Typos, Spelling, and Grammar.

- test/integration/main-esapi.c
- test/integration/main.c
All ESAPI tests are all passing fine as they run it the harness,
but when run as a single tests they all fail with error code 0x00000100:
"TPM not initialized by TPM2_Startup or already initialized"
This is bacause the Tss2_Sys_Startup is only called from main in
test/integration/main.c, but not from main in test/integration/main-esapi.c
Add Esys_Startup() into test/integration/main-esapi.c to enable
invocation of the esapi test as single tests.
> test: esapi: enable esapi single tests

- .travis.yml
We now short-circuit the build if the COVERITY_SCAN_BRANCH is set in the
'script' section of .travis.yml. At this point the coverity build has
already happened and there's no point in running the rest of our typical
build / test cycle.
The number of `jobs` used in the coverity build has been reduced from
`$(nproc)*2` to just `$(nproc)` to align with the rest of the builds.
All scan tokens appear to have been refreshed and so we've created a new
encrypted variable for it. Finally the scan service is also rejecting
access if the `name` for the project is reported as anything other than
`01org/TPM2.0-TSS`.
> ci: Get coverity running again accounting for changes after the outage.

- src/util/io.c
- test/unit/io.c
- test/unit/tcti-mssim.c
Add IPv6 client socket support.
This results in dual-stack IPv4/IPv6 support for client socket connections.
Fixes #876.
> IPv6 Client Socket Support

- lib/tss2-sys.def
This PR resolves #916 and #900. Just some meta-data that got messed up in the Windows linker module definition file.
> Windows def name symbols

- include/tss2/tss2_sys.h
- lib/tss2-sys.def
- src/tss2-sys/api/Tss2_Sys_Finalize.c
According to the spec `Tss2_Sys_Finalize` returns void. Also the spec
does not include an async version of the Finalize function and so the
`Tss2_Sys_Finalize_Complete` function makes no sense.
> tss2-sys: Tss2_Sys_Finalize now returns void, remove '_Complete'.

- Makefile-test.am
- Makefile.am
- src/tss2-tcti/tcti-common.c
- src/tss2-tcti/tcti-common.h
- src/tss2-tcti/tcti-device.c
- src/tss2-tcti/tcti-device.h
- src/tss2-tcti/tcti-mssim.c
- src/tss2-tcti/tcti-mssim.h
- test/integration/sys-initialize.int.c
- test/unit/tcti-device.c
- test/unit/tcti-mssim.c
Using the same structure for both the device and mssim TCTI was lazy. We
were also using the same magic number for both modules which had the
potential to cause confusion if one library was passed a TCTI
initialized by the other. This patch resolves both of these issues by
breaking the old TSS2_TCTI_CONTEXT_INTEL structure up into the
TSS2_TCTI_COMMON_CONTEXT and a structure specific to the device and
mssim TCTIs.
To accomplish this we rename the old 'tcti' module to 'tcti-common'.
This module defines a context structure containing all of the data
common to both the device and mssim TCTIs. This includes the v2
structure as well as a header structure, the enumeration to track the
state machine as well as the locality. We also create new header files
for the device and mssim TCTI. In these …
> tcti: Use separate structures for the device and mssim TCTI contexts.

- src/tss2-sys/sysapi_util.c
This comment is not relevant. We don't have ctx->rval anymore.
> sapi: cleanup old comment

- configure.ac
To build binaries with debug info the configure script takes
--enable-debug=yes flag (default no). This produces makefiles
with EXTRA_CFLAGS = -Og flag. The problem is that autotools
still produces CFLAGS = -g -O2 by default, which affects
the debug info. To swith off the default optimization flags
we need to set CFLAGS="" before AC_PROG_CC macro, and then
add optimizations to EXTRA_CFLAGS if debug is not enabled.
See AC_PROG_CC section in:
https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/C-Compiler.html
> build: disable default -O2 flag

- CHANGELOG.md
- CONTRIBUTING.md
- INSTALL.md
- Makefile.am
- RELEASE.md
Fix spelling errors in documentation, messages and comments.
Fixes #926.
> Fix Spelling Errors

- src/tss2-mu/base-types.c
- src/tss2-mu/tpm2b-types.c
- src/tss2-mu/tpma-types.c
- src/tss2-mu/tpml-types.c
- src/tss2-mu/tpms-types.c
- src/tss2-mu/tpmt-types.c
- src/tss2-mu/tpmu-types.c
- src/tss2-sys/api/Tss2_Sys_Execute.c
- src/tss2-sys/api/Tss2_Sys_GetRpBuffer.c
- src/tss2-sys/sysapi_util.c
- src/tss2-tcti/tcti-mssim.c
Fix spelling errors in src directory.
Fixes #936.
> src: Fix Spelling Errors

- src/tss2-tcti/tcti-device.c
- test/unit/tcti-device.c
The linux kernel driver closes connections that don't read the full
response buffer	in one read. This requires that the device TCTI
do exactly this to keep our FDs closed prematurely. It also means we
can't read the response header to know the size of the response ahead
of reading the response body.
If the caller queries for the size of the response before providing us
with the buffer (by providing a NULL buffer) then we just tell them to
give us a 4k buffer to be safe. We do not however require that the
buffer be this large to allow "expert" applications that may want to
precalculate the size of their response buffers in advance.
This commit also updates the unit tests to account for this change.
Signed-off-by: Philip Tricca <flihp@twobit.us>
> tcti: Replace 2 read calls in the 'receive' function with a single read.

- src/tss2-sys/api/Tss2_Sys_ClockRateAdjust.c
Tss2_Sys_ClockRateAdjust falsely marshaled a
UINT32 for rateAdjust, where it should have been
a UINT8.
> SAPI: Fix type of marshalling

- src/tss2-sys/api/Tss2_Sys_AC_Send.c
Fix a case of unused return codes in Tss2_Sys_AC_Send.
This is the only clang scan-build error currently.
> SAPI: Fix unused return codes

- test/unit/tcti-device.c
Inside the teardown function, it converts a pointer to wrong type.
This commit fixes the bug.
Signed-off-by: Ying-Chun Liu (PaulLiu) <paulliu@debian.org>
> test/unit/tcti-device.c: fix unit test fail on armel, armhf, mipsel

- test/integration/session-util.c
Fix scan-build warnings in session-util.c introduced with #967.
Fixes #971.
> test: Fix scan-build Warnings

- INSTALL.md
Document that uthash Development Files are required after
the integration of #967.
Fixes #972.
> Document That uthash Development Files Are Now Required

- Makefile.am
With the assignment / definition of the udevrules_DATA wrapped in a
conditional checking for WITH_UDEVRULESPREFIX then we only have a _DATA
variable defined when the configure script was provided with a prefix.
This prevents the installation of the udev rules under the most common
configure case: ./configure && make && make install
The fix is trivial: remove the conditional.
> build: Fix udev rule when no file prefix is provided.

- include/tss2/tss2_tcti.h
- src/tss2-tcti/tcti-device.c
- src/tss2-tcti/tcti-mssim.c
- test/unit/esys-default-tcti.c
This is based on feedback from TCG TSS2 working group. The 'magic'
field in the INFO structure isn't necessary or useful. This allows us to
remove the VERSION type all together and just use a uint32_t in its
place. The macros in the header are updated as well.
> tcti: Remove TSS2_TCTI_VERSION type, replace with simple uint32_t.

- src/tss2-esys/api/Esys_Commit.c
- src/tss2-esys/api/Esys_Create.c
- src/tss2-esys/api/Esys_CreatePrimary.c
- src/tss2-esys/api/Esys_Duplicate.c
- src/tss2-esys/api/Esys_ReadPublic.c
Initialize the output pointers (starting with the third parameter) to NULL in order to prevent a dereferencing of uninitialized pointers duirng error handling.
Fixes: #981
> ESAPI: Initialize outputs to NULL.

- .appveyor.yml
Dan fixed the release builds a while back but the AppVeyor yml file was
never updated to get these on the build matrix.
> build: Add 'Release' builds to .appveyor.yml

- .travis.yml
- INSTALL.md
- Makefile-test.am
- README.md
- configure.ac
- script/int-log-compiler.sh
Bill recently integrated the tools integration tests into the test
harness and his approach assumes that the `tpm_server` binary is on the
PATH. This simplifies a few thing and generally it's just cleaner than
requiring the caller to pass the full path to the executable at
configure time.
This patch removes the --with-simulatorbin configure option replacing it
with the --enable-integration option instead. This option takes no
parameters but it does check that the 'tpm_server' binary is on the
callers path. Additionally this patch consolidates the multiple AC_IF
checks for the definition of the associated variable. The corresponding
option to the int-log-compiler.sh script is removed as well.
> build: Remove --with-simulatorbin, replace with --enable-integration.

- src/tss2-esys/esys_crypto.c
- src/tss2-esys/esys_iutil.c
- src/util/log.c
- test/integration/esys-create-fail.int.c
- test/integration/esys-create-password-auth.int.c
- test/integration/esys-save-and-load-context.int.c
- test/integration/esys-unseal-password-auth.int.c
- test/integration/sapi-abi-version.int.c
- test/integration/sapi-asymmetric-encrypt-decrypt.int.c
- test/integration/sapi-sys-initialize.int.c
- test/tpmclient/tpmclient.int.c
Replace
// C++ comments
in C source code with
/* C comments. */
Fixes #1009.
> Replace C++ Comments in C Source Code with C comments

- src/tss2-esys/esys_crypto.c
Fix two potential null ptr dereference issues reported by ceverity.
CID 1468838:  Null pointer dereferences  (REVERSE_INULL)
Null-checking "partyUInfo" suggests that it may be null,
but it has already been dereferenced on all paths leading to the check.
CID 1468837:  Null pointer dereferences  (REVERSE_INULL)
Null-checking "partyVInfo" suggests that it may be null,
but it has already been referenced on all paths leading to the check.
> esys_crypto: fix defects reported by Coverity Scan

- INSTALL.md
- configure.ac
- script/int-log-compiler.sh
I just ran a full build and integration test run on a fresh build system
installing only things that the configure script tested for. Everything
built fine but the test harness hung. This happened because the netstat
utility was missing. I hadn't installed net-tools (Debian).
This commit adds an explicit check for this tool @ configure time. The
integration test wrapper has also been instrumented to ensure that
netstat is on the PATH as well. This causes tests to fail early instead
of timing out because all checks for simulator port conflicts fail which
cause retries and backoff timeouts.
The INSTALL documentation is also updated to include mention of the need
for netstat / the net-tools package.
> build: Add checks for 'netstat' @ configure and integration test time.

- INSTALL.md
This dependency was removed some time back but the docs were never
updated.
> doc: Remove liburiparser-dev from Ubuntu example in INSTALL.md

- src/tss2-esys/esys_iutil.c
The spec [1] in isection 3.8.2.3 says that if decryptParamSize is 0 then
decryptParamBuffer is unspecified.
[1] https://trustedcomputinggroup.org/wp-content/uploads/TSS_SAPI_v1.1_r21_Public_Review.pdf
> esapi: fixes for encrypt param function

- CHANGELOG.md
This is a collection of nit-picks on language in the changelog.
Additionally I've added specific reference to the libraries by their
full name (libtss2-*) for clarity. The item about the new VS build stuff
now notes that only a subset of the TSS2 libraries will build.
> CHANGELOG.md: Nit-picking language & location / nature of some changes.

- CHANGELOG.md
> CHANGELOG.md: Document fix to AC commands.

- test/integration/esys-pcr-basic.int.c
This fixes #1028 
TPM Spec Part 4, A.2 names the PCRs 17 and 0 for DRTM and HCRTM.
If DRTM and HCRTM were not defined, adding these PCRs to pcrSelections is unnecessary but harmless. Apart from the PCR_Allocate, only a PCR_Read is performed with this selection.
> Tests: Fix test that is not spec-conform

- test/integration/sapi-policy-template.int.c
A parent key is required to use the symmetric mode TPM2_ALG_CFB according to the Spec.
This fixes #1033
> Use correct symmetric mode for parent primary key in test

- test/integration/sapi-command-cancel.int.c
Since the command that raised the error is designed specifically for the simulator, it can be expected to fail on anything else.
This fixes #1037
> Skip the command cancel test if no simulator is used

- test/integration/esys-clear-control.int.c
- test/integration/esys-hierarchy-control.int.c
Fixes #1023 
As discussed in the issue, the "r" which is returned in case of an error would always be evaluated to "0", making the whole test impossible to fail.
> test: Allow tests that expect an error to fail

- test/integration/esys-hierarchychangeauth.int.c
Addressing #1030 
The arbitrary auth that is set in the test keeps following tests from using this hierarchy.
Changing it back to the default, which is an empty auth, solves the problem.
> test: Change the ownerAuth back to an empty buffer

- test/integration/esys-evict-control-serialization.int.c
Addresses #1030 
Other tests are using the same permanent handle (TPM2_PERSISTENT_FIRST).
This leads to an error.
> test: Delete a key that has been made persistent

- .travis.yml
- README.md
Coveralls hasn't been able to recover from our transition from the Intel
01org github org to the new tpm2-software org. Coveralls has started
returning errors for this repo and since I haven't even been able
to login to the coveralls.io website for the last few months debugging
this is impossible.
This commit leaves all of the mechanics of collecting code coverage
metrics intact. It only disables use of the coveralls webservice for
maintaining history and providing an interface to the data. This is a
short term solution to get our builds passing again.
> build: Remove use of coveralls

- test/integration/esys-nv-ram-extend-index.int.c
Addressing #1030 
Following tests get the error TPM_RC_NV_DEFINED beacuse they try to define the same space again.
> Tests: Undefine NV space when necessary

- test/integration/esys-commit.int.c
- test/integration/esys-tr-fromTpmPublic-key.int.c
- test/integration/sapi-encrypt-decrypt-2.int.c
- test/unit/esys-getpollhandles.c
According to the coding standard, white spaces are prohibited. Fixing #1051
> Remove trailing whitespaces

- src/tss2-esys/esys_tr.c
[updated]
Fix a bug in Esys_TR_Deserialize where no correct ESYS_TR handle was returned to the caller.
> ESYS: Fix handle returning in Esys_TR_Deserialize

- test/integration/esys-audit.int.c
- test/integration/esys-certify-creation.int.c
- test/integration/esys-certify.int.c
- test/integration/esys-commit.int.c
- test/integration/esys-create-fail.int.c
- test/integration/esys-create-password-auth.int.c
- test/integration/esys-create-primary-hmac.int.c
- test/integration/esys-create-session-auth.int.c
- test/integration/esys-createloaded.int.c
- test/integration/esys-ecdh-keygen.int.c
- test/integration/esys-ecdh-zgen.int.c
- test/integration/esys-get-time.int.c
- test/integration/esys-nv-certify.int.c
- test/integration/esys-quote.int.c
- test/integration/esys-save-and-load-context.int.c
- test/integration/esys-zgen-2phase.int.c
The PC client TPM profile only requires CFB mode for TPMs.
ECB mode is denoted as 'should not'.
This patch changes occurences of ECB mode to CFB mode in
ESYS tests.
> TEST ESYS: Switch from ECB to CFB mode.

- include/tss2/tss2_esys.h
The header constants are made unsigned.
> ESYS: Fix esys header file.

- doc/doxygen.dox
The parameter declarations of some ESAPI commands were adapted to the
current API.
> DOXYGEN: Fix wrong doxygen declarations.

- src/tss2-sys/api/Tss2_Sys_Execute.c
Report a more informative message when the device is a TPM 1.2 dev.
> sapi: check for 1.2 TPM response

- .appveyor.yml
- lib/tss2-tcti-mssim.def
- src/tss2-mu/tss2-mu.vcxproj
- src/tss2-sys/tss2-sys.vcxproj
- src/tss2-tcti/tcti-common.c
- src/tss2-tcti/tcti-device.c
- src/tss2-tcti/tcti-mssim.c
- src/tss2-tcti/tcti-mssim.h
- src/tss2-tcti/tss2-tcti-mssim.sln
- src/tss2-tcti/tss2-tcti-mssim.vcxproj
- src/tss2-tcti/tss2-tcti-mssim.vcxproj.filters
- src/util/io.c
- src/util/io.h
- tpm2-tss.sln
Add conditional inclusion directives to separate POSIX and Windows
specific code.
Replace hard coded -1 values with SOCKET_ERROR and INVALID_SOCKET.
Add Visual Studio solution for Simulator TCTI
Add .def file for building the Simulator TCTI dll
Rewrite the TEMP_RETRY macro. Previously this macro was a stement
expression; statement expressions are part of the non-standard gcc
extension statement-exprs.
When compiling on Windows:
- Initialize winsock
- Replace errno with WSAGetLastError()
- Replace "read" with "recv"
- Replace "write" with "send"
- Replace "close" with "closesocket"
- Set _HOST_NAME_MAX to MAX_COMPUTERNAME_LENGTH instead of
_POSIX_HOST_NAME_MAX
- Map strtok_r to strtok_s
Turn off parallel build in Appveyor
Fixes #671, #672
Signed-off-by: David Maria <davidjmaria@fb.com>
> tcti: Port sumulator TCTI to Windows

- src/tss2-esys/tss2-esys.vcxproj
- src/tss2-esys/tss2-esys.vcxproj.filters
Add new esys_crypto_gcrypt.c/h files to the Visual Studio solution for ESYS
to fix the current Windows build failures.
> build: Add esys_crypto files to ESYS VS Solution

- src/tss2-esys/api/Esys_Startup.c
Addressing #1025.
Receiving TPM2_RC_INITIALIZE after a Startup command is not really an
error (The TPM simply already is in the desired state).
The user does not have to take any further action to interact with
the TPM and thus does not need the log message.
> ESAPI: Fixed unnecessary warning in Esys_Startup.

- .travis.yml
The test harness will dump the output from failing tests by default.
Doing this manually is redundant, and dumping the output from successful
tests clutters the output unnecessarily.
> ci: Stop manually dumping test logs.

- .travis.yml
All of these things were infating our coverage numbers.
> ci: Exclude dependencies and tests when collecting code coverage data.

- test/integration/esys-audit.int.c
- test/integration/esys-change-eps.int.c
- test/integration/esys-clear-control.int.c
- test/integration/esys-clockset.int.c
- test/integration/esys-hierarchy-control.int.c
- test/integration/esys-lock.int.c
- test/integration/esys-pcr-auth-value.int.c
- test/integration/esys-pcr-basic.int.c
- test/integration/esys-policy-nv-undefine-special.int.c
- test/integration/esys-pp-commands.int.c
- test/integration/esys-set-algorithm-set.int.c
The usage of the mask to get the return code was fixed.
> TEST ESYS: Fix wrong check of bad authorization.

- src/tss2-esys/esys_crypto_gcrypt.c
- src/tss2-esys/esys_crypto_ossl.c
TPM spec part 2 says: When zero, indicates that the exponent is the default of 2**16 + 1.
This default now will be used in the corresponding crypto functions.
> ESYS: Fix RSA encryption with exponent == 0

- Makefile-test.am
- src/tss2-esys/esys_crypto.c
Minor fixes to allow building tss2-esys with the openssl crypto backend without installing grcypt.
> Esys ossl cleanup

- src/tss2-sys/tss2-sys.vcxproj
This change completes the migration from the Clang/C2 PlatformToolset to
LLVM-vs2014. This migration was initiated as the solutions for the
tss2-tcti-mssim and tss2-esys were added.
> build: Change tss2-sys solution to use LLVM-vs2014 PlatformToolset

- src/tss2-sys/api/Tss2_Sys_ECC_Parameters.c
The base type of TPMI_ECC_CURVE is UNIT16 not UINT32.
> SAPI: Fix marshaling in Tss2_Sys_ECC_Parameters.

- test/integration/esys-clockset.int.c
* The wrong field of the structure TIME_INFO was used to determine the current clock.
* This test  worked with the simulator but did fail with a physical TPM (in most cases).
* Also the error check was fixed.
> TEST ESYS: Fixed test clockset.

- Makefile-test.am
- doc/doxygen.dox
- test/integration/esys-create-session-auth.int.c
- test/integration/esys-ecc-parameters.int.c
- test/integration/esys-hash.int.c
- test/integration/esys-hmac.int.c
- test/integration/esys-lock.int.c
- test/integration/esys-nv-ram-ordinary-index.int.c
* The two new integration tests were added to the mandatory tests.
* The test clockset was moved from optional to mandatory tests.
* Doxygen comments were updated.
* Also some minor formatting fixes were added.
> ESYS TEST: Added tests for Esys_HMAC and Esys_Hash and minor fixes.

- src/tss2-esys/esys_crypto_gcrypt.c
* Fixed sizes for the binary data are used in all cases.
* Variable sizes caused race conditions in RSA encryption and
ECDH key exchange:
* TPM decryption with OAEP failed in rare cases when the cipher size
computed by gcry_mpi_print is lower than the key size
(With openSSL and gcrypt it's possible to decrypt such ciphers).
* The computation of the shared secret failed in rare cases when the
size of the x coordinate of the product Q*d  computed by
gcry_mpi_print(in function iesys_cryptogcry_get_ecdh_point)
is lower than the maximum size of a point coordinate.
> ESYS: Fix conversion of gcrypt mpi numbers to binary data.

- Makefile.am
- m4/ax_prog_doxygen.m4
Number of issues with doxygen encountered on make distcheck.
This change fixes the problems.
> build: doxygen causes make distcheck to fail

- include/tss2/tss2_esys.h
- lib/tss2-esys.def
- src/tss2-esys/esys_free.c
- src/tss2-esys/tss2-esys.vcxproj
- src/tss2-esys/tss2-esys.vcxproj.filters
Add esys_free, a wrapper around free(), to ESYS when building on Windows.
Having a wrapper around free is best practice when building libraries
on Windows; this is because there is a high chance that the caller
program will be built using a different version of the C runtime
than the library, which means that the program and the library will have
separate heaps. This is an issue because many of the ESYS functions
allocate memory for the caller and expect the caller to free the memory,
but in the case where the caller was built with a different version of
the C runtime, the caller will not be able to free the memory because
it does not have access to the esys heap. esys_free allows the caller
program to have the library free any memory that the caller didn't allocate.
Signed-off-by: David …
> [RFC] ESYS: Add esys_free helper function

- src/tss2-esys/esys_crypto_gcrypt.c
The mpi2bin function is local to crypto_gcrypt and should
be defined as static.
> esapi: change mpi2bin to static

- src/util/io.c
When building for the s390 architecture the following warning occurs
which leads to a build error:
```
src/util/io.c:70:9: error: format '%x' expects argument of type 'unsigned int', but argument 10 has type 'long unsigned int' [-Werror=format=]
LOG_DEBUG("writing %zu bytes starting at 0x%" PRIxPTR " to fd %d",
```
size_t is of a different type than uintptr_t on s390. Due do integer
type promotion the type won't match the PRIxPTR specifier any more after
adding to it.
Arithmetic should be done with the pointer, not the uintptr_t. This will
fix will the warning.
Signed-off-by: Matthias Gerstner <matthias.gerstner@suse.de>
> util: fix a format warning that can occur on some platforms

- configure.ac
There is a typo in AS_HELP_STRING for --with-ptpm.
One parenthesis is in wrong place.
While fixing that also clean up two white space issues,
which are not worth a separate commit.
> configure.ac: cleanup configure.ac file

- src/tss2-esys/api/Esys_StartAuthSession.c
- src/tss2-esys/esys_int.h
The struct StartAuthSession_IN contained a field
encryptedSaltData that was unused, remove it.
> esapi: remove unused field from struct

- Makefile-test.am
- configure.ac
Fix default tcti configuration setting passing and the corresponding unit test.
> ESYS: Fix default tcti configuration

- src/tss2-sys/api/Tss2_Sys_Execute.c
In case of an invalid tag in the TPM's response, Tss2_Sys_Execute.c
prints that tag using LOG_ERROR. It uses the platform's format string
for 32-bit varibles. The structure definition of the response header
defines a 16-bit variable for the tag. This leads to format string
warnings on some platforms. Therefore, the format string was changed
from PRIx32 to PRIx16, the platform's format string for 16-bit
variables.
* Changed the format string for the response tag in a call to the logging
function in Tss2_Sys_Execute.c
Signed-off-by: Lukas Jäger <lukas.jaeger@sit.fraunhofer.de>
> SAPI: Fixed a bug in the logging of a response header tag in execute

- configure.ac
* The misleading help string for --disable-esapi is deleted.
* --disable-FEATURE explained in the help output already describes how to
deactivate ESAPI.
> ESYS: Delete unnecessary help string in configure.ac

- Makefile-test.am
- src/tss2-esys/esys_context.c
- src/tss2-esys/esys_int.h
- src/tss2-esys/esys_tcti_default.c
- src/tss2-esys/esys_tcti_default.h
- test/unit/esys-default-tcti.c
- test/unit/esys-nulltcti.c
- The handle of dlopen used to leak. Save this handle and dlclose on Esys_Finish().
- ESYSFLAGS was actually never set. Probably leftover from an earlier version.
> ESYS: Fix leak of dlopen handle and Makefile

- src/tss2-esys/esys_tcti_default.c
- src/tss2-tcti/tcti-mssim.c
- test/unit/esys-default-tcti.c
…fault.
* The config string was set to "" in the ESYS default table. The value now is set to NULL.
If config string is NULL the used TCTI module will use the default value instead of ""
* The corresponding fake routines in the unit test were adapted to accept a null  pointer
for config parameter.
* This fix allows changing of the default library without recompiling, which was not
possible before.
> ESYS: Fix default value for config string in TCTI default table

- CONTRIBUTING.md
New guidelines to keep the prefix components persistent in commit
messages for the enhanced and system APIs.
> CONTRIBUTING.md: add guidelines for commits to sys and esys components

- .travis.yml
- src/tss2-esys/esys_crypto_ossl.c
- Fixes #1157 
- Adds OpenSSL (in two versions) to tests.
@flihp @tstruk Hope to get this in before 2.2 (since the code-change is small)
> Fix OpenSSL crypto backend

- Makefile-test.am
- test/integration/sapi-stir-random.int.c
Add a simple test for StirRandom to increase code coverage.
It does only check whether the command itself works and returns success
for suitable input data.
> test: Add integration test for StirRandom

- Makefile-test.am
autotools does not like variables to end on _LDFLAGS and spits out
warnings. So we rename the variable.
Addresses issue posted in #1159 review.
> Build: Fix autotools warning on _LDFLAGS

- configure.ac
- lib/tss2-esys.pc.in
Switch the default ESAPI crypto backend to openSSL.
This should also fix the problem with forcing applications to
link against libgcrypt.
> switch default ESAPI crypto backend to openSSL

- test/unit/TPM2B-marshal.c
tpm2b unit test fails on big endian machines
> test: fix tpm2b unit tests failing on big endian

- LICENSE
It seems to confuse some tools if the SPDX appears in the License file - e.g. Github which did not show the LICENSE in the right tab.
Signed-off-by: Peter Huewe <peter.huewe@gmx.de>
> Remove SPDX from LICENSE itself

- m4/misc.m4
ERROR_IF_NO_PROG macro doesn't work as intended.
See https://github.com/tpm2-software/tpm2-tss/issues/1181
> fix ERROR_IF_NO_PROG

- configure.ac
- m4/flags.m4
The 'AX_' prefix is the namespace for the autoconf archive macros. We
shouldn't be using a namespace belonging to another project.
Signed-off-by: Philip Tricca <flihp@twobit.org>
> build: Remove 'AX_' prefix from local m4 flag macros.

- configure.ac
This fixes a bug introduced in 3980bad87fe18ad9d32914e9d21dba145eba973f.
That patch references the documentation for AC_PROG_CC but it misread
the recommended workaround. The leading colon (aka `:`) in the
documentation is significant.
The `:` is a shell 'builtin' command that is equivalent to invoking the
'true' command. By placing the conditional substitution of the CFLAGS
after this, the result of the substitution will be ignored and the
script won't fail. Without this the contents of the CFLAGS variable set
in the environment will be interpreted as a command and since they're
not commands the configure script will abort.
Signed-off-by: Philip Tricca <flihp@twobit.org>
> build: Fix breakage in generated configure script when CFLAGS is set.

- CONTRIBUTING.md
We are now tpm2-software not 01.org anymore :)
> Fix project URL in CONTRIBUTING

- Makefile.am
- configure.ac
- include/tss2/tss2_tcti.h
QNX-specific quirks:
*   Certain "netdb.h" API is only available if __EXT_POSIX1_200112 is
defined. __EXT_POSIX1_200112 is defined if "_XOPEN_SOURCE" is set
to 600.
*   Socket api is provided through separate library called "libsocket".
*   Dynamic-library API (e.g. dl_open) is a part of libc. There is no
"libdl".
Makefile.am:    Replaced hard-coded LDFLAGS, "-ldl" and "-lsocket"
with variables, LIBDL_LDFLAGS, and LIBSOCKET_LDFLAGS.
configure.ac:   Added "$host_os" case statement to detect QNX targets
and modify CFLAGS and set the XXX_LDFLAGS as required.
tss2_tcti.h:    Added "__QNXNTO__" to the list of OS-specific flags.
Signed-off-by: Safayet Ahmed <safayet.ahmed@ge.com>
> Added support for QNX build

- Makefile-test.am
- Makefile.am
- configure.ac
> build: Use SPDX license identifier in autoconf & automake files.

- src/tss2-tcti/tcti-mssim.c
Commit 54090544832a00fb78c65a91fc45e67c77fbd936 broke the build for all
loglevels other than 'trace':
src/tss2-tcti/tcti-mssim.c: In function ‘Tss2_Tcti_Mssim_Init’:
src/tss2-tcti/tcti-mssim.c:512:5: error: ‘else’ without a previous ‘if’
else
^~~~
Explicitly enclosing the scope of this conditional with curly braces
is the most simple solution.
> build: Fix breakage when --with-maxloglevel is not 'trace'.

- configure.ac
The preprocessor, compiler, and linker flags that we chose as the
default were chosen for a reason. But we can't possibly know that they
make sense for every possible user or environment. This commit adds a
new flag to the configure script that allows users to disable / omit
all of these flags if they choose to (--disable-defaultflags).
> build: Add configure option to enable / disable default flags.

- configure.ac
Fix #1204: The doxygen feature is controlled by the variable <code>$*enable*_doxygen_doc</code>, which is why the current check does not work.
> configure: fix check for doxygen

- configure.ac
> build: Fix malformed AC_HELP_STRING for defaultflags help output.

- INSTALL.md
We need at least version 2017.03.21 because we rely on
- [`DX_RULES`](https://github.com/tpm2-software/tpm2-tss/blob/6751b3c1ec21710e0d54ae38d28b3940f0499c18/Makefile.am#L25) from `ax_prog_doxygen.m4`, which was [introduced in version 2016.03.20](https://github.com/autoconf-archive/autoconf-archive/commit/5ef1e0b754692f089fa031100deeca1d05693fe6) and
- [`CODE_COVERAGE_LIBS`](https://github.com/tpm2-software/tpm2-tss/blob/6751b3c1ec21710e0d54ae38d28b3940f0499c18/Makefile.am#L10) from `ax_code_coverage.m4`, which was [introduced/renamed in version 2016.03.20](https://github.com/autoconf-archive/autoconf-archive/commit/b812cb0104efaa25ce2f067a950fbf2abc36ebe5), but [fixed in **2017.03.21**](https://github.com/autoconf-archive/autoconf-archive/commit/79faac8a16841490a729fd22e7711696435ec6f8). …
> doc: specify minimum required version for autoconf-archive

- Dockerfile
Since #1184 `./configure` checks for the presence of doxygen, but the
Docker image does not include it, hence the build failed. (closes
Signed-off-by: Julien Hachenberger <julien.hachenberger@sit.fraunhofer.de>
> Dockerfile: Add doxygen package

- include/tss2/tss2_tpm2_types.h
* Missing type casts are added as defined in "TCG TSS 2.0 Overview and Common Structures Specification".
*  Wrong type name _ID_OBJECT is fixed.
* The type The type TPM2_NT is added.
> TPM Types: Fix tss2_tpm_types.h

- README.md
The Linux Foundation Core Infrastructure Initiative (CII) Badge is a self-certification program for open source software to assess whether they are following the best practice guidelines for healthy open source projects.
The tpm2-tss is growing in size and influence and is starting to become critical core infrastructure, so it is time to do the self assessment.
The Badge adds a link to the assessment and also shows the progress to our users.
Signed-of-by: Peter Huewe <peterhuewe@gmx.de>
> Core Infrastructure Initiative (CII) Badge

- src/tss2-esys/api/Esys_StartAuthSession.c
- src/tss2-esys/esys_iutil.c
- src/tss2-esys/esys_tr.c
* In the function  Esys_TRSess_SetAttributes a Null pointer check was added
because the function esys_GetResourceObject returns TSS2_RC_SUCCESS for the handle
ESYS_TR_NONE and a null pointer for the session object.
*  The size of an hmac value of a session was only set for objects with authorization.
* An unnecessary size check in StartAuthSession was removed.
The check whether the secret size is zero can be removed because  size zero is
possible if no tpmKey for encryption is used and the authValue of the bind
object has length 0.
> Fix esys session handling

- configure.ac
- src/tss2-sys/api/Tss2_Sys_GetRspAuths.c
- test/integration/sapi-session-util.c
Add strict signed overflow checking which is an undefined behavior and thus can have weird side-effects based on compiler and compiler settings.
> Strict overflow flag

- .travis.yml
Looks like Doxygen causes some builds problems on travis
Disable it for now until it is resolved.
> travis: temporarily disable doxygen

- src/tss2-mu/tpm2b-types.c
- test/unit/TPM2B-marshal.c
* The offset was not computed correctly if a NULL buffer was passed.
The TSS MU spec states: If the 'buffer' parameter is NULL the
implementation shall not write any marshaled data but the 'offset'
parameter shall be updated as as though it had.
* The unnecessary test of NULL buffer and not NULL offset was removed
and the corresponding unit test was adapted.
* Also a unit test which compares the result of NULL buffer and
not NULL buffer marshaling was added.
> MU: Fix marshaling of TPM2Bs with sub types.

- .travis.yml
- Makefile.am
- test/integration/esys-create-session-auth.int.c
- test/integration/sapi-entity-util.c
- test/integration/sapi-session-util.c
Travis now provides a Xenial image, see https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures and https://github.com/tpm2-software/tpm2-abrmd/pull/561/. This allows us to use the packaged versions of cmocka and Doxygen instead of building them from source, which should make the CI a bit more robust.
The updated version of Clang in the image reports some additional bugs with `scan-build`, which need to be addressed so that the build passes.
Somewhat unrelated, I also removed an invalid `CLEANFILES` directive in the Makefile related to Doxygen. This does not lead to errors, but adds noise by generating an extra warning
```
rm: cannot remove 'doxygen-doc': Is a directory
make: [Makefile:14043: clean-generic] Error 1 (ignored)
```
> travis: update to Xenial VM

- src/tss2-esys/esys_crypto_ossl.c
In some cases, when built with the `openssl` crypto backend, `ENGINE_by_id("openssl");` fails with the error that no engine named `libopenssl.so` was found in the openssl `engines/` directory.
Specifically, I ran into errors experimenting with `openssl` `s_server` with the `tpm2tss` engine which uses the ESYS API. This was in a container with an Alpine base image. My tss libraries were compiled with the `openssl` crypto backend.
Loading the engine explicitly with a call to `ENGINE_load_builtin_engines` eliminates this error.
> esys_crypto_ossl.c: load engine explicitly

- Dockerfile
- INSTALL.md
- configure.ac
- script/int-log-compiler.sh
I dug a little deeper into #1227, which I can reproduce with some reliability on my machine when running several tests in parallel (e.g. `make -j16 check`). Apparently `tpm_server` sometimes fails to bind to the IPv4 interface, but succeeds in binding to the IPv6 interface, even though I am not entirely sure why that happens (the port doesn't appear to be used by other instances of the simulator or anything else on the system). As the [netstat check whether binding the port succeeded](https://github.com/tpm2-software/tpm2-tss/blob/266af7ffa335b9b0ef59f6e5fe541a774cb203a1/script/int-log-compiler.sh#L205) sees the IPv6 binding, it erroneously thinks that everything has worked fine, resulting in a "Connection refused" error because the tests only connect to the simulator using IPv4.
The …
> Fix integration tests erroring with "Connection refused"

- src/tss2-esys/api/Esys_EventSequenceComplete.c
- src/tss2-esys/api/Esys_SequenceComplete.c
- src/tss2-esys/api/Esys_SequenceUpdate.c
- src/tss2-esys/esys_iutil.c
- src/tss2-esys/esys_tr.c
- test/integration/esys-object-changeauth.int.c
esys: Check for NULL auth in iesys_compute_session_value
esys: Fix NULL ptr auth in Esys_TR_SetAuth
esys: handle NULL sequenceHandleNode
test: esys: Add test for Esys_TR_SetAuth with NULL auth
> Fix number of NULL ptr issues in ESYS

- src/tss2-esys/api/Esys_HMAC_Start.c
- src/tss2-esys/api/Esys_HierarchyChangeAuth.c
- src/tss2-esys/api/Esys_NV_ChangeAuth.c
- src/tss2-esys/api/Esys_NV_DefineSpace.c
- test/integration/esys-hierarchychangeauth.int.c
- test/integration/esys-hmacsequencestart.int.c
- test/integration/esys-policy-nv-changeauth.int.c
* In some cases in ESAPI a NULL pointer was dereferenced when NULL was passed
as auth value.
* When a special handling for the auth value is required by ESAPI,
in these cases the size of the stored auth value will be set to zero.
* The integration tests are modified to cover these cases.
> ESYS: Fix passing of NULL pointers for auth values.

- src/tss2-esys/esys_crypto_ossl.c
My ESAPI port of tpm2-tools was causing leaks when using the OpenSSL crypto backend. It took me a while to find that I could use `ASAN_OPTIONS=fast_unwind_on_malloc=0` to print fuller stacktraces and find out where the culprit was:
> =================================================================
> ==21014==ERROR: LeakSanitizer: detected memory leaks
> 
> Direct leak of 72 byte(s) in 1 object(s) allocated from:
>     #0 0x7fc7a27f5848 in __interceptor_malloc (/lib64/libasan.so.5+0xef848)
>     #1 0x7fc7a238cc2c in CRYPTO_zalloc (/lib64/libcrypto.so.1.1+0x186c2c)
>     #2 0x7fc7a237a78a in EVP_PKEY_new (/lib64/libcrypto.so.1.1+0x17478a)
>     #3 0x7fc7a237d4e9 in EVP_PKEY_keygen (/lib64/libcrypto.so.1.1+0x1774e9)
>     #4 0x7fc7a237d64d in EVP_PKEY_new_mac_key …
> Fix leak in ESAPI with OpenSSL crypto backend

- Makefile.am
I just tried building 2.2.0-rc0 with a source tarball generated by `make distcheck`. The build process itself works fine, but `make install` fails with the following errors:
```
/usr/bin/install: cannot stat './doxygen-doc/man/ESYS_TR.3': No such file or directory
/usr/bin/install: cannot stat './doxygen-doc/man/ESYS_TR_defines.3': No such file or directory
...
/usr/bin/install: cannot stat './doxygen-doc/man/Esys_HierarchyControl.3': No such file or directory
make[1]: *** [Makefile:13304: install-man3] Error 1
```
The problem is that `doxygen-doc`, the rule from [`ax_prog_doxygen.m4`](https://www.gnu.org/software/autoconf-archive/ax_prog_doxygen.html) that is [used to generate the documentation](https://github.com/tpm2-software/tpm2-tss/blob/acd54f261ad963bc682bbb7d5cd491cae5f093c7/Makefi …
> build: add doxygen.dox to distribution

- Dockerfile
- INSTALL.md
- Makefile-test.am
- Makefile.am
Following #1246, I had a closer look at the dependency list in [`INSTALL.md`](https://github.com/tpm2-software/tpm2-tss/blob/master/INSTALL.md). I think we should
**Add**
- doxygen, required since #1184.
- Gnulib, required since #1199.
- `ps` executable, required for [`script/int-log-compiler.sh`](https://github.com/tpm2-software/tpm2-tss/blob/3e2c09a38d471ab1f06689422216bbb2305b3657/script/int-log-compiler.sh#L63).
- `tpm_server` executable, required for [`script/int-log-compiler.sh`](https://github.com/tpm2-software/tpm2-tss/blob/3e2c09a38d471ab1f06689422216bbb2305b3657/script/int-log-compiler.sh#L69).
**Move**
- OpenSSL to main requirements because of #1173.
- `ss` executable to integration test suite, it is only needed in [`script/int-log-compiler.sh`](https://github.com/tpm2-software/ …
> doc: update dependencies

- .travis.yml
- Dockerfile
- INSTALL.md
- Makefile.am
Installing aclocal files enables downstream patches to be applied simpler, as
the macros at build machine's /usr/share/aclocal are copied into package m4/
directory.
For example the ax_code_coverage.m4 broke backward compatibility in recent
version, distributing this within package reduce dependencies and makes it
easier to run autoreconf.
Signed-off-by: Alon Bar-Lev <alon.barlev@gmail.com>
> build: install aclocal files

- .gitignore
- .travis.yml
- Makefile.am
- configure.ac
When using this project in combination with the freshly released Autoconf Archive 2019.01.06, the build fails with a "missing separator" error in the makefile. This is because upstream made a [breaking change](http://git.savannah.nongnu.org/cgit/autoconf-archive.git/commit/m4/ax_code_coverage.m4?id=b5a2d69f7a7e0133733673586231b88464a98d58) by removing `@CODE_COVERAGE_RULES@` and replacing it with `include $(top_srcdir)/aminclude_static.am`, see the [documentation](https://www.gnu.org/software/autoconf-archive/ax_code_coverage.html) for reference.
> build: update to ax_code_coverage.m4 version 2019.01.06

- src/tss2-esys/api/Esys_StartAuthSession.c
Addressing #1251.
In error cases an already created session was not flushed. Only Esys_TR_Close was
called which does not flush the session.
> ESYS: Fix leaking of sessions

- .travis.yml
- Dockerfile
- INSTALL.md
- m4/ld-version-script.m4
From the Gnulib website:
> Gnulib takes a different approach. Its components are intended to be shared at the source level, rather than being a library that gets built, installed, and linked against. Thus, there is no distribution tarball; the idea is to copy files from Gnulib into your own source tree.
and thus several distributions (Arch Linux, Clear Linux, openSUSE, etc) don't package it.
Therefore add back `ld-version-script.m4` and update collateral to reflect this.
> Add ld-version-script.m4 back

- src/tss2-sys/sysapi_util.h
Remove the definition of unused struct TPM20_ErrorResponse
> sys: remove TPM20_ErrorResponse

- README.md
- doc/arch.md
This file is only used once in README.md, but it is not
needed as the block diagram is linked directly anyway
and the link in the header only confuses doxygen.
> doc: remove unneeded doc/arch.md file

- src/tss2-mu/tpm2b-types.c
src/tss2-mu/tpm2b-types.c: In function 'Tss2_MU_TPM2B_ECC_POINT_Marshal':
src/tss2-mu/tpm2b-types.c:201:24: error: 'ptr' may be used uninitialized in this function [-Werror=maybe-uninitialized]
*(UINT16 *)ptr = HOST_TO_BE_16(buffer + local_offset - ptr - 2); \
^
src/tss2-mu/tpm2b-types.c:152:12: note: 'ptr' was declared here
UINT8 *ptr; \
Fixes:
- http://autobuild.buildroot.org/results/8d7b6dad6602fe67338abc696bc4752dda8e9717
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> tpm2b-types.c: fix maybe-uninitialized error

- config.h
- src/tss2-esys/esys_iutil.h
- src/tss2-mu/base-types.c
- src/tss2-mu/tpm2b-types.c
- src/tss2-mu/tpma-types.c
- src/tss2-mu/tpml-types.c
- src/tss2-mu/tpms-types.c
- src/tss2-mu/tpmt-types.c
- src/tss2-mu/tpmu-types.c
- src/tss2-sys/sysapi_util.h
- src/tss2-tcti/tcti-common.h
- src/util/log.h
When ac config header was introduced and the C files included
config.h header it created a problem for windows build, where
the config.h file was never generated. To solve this windows
build problem an empty file was added to satisfy the
#include <config.h> on windows.
This created a different problem though. The problem is solely
git related. When configure generates the header with different
configuration values then git status treats this auto-generated
updates as legitimate code changes and "git commit -a ..." will
add the changes to the commit.
It can be worked around locally by
git update-index --assume-unchanged config.h or
git update-index --skip-worktree config.h but there is no good
way to enforce this on remote repo and propagate it to clones.
To avoid that we remove the header …
> build: remove fake config.h

- .travis.yml
Don't need to build and install openssl when gcrypt
crypto backend is used. Also switch to conditional
build to gcrypt to speed up the build in CI.
> travis: don't install openssl when gcrypt is used

- src/tss2-esys/esys_crypto_ossl.c
If OpenSSL was compiled without -Bsymbolic (which some packages patched out), then we had a symbolic naming conflict. Even though the functionality seems to be 100% equivalent. Moved the function in question to internal namespace and made it static.
Fixes: #1273
> ESYS: Fix openssl building

- Makefile.am
- configure.ac
By adding these two autoconf-archive macros we can easily enable
valgrind checks for our unit and integration tests.
If valgrind is installed on the system during configure, a few new make
targets are added automatically
make check-valgrind
make check-valgrind-<toolname>
Normal testflow is not altered by these new targets.
> Add valgrind for integration and unit tests

- test/unit/esys-getpollhandles.c
Esys_GetPollHandles returns callee-allocated handles in *handles which must be freed on exit.
Even if this is only in a test case, we should free it as someone might use it as a reference code.
> Add missing free on handles returned by Esys_GetPollHandles

- src/tss2-esys/esys_crypto_ossl.c
Make sure esys with openSSL uses SW implementation of
RAND_bytes for session salt. Otherwise it can be spoofed
by the TPM connection session compromized.
Fixes: #1274
> esys: force esys to use software version of RAND_bytes

- src/util/log.c
This patch replaces the old implementation of the posix strncasecmp
substitute, with a more straight forward implementation.
This also removes the access to unitialized memory in the old
implementation.
> Reimplement case_insensitive_strncmp

- test/unit/esys-crypto.c
If we do not clean up the 'invalid' contexts valgrind complains about memory leaks - also tests often serve as reference code.
> test: cleanup hmac and hash contexts

- src/tss2-esys/esys_iutil.c
Use the Tss2_Sys_GetEncryptParam() function to get the parameter
to decrypt. Using Tss2_Sys_GetRpBuffer() is not correct as it
returns the buffer even for commands with TPM2_ST_NO_SESSIONS.
> esys: use GetEncryptParam funct to get the param to decrypt

- src/tss2-esys/esys_iutil.c
The enc flag needs to be check earlier, before bailing out on TSS2_SYS_RC_NO_ENCRYPT_PARAM error.
> Session flags

- src/tss2-tcti/tcti-tbs.c
If response_size is NULL the function will dereference a NULL ptr before checking.
> tcti: fix null ptr dereference in tcti_tbs_receive

- .travis.yml
There is no need to upload 12 sets of metrics from a single build.
> Upload coverage metrics for selected builds only

- src/tss2-esys/api/Esys_NV_Extend.c
* After the execution of the NV_Extand command the meta data was not updated.
* This causes an error in the HMAC computation of NV_Read for this object because the NV_WRITTEN flag is not set.
> ESYS: Fix missing update of meta data in Esys_NV_Extend.

- .dockerignore
- .gitignore
- .travis.yml
- Dockerfile
- Makefile-fuzz.am
- Makefile.am
- bootstrap
- configure.ac
- doc/fuzzing.md
- m4/flags.m4
- script/fuzz-log-compiler.sh
- script/gen_fuzz.py
- test/fuzz/main-sapi.cpp
- test/fuzz/tcti/tcti-fuzzing.c
- test/fuzz/tcti/tcti-fuzzing.h
- test/fuzz/tcti/tss2_tcti_fuzzing.h
- test/integration/sapi-context-util.c
- test/integration/sapi-test-options.c
- test/integration/test-options.h
* Removed struct TSS2_SYS_CONTEXT definition from
src/tss2-sys/sysapi_util.h as it caused errors with C++ build.
* travis will build fuzz tests to make sure they don't bit rot if
building with clang.
* Dockerfile uses targets and can build just fuzz tests.
* Added Makefile-fuzz.am and generating Makefile-fuzz-generated.am
which build fuzz tests.
* Added python script gen_fuzz.py which reads include/tss2/tss2_sys.h
and generates a fuzz target for all Prepare and Complete calls.
* Added test/fuzz/main-sapi.cpp which defines a libfuzzer target used to
fuzz SAPI calls.
* Added a TCTI for fuzzing which stores fuzzer generated data which
populates structures used for SAPI Prepare calls or feed to Complete
and subsequently unmarshalled.
* Modified integration sapi context util to enable static …
> tests: Add fuzz testing for libfuzzer and oss fuzz

- test/unit/TPM2B-marshal.c
- test/unit/io.c
Fix memcheckd error on reading unitialized memory during make check-valgrind.
> Tests: Fix valgrind errors

- configure.ac
- src/tss2-sys/api/Tss2_Sys_Create.c
- src/tss2-sys/api/Tss2_Sys_CreatePrimary.c
- src/tss2-sys/api/Tss2_Sys_HMAC.c
- src/tss2-sys/api/Tss2_Sys_HMAC_Start.c
- src/tss2-sys/api/Tss2_Sys_Hash.c
- src/tss2-sys/api/Tss2_Sys_HashSequenceStart.c
- src/tss2-sys/api/Tss2_Sys_Import.c
- src/tss2-sys/api/Tss2_Sys_Load.c
- src/tss2-sys/api/Tss2_Sys_LoadExternal.c
- src/tss2-sys/api/Tss2_Sys_NV_DefineSpace.c
- src/tss2-sys/api/Tss2_Sys_PCR_Allocate.c
- src/tss2-sys/api/Tss2_Sys_PCR_SetAuthPolicy.c
- src/tss2-sys/api/Tss2_Sys_PolicyPCR.c
- src/tss2-sys/api/Tss2_Sys_Quote.c
- src/tss2-sys/api/Tss2_Sys_SetCommandCodeAuditStatus.c
- src/tss2-sys/api/Tss2_Sys_SetPrimaryPolicy.c
- src/tss2-sys/api/Tss2_Sys_StartAuthSession.c
- src/tss2-sys/sysapi_util.c
- src/tss2-sys/sysapi_util.h
Core Infrastructure best practices require usage only strong
cryptographic algorithms. To comply with this requirement we
need to have a way to disable usage of algorithms that are
considered weak. The diable mechanism will validate
the TPM2_PUBLIC template of an object and will not allow
to create or load object which the public template will
contain references to the not allowed algorithms.
Additionally it will validate the nameAlg of inPublic and
NV_PUBLIC, hashAlg of the different signing schemes, and
hashAlg of PCR selection for relevant commands.
Algorithms that will be disabled by this are as follows:
- RSA with key size < 2048 bits
- Symmetric ciphers with key size < 128 bits
- SHA1
The new configure flag is called --disable-weakcrypto
> sys: add mechanism to disable weak crypto

- src/tss2-sys/sysapi_util.h
The "public" is a C++ key word and since the sysapi_utils.h in
included by fuzz/main-sapi.cpp it needs to be renamed.
> sys: rename public to pub in ValidatePublicTemplate declaration

- test/integration/esys-unseal-password-auth.int.c
- test/integration/sapi-entity-util.c
- test/integration/sapi-pcr-extension.int.c
- test/integration/sapi-sys-initialize.int.c
- test/integration/sapi-tpm-properties.int.c
These tests don't test any of the code from the sysapi_util module. The
only use was to get the size of a structure defined there but this is
exposed through the tss2-sys API directly. Inclusion of this header is
largely an artifact of this code having been liberated from the legacy
`tpmclient` test.
> test: Remove use of 'sysapi_util.h' from integration tests.

- src/tss2-esys/api/Esys_Load.c
- src/tss2-esys/api/Esys_LoadExternal.c
Both functions dereference inPublic param in their corresponding
_Finish functions so it needs to be checked if it is not null.
> esys: fix null ptr dereference in Esys_Load and Esys_loadExternal

- test/tpmclient/tpmclient.int.c
Using strlen on an uninitialized character array means the old behavior
of this macro is undefined. "Most compilers" initialize this memory to
'\0' however and the behavior is as if the ErrorHandler function were
passed a character array with length 0. This causes the ErrorHandler to
write no data to the array and no output to be displayed.
The array size is constant and this patch moves its definition to a
macro.
> test: Restore output of Check* macros in tpmclient.

- configure.ac
- doc/fuzzing.md
* The flag -fsanitize=fuzzer-no-link is required per clang's
documentation. However, the link stage -fsanitize=address (and others)
seem to provide the same effect.
* The flag -fsanitize=fuzzer-no-link when combined with building under
Google's OSS-Fuzz with AFL as the fuzzing engine, results in discarded
.text sections, breaking the build during linking.
* Update fuzzing.md doc to reflect recent changes made to configure
> test: fuzz: Remove compile time fuzzing flag

- configure.ac
For features/options enabled by default, the output of “./configure --help” shall state, how to disable them, not how to enable them.
Printing --disable-X implies, that by default feature X is enabled.
Signed-Off-By: Дилян Палаузов <git-dpa@aegee.org>
> configure.ac: tweak output on ./configure --help for features enabled by default

- configure.ac
For AC_ARG_ENABLE/AC_ARG_WITH the default ACTION-IF-FOUND is to set $enable_feature to $enableval.  This does not have to be done explicitly.
After applying this change, the differences between the old and new configure
look so:
```diff
--- /old/configure   2019-03-08 13:06:18.842421251 +0000
+++ /new/configure   2019-03-08 13:29:32.808020085 +0000
@@ -15943,7 +15943,7 @@
if test "${enable_unit+set}" = set; then :
-  enableval=$enable_unit; enable_unit=$enableval
+  enableval=$enable_unit;
else
enable_unit=no
fi
@@…
```
> configure.ac: remove some implicit defaults in AC_ARG_ENABLE

- configure.ac
* use `test =` instead of `test ==`
* mismatched braket
* remove redundant code on AC_ARG_ENABLE
* for features disabled by default, when “./configure --help” prints “--enable-X” don’t state, that by default the feature is disalbed, as this is imlied
> configuce.ac: tweaks

- configure.ac
In all Autoconf projects is expected that:
• calling “./configure” implies passing -O2 -g to the compiler, while
• calling “CFLAGS=–flto ./configure” implies passing -flto to the compiler
but omiting “-O2 -g”.
This patch restores the expected behaviour.
> configure.ac: preserve default behaviour of CFLAGS

- src/tss2-sys/api/Tss2_Sys_GetRspAuths.c
Upcasting in Tss2_Sys_GetRspAuths.c causes memory alignment
errors on some platforms. Therefore, their occurance is
replaced with a more secure implementation using memcpy.
Signed-off-by: Lukas Jäger <lukas.jaeger@sit.fraunhofer.de>
> Fix upcasting issues in Tss2_Sys_GetRspAuths.c

- configure.ac
… so that Makefile is not generated, if ./configure aborts with an error.
> configure.ac: call AC_OUTPUT after all checks

- Makefile-test.am
- src/tss2-esys/esys_iutil.c
- src/tss2-esys/esys_iutil.h
- src/tss2-sys/api/Tss2_Sys_GetEncryptParam.c
- test/integration/esys-session-attributes.int.c
- test/integration/main-esapi.c
This PR includes
- A test that encrypt and decrypt session flags survive the TSS
- A fix for re-enabling encrypt session flags detected by the previous
- A fix for a bug in the response decryption formerly hidden by the previous
in reverse order so that all commits should still build.
This is still using Tss2_Sys_GetEncryptParam() out of sequence. The NO_ENCRYPT_PARAM error merely has precedence over BAD_SEQUENCE. This PR fixes the functionality for now, but we need a proper rework before release.
Relates to: #1316
> 1316 esys session attributes

- src/tss2-esys/esys_crypto_ossl.c
- src/tss2-tcti/tcti-mssim.c
- test/integration/esys-hmacsequencestart.int.c
- test/integration/esys-pcr-auth-value.int.c
and fix unbalanced #ifdef .. #endif
Found by http://www.catb.org/~esr/deheader/ .
> deheader: remove double #include’d headers

- src/tss2-esys/esys_tr.c
* The size of auth value is not checked in Esys_TR_SetAuth, but the size is used for memcpy.
* memcpy caused an out-of-bound overwrite if size > sizeof(TPMU_HA).
> ESYS: Fix usage of bad auth values.

- Makefile-test.am
see https://www.gnu.org/software/automake/manual/html_node/Default-_005fSOURCES.html.
> Makefile-test.am: remove redundant _SOURCES specifications

- configure.ac
- src/tss2-esys/esys_crypto_ossl.c
Instead of attempting to load the non-existent engine "openssl" which
returned NULL we are now using the engine NULL aka default directly.
This removes some side-effects with openssl's s_client to crash when
using the tpm2-tss-engine project.
This change is save to do, since even if tpm2-tss-engine is set as the
default engine, the keys are not tpm2-tss-engine keys. The tpm2-tss-engine
will forward operations to OpenSSL's own software implementation for
such standard key objects.
Also bumping version to 2.3.0-dev so downstream project can require >=2.3.0
Fixes: #1320 
Should be backported to 2.2.X
> Fix OpenSSL issue and bump version

- src/tss2-sys/api/Tss2_Sys_EncryptDecrypt.c
EncryptDecrypt cmd does not allow param encryption because
the first param is not a TPM2B type.
> sys: fix wrong enc flag in EncryptDecrypt

- configure.ac
* print in the summary the default value for tctidefaultmodule, if --with-tctidefaultmodule was not supplied
* replace "x$with_cryptor" → "x$with_crypto"
> Configure: further tweaks

- Makefile-fuzz.am
- Makefile.am
When target_CFLAGS is missing, $(AM_CFLAGS) is used implictly.
> Makefile.am: remove redundant AM_CFLAGS references

- Makefile-test.am
In particular do not compile on simple $(make) `test/helper/tpm_startup`, `test/helper/tpm_transientempty` and `test/integration/libtest_utils.a`.
> Makefile.am: compile test utilities only on “make test”

- Makefile-fuzz.am
- Makefile-test.am
TESTS are the tests, executed by $(make check), and for running $(make check) some further utility programs and libraries need to be compiled, that do not belong to TESTS.  The latter are not supposed to be compiled during $(make all), hence the split.
Makefile-test.am:
* Libraries build during $(make check) are no more called noinst_LTLIBRARIES, but check_LTLIBRARIES.  Add check_LTLIBRARIES to TESTS_LDADD, so that these libraries are considered when linking tests.
*  Remove noinst_LTLIBRARIES from TESTS_LDADD, because its value is libutil.la and the latter is included explicitly.
Follow up of https://github.com/tpm2-software/tpm2-tss/pull/1339.
> Makefile*am: split between TESTS and programs compiled during “make check”

- Makefile.am
From the Automake manual: “Files listed with the ‘_DATA’ primary are not automatically part of the tarball built with ‘make dist’”.
> Makefile.am: remove nodist_ before pkgconfig_DATA

- Makefile-fuzz.am
- script/gen_fuzz.py
Before this change, when `GEN_FUZZ=1 ./bootstrap` has filled Makefile-fuzz-generated.am, the aforementioned files were genetared, and included on “make dist”.
Likewise, test/fuzz/main-sapi.cpp was sometimes considered by “make dist” and test/fuzz/tcti/tss2_tcti_fuzzing.h was always forgotten.
> script/gen_fuzz.py: don’t include test/fuzz/*.fuzz.cpp files on “make dist”

- Makefile-fuzz.am
- Makefile-test.am
- Makefile.am
The sole purpose of mentioning a .h file in Makefile*.am is either:
• for installing and distributing it, being in a _HEADERS primary, or
• only for distributing it, when it is in a _SOURCE primary.
The dependencies between .c and .h files (when a .h file is changed, recompile the .c file and relink) are anyway generated by $CC -M.
> Automake: a .h file needs to be included only once in _SOURCES or _HEADERS for the whole project

- Makefile.am
We don't care how much of our test code gets executed when the test
harness is run. Including this data in our metrics causes the LOC count
to be off by a full 1% while the coverage of functions is over reported
by nearly 10%.
> build: Limit code coverage metrics collection to $(top_builddir)/src.

- Makefile-test.am
- Makefile.am
- configure.ac
* Makefile.am: instead of linking libtss2-esys with -lssl -lcrypto, link with $(LIBCRYPTO_LIBS) $(LIBSSL_LIBS).  Use $(LIBSSL_CFLAGS) and $(LIBCRYPTO_CFLAGS) as CFLAGS for the library.
* Makefile-test.am:
- likewise for the ESYS unit tests.
- N.B.: test/unit/esys_context_null uses $(esyscryLDFLAGS) but not $(esyscryCFLAGS); test/integration/esys_policy_ticket.int uses $(esyscryCFLAGS) but not $(esysLDFLAGS).
* Discontinue linking libtss2-sys.so, libtss2-mu.so, libtss2-tcti-mssim.so and libtss2-tcti-device.so with -lcrypto, but on --with-crypto=gcrypt continue linking them with -lgcrypt.
* configure.ac: When --with-crypto=ossl --enable-esapi --enable-integration is used, don't check a second time for libcrypto.
> configure.ac: check for libcrypto/libssl with PKG_CHECK_MODULES

- .gitignore
- Makefile-test.am
- script/int-log-compiler-ptpm.sh
- script/int-log-compiler.sh
- test/helper/tpm_dumpstate.c
- test/integration/esys-pcr-basic.int.c
Fixes a PCR allocation test.
Also adds some code to detect TPM state changes during tests, such as NV, objects, sessions and theoretically PCR allocations.
PCR allocation changes only take effect after reboot, so they are not really discovered now.
Future TODO: We need to figure out, how to make the tpm-simulator boot before a third call to dumpstate in the script.
Fixes: #1354
> Restore original PCR allocations in test and detect TPM state changes

- Makefile-test.am
- test/integration/sapi-nv-policy-locality.int.c
- test/integration/sapi-nv-readwrite.int.c
- test/tpmclient/tpmclient.int.c
This is some refactoring that I ended up doing while attempting to liberate a different test. Removing the test I was working on caused breakage in these tests so I went ahead and cleaned these up too.
> Tpmclient: refactor NV tests

- Makefile.am
- configure.ac
- lib/tss2-esys.pc.in
- lib/tss2-mu.pc.in
- lib/tss2-sys.pc.in
- lib/tss2-tcti-device.pc.in
- lib/tss2-tcti-mssim.pc.in
- Properly use `AC_CONFIG_FILES` instead of doing manual search-and-replace to generate the pkg-config files.
- Define variables for `libdir` and `includedir` in pkg-config files. This is [standard practice](https://people.freedesktop.org/~dbn/pkg-config-guide.html#using) and allows the user to figure out where the files have been installed, which is e.g. required in [tpm2-tools](https://github.com/tpm2-software/tpm2-tools/pull/1401#discussion_r273539639).
> pkg-config files: use AC_CONFIG_FILES and define variables

- Dockerfile
Fixes environment variable problem (GEN_FUZZ=1) in Dockerfile.
Please backport to 2.2.2.
Signed-off-by: Michael Eckel <michael.eckel@sit.fraunhofer.de>
> Fixed Dockerfile environment in fuzzing section.

- doc/fuzzing.md
As communicated with John Andersen, the line
`export LD_LIBRARY_PATH=/usr/local/bin`
was supposed to be copied from the Dockerfile, but it was not.  In the latter the variable is set to /usr/local/lib and the purpose is likely to find the libtss2-tcti-*.so files.  Summa summarum, the line removed herein does nothing.
> doc/fuzzing.md: relax requirements

- Makefile.am
- configure.ac
This allows configuring the pkg-config directory using
```
./configure --with-pkgconfigdir
```
Also use distclean instead of clean for `.pc` files, since they are generated by `configure` since 8ed533fba7dad438f4e8fcd99f108a75eddfff0f.
> build: use PKG_INSTALLDIR to determine pkgconfigdir

- Makefile-test.am
- src/util/log.c
- src/util/log.h
- test/unit/log.c
This PR makes not exported functions static, removes unused code and adds a simple test for codecoverage.
Signed-off-by: Peter Huewe <peter.huewe@infineon.com>
> Improve logging quality

- src/tss2-esys/esys_iutil.c
Not all TPM implementations allow for nonce sizes to change between
the initial auth session start and subsequent commands, so just
use the original caller nonce-size when generating the next nonce
value.
Bugs were reported to the tpm2-tools:
- https://github.com/tpm2-software/tpm2-tools/issues/1381
> esapi: keep nonce sizes stable

- Makefile-fuzz.am
DISTCLEANFILES is declared in Makefile.am, therefore Makefile-fuzz.am cannot declare it once again, it can only add to it.
Regression introduced in 64b08028dc331a, fixes #1385.
> Makefile-fuzz.am: add to DISTCLEANFILES

- src/tss2-esys/esys_tcti_default.c
The macro is already quoted, so using stringification will lead to a configuration string like `"/dev/tpmrm0"`, including the double quotes. Just use the macro directly instead like `ESYS_TCTI_DEFAULT_MODULE`.
An alternative solution would be to keep the stringification and remove the double quotes from the [definition of `ESYS_TCTI_DEFAULT_MODULE` in `configure.ac`](https://github.com/tpm2-software/tpm2-tss/blob/2f3bff12ad2527668c84a684711b8ae478442adc/configure.ac#L110). However this wouldn't be consistent with the other strings in `config.h` (including the ones automatically defined by Autoconf) which all have quotes.
> esys: don't stringify ESYS_TCTI_DEFAULT_CONFIG

- .travis.yml
Following the discussion in #1348, I suggest removing the separate `make distcheck` in Travis CI and instead replace the `check` by a `distcheck` target for Clang. The reasons are as follows:
- Doing this saves time, since the integration tests don't have to be run twice.
- Possible errors with files missing for specific configuration options are spotted more easily: currently `make distcheck` [only takes into account the value of `WITH_CRYPTO`](https://github.com/tpm2-software/tpm2-tss/blob/9f7cc086e9802d1ed3682e8f5b036bd33dc5aa21/.travis.yml#L127), while `WITH_TCTI_ASYNC` and `WITH_TCTI_PARTIAL` aren't considered.
The reason why we can't replace `check` by `distcheck` for GCC as well is that we want to [test code coverage for GCC](https://github.com/tpm2-software/tpm2-tss/blob/9f7cc086e9 …
> ci: replace check with distcheck for Clang, remove separate distcheck

- src/tss2-esys/tss2-esys.vcxproj
- src/tss2-mu/tss2-mu.vcxproj
- src/tss2-sys/tss2-sys.vcxproj
- src/tss2-tcti/tss2-tcti-mssim.vcxproj
- src/tss2-tcti/tss2-tcti-tbs.vcxproj
The previous configuration was a misguided attempt to get all build
output in a central location. Turns out VS doesn't like this since I
rolled the intermediate output directory into the same location. This
causes a race condition since there's no guarantee that the intermediate
build output (object files) will have unique names.
The right way to resolve this is to just remove the configuration and
use the VS defaults.
> build: Use default OutDir for all VS projects.

- .travis.yml
- tpm2-tss is built first without tests enabled in order to prevent test-specific code from causing errors if disabled (#913). Improve this test to respect `WITH_TCTI_PARTIAL` and `WITH_TCTI_ASYNC` for better configuration options coverage.
- The fuzz target is tested using a [separate build matrix entry](https://github.com/tpm2-software/tpm2-tss/blob/0e778bf959b20d8f38b5c4f440cfd6c6d55c48b7/.travis.yml#L14). This is redundant because it starts a job for both GCC and Clang (and fuzzing can be used only with Clang) and runs the integration tests already included in [another job](https://github.com/tpm2-software/tpm2-tss/blob/0e778bf959b20d8f38b5c4f440cfd6c6d55c48b7/.travis.yml#L13) before doing the fuzz target test. Move this test to a separate job in `matrix.include` instead.
> Improvements to Travis CI jobs configuration

- src/tss2-esys/esys_iutil.c
- test/integration/esys-policy-password.int.c
TPM commands like tpm2_encryptdecrypt can clear the continuesession flag in the
sessionAttributes. However, when it is intended to continue the policy session
inorder to be able to flush the session at a later time in order to:
1. Chain further TPM operations that are intended to modify policy digest
2. Run additional TPM commands using the session with satisfied policy
Signed-off-by: Imran Desai <imran.desai@intel.com>
> esys_iutil.c: Update session attribute in cmdauths structure for policy sessions

- src/tss2-esys/api/Esys_StartAuthSession.c
- test/integration/esys-policy-nv-undefine-special.int.c
* The session name was no added to meta data in StartAuthSession.
* This caused an error in HMAC computation for policy sessions.
> ESYS: Fix computation of session name in Esys_StartAuthSession.

- Makefile-test.am
- Makefile.am
- configure.ac
Linking against `libssl` doesn't appear to be necessary according to `ldd -u -r`, everything builds fine with `libcrypto` alone. This change is related to, but completely independent of #1417 and reduces overlinking.
> build: remove libssl

- Dockerfile
Using the [organisation-wide Dockerfile](https://github.com/tpm2-software/tpm2-software-container) as a base helps avoiding duplicate efforts in keeping the image up to date, see https://github.com/tpm2-software/tpm2-tss/issues/1419#issuecomment-493987654. This change depends on https://github.com/tpm2-software/tpm2-software-container/pull/7 to configure a more recent clang++ for the fuzzing target to work properly.
> Dockerfile: use tpm2software/tpm2-tss as base image

- Makefile-test.am
- Makefile.am
- configure.ac
Split out the backwards-compatible change a89ce2afae195aa58a0579da7d7019a004ff1edd from #1417  in order to prevent it from getting stale. In theory we could also merge 1a7be9bbaaad53ab770b9a5afe2c252e6a1f149f now because it is backwards-compatible as well, but I think I would prefer correcting the pkg-config files in one go.
- `configure.ac`: Introduce `TSS2_ESYS_CFLAGS_CRYPTO` and `TSS2_ESYS_LDFLAGS_CRYPTO` reflecting the chosen ESAPI cryptographic backend.
- `Makefile.am`: Use the newly introduced variables instead of relying on the `ESYS_OSSL`/`ESYS_GCRYPT` conditionals.
- `Makefile-test.am`: following suggestions from @dilyanpalauzov, remove the `esyscryCFLAGS`/`esyscryLDFLAGS`/`esyscrySRC` and replace them with the newly introduced variables. Also fix #1366 (a missing CFLAGS …
> build: use unified TSS2_ESYS_{C,LD}FLAGS_CRYPTO for crypto backend

- Makefile.am
When building from a release tarball having `make clean` delete the
AUTHORS file isn't what the user expects. This file is only generated by
the `dist*` targets and it should only be removed on `maintainer-clean`.
This resolves #1402
> build: Delete AUTHORS file in `maintainer-clean` make target.

- Makefile.am
Apped the map files for SYS and ESYS to LDFLAGS only
if HAVE_LD_VERSION_SCRIPT is true.
> makefile.am: conditionally append map file

- src/tss2-esys/esys_crypto_ossl.c
During pk_encrypt we will generate random values for the key as well as the OAEP padding. We need to ensure that we use a CPU-based random function.
> Esys: Require software random values

- src/tss2-esys/esys_iutil.c
The loop end condition for the hash table loop was wrong (Fixes :#1440).
> Esys: Fix computation of hmac.

- .travis.yml
Much of the CI time is spent on running the integration test suite, which is not CPU bound. This speeds up the CI from about [00:35 real-time/02:15 total](https://travis-ci.org/diabonas/tpm2-tss/builds/544156308) to about [00:25 real-time/01:30 total](https://travis-ci.org/diabonas/tpm2-tss/builds/544133369) (both measured with warm cache).
> ci: don't limit the amount of parallel jobs for make (dist)check

- include/tss2/tss2_tpm2_types.h
The algorithm was added in [revision 1.27 of the TCG Algorithm Registry](https://trustedcomputinggroup.org/wp-content/uploads/TCG-_Algorithm_Registry_Rev_1.27_FinalPublication.pdf). Please advise if there are more places in tpm2-tss where it needs to be added.
Fixes: #1436
> types: add CMAC algorithm

- Makefile-test.am
- src/tss2-esys/esys_iutil.c
- src/tss2-esys/esys_tr.c
- src/tss2-esys/esys_types.h
- test/integration/esys-tr-fromTpmPublic-session.int.c
The getcap command can return a TPM2_HANDLE for the loaded or saved
session however, ESAPI has no way to flush this from the TPM. Modify
Esys_TR_FromTPMPublic() to accept a TPM2_HANDLE representing a session
and create a resource object tagged with IESYSC_SESSION_RSRC.
TODO:
Fixes: https://github.com/tpm2-software/tpm2-tss/issues/1443
> tss2-esys: Support sessions in Esys_TR_FromTPMPublic

- bootstrap
Currently, ./configure will fail with a parameter error if ax_is_release
on the system is outdated. Instead make ./bootstrap fail, with a more
meaningful error message and advice for a download url.
> Build: Add a test for ax_is_release version

- git.mk
The existing rules will only ignore gcda & gcno files in the root
directory. The code coverage macros generate these files in
subdirectories alongside the object files.
> build: Update generated ignore rules to catch code coverage data

- include/tss2/tss2_tcti.h
- src/tss2-esys/esys_tcti_default.c
- src/tss2-tcti/tcti-device.c
This patch is used to add VxWorks support. With this patch, tpm2-tss could work on VxWorks.
> This patch is used to add VxWorks support. 

- test/unit/tctildr-dl.c
This fix moves the definition of the 'HANDLE' constant outside the ifdef
to ensure it's defined for all tests.
This resolves #1462
> test: Fix build breakage from b258ab96

- Makefile-test.am
- Makefile.am
This header will not be shipped in a dist tarball otherwise causing
breakage for dist targets and generated source tarballs.
> build: Add required tctildr headers to libtss2-tctildr _SOURCE.

- src/tss2-tcti/tcti-mssim.c
- test/tpmclient/tpmclient.int.c
* The default value should be 0 instead of 3.
* The integration tests relying on locality 3 (extend pcr 17, pcr event pcr 18) were adapted.
* The locality is reset to 0 at the end of the locality integration test.
> TCTI: Fix the default locality value of tcti-mssim.

- .travis.yml
- INSTALL.md
- Add missing tctildr.h and tctildr-interface.h to distball
- Fix distcheck build in CI (was a false-positive)
- Add doc for Ubuntu
> Fix scanbuild and distcheck

- src/tss2-esys/esys_tr.c
* In Esys_TRSess_SetAttributes a return_if_null checked the
esys_context pointer instead of the esys_object pointer it was meant
to check. This patch fixes this.
Fixes: #1471
> esys: tr: Esys_TRSess_SetAttributes null check fix

- src/tss2-esys/esys_tr.c
* In Esys_TR_FromTPMPublic_Finish esys_handle within esys_context was
accessed prior to a _ESYS_ASSERT_NON_NULL check. This patch fixes this.
Fixes: #1458
> esys: tr: Esys_TR_FromTPMPublic_Finish null check fix

- src/tss2-esys/esys_tr.c
* In Esys_TR_GetName the allocated TPM2B_NAME object is assigned to the
value of the pointer to pointer to TPM2B_NAME. However, the call to
SAFE_FREE passed the pointer to pointer to TPM2B_NAME rather than the
pointer to TPM2B_NAME, as intended. This patch fixes that.
Fixes: #1432
> esys: tr: Esys_TR_GetName SAFE_FREE correction

- lib/tss2-esys.pc.in
- lib/tss2-sys.pc.in
- lib/tss2-tcti-device.pc.in
- lib/tss2-tcti-mssim.pc.in
The pkg-config files should contain the modules required by the respective library according to the [following guidelines](https://people.freedesktop.org/~dbn/pkg-config-guide.html#writing):
> `Requires` and `Requires.private` define other modules needed by the library. It is usually preferred to use the private variant of `Requires` to avoid exposing unnecessary libraries to the program that is linking with your library. If the program will not be using the symbols of the required library, it should not be linking directly to that library. See the discussion of [overlinking](https://wiki.openmandriva.org/en/Overlinking_issues_in_packaging) for a more thorough explanation.
>
> Since `pkg-config` always exposes the link flags of the `Requires` libraries, these modules will become direct …
> pkg-config: sort out dependencies

- configure.ac
- src/tss2-tcti/tctildr-dl.c
When compiling with `CFLAGS='-O2'` and GCC 9.1.0, compilation fails with
```
src/tss2-tcti/tctildr-dl.c: In function ‘get_info_default’:
src/tss2-tcti/tctildr-dl.c:210:12: error: ‘rc’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
210 |     return rc;
|            ^~
cc1: all warnings being treated as errors
```
This is a false positive because if `ESYS_TCTI_DEFAULT_MODULE` is not defined and the (constant) `tctis` array does not have any elements, `info_from_handle` will return `NULL` and `rc` will be initialised, but initialising `rc` with a failure value does not hurt.
Also take the opportunity to add `-O2` to the compilation flags if fortification is enabled, otherwise compilation fails with
```
/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE …
```
> tctildr: initialise rc in get_info_default to avoid compiler warning 

- Makefile-test.am
- Makefile.am
- bootstrap
- configure.ac
- include/tss2/tss2_rc.h
- lib/tss2-rc.def
- lib/tss2-rc.map
- lib/tss2-rc.pc.in
- src/tss2-rc/tss2-rc.vcxproj
- src/tss2-rc/tss2_rc.c
- test/unit/test_tss2_rc.c
- tpm2-tss.sln
This library implements the TCG spec:
-https://trustedcomputinggroup.org/wp-content/uploads/TCG_TSS_RC_v1p0_r12_pub.pdf
This library allows for the conversion of TSS2_RC's from numerical form
to a standardized human readable text string.
Fixes: #1444
> tss2-rc: add TSS2_RC decoding library

- src/tss2-tcti/tctildr-dl.c
If `Esys_Initialize` or `Tss2_TctiLdr_Initialize` attempt to get the default TCTI using [`tctildr_get_default`](https://github.com/tpm2-software/tpm2-tss/blob/d650eda45813424823f57ea0df43544c9995f57e/src/tss2-tcti/tctildr-dl.c#L213), errors of the form
```
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:116:handle_from_name() Failed to load TCTI for name "libtss2-tcti-default.so": libtss2-tcti-libtss2-tcti-default.so.so: cannot open shared object file: No such file or directory
ERROR:tcti:src/tss2-tcti/tctildr-dl.c:116:handle_from_name() Failed to load TCTI for name "libtss2-tcti-tabrmd.so.0": libtss2-tcti-libtss2-tcti-tabrmd.so.0.so: cannot open shared object file: No such file or directory
```
are produced until the correct library is found. This PR downgrades these non-errors to debug messages …
> tctildr: downgrade missing TCTI library error to debug message

- test/integration/esys-clear-control.int.c
- test/integration/esys-clockset.int.c
- test/integration/esys-policy-nv-undefine-special.int.c
* Fixes: #1479
* Some integration tests did use platform hierarchy. These tests did not check
the error code TPM2_RC_HIERARCHY if platform hierarchy is disabled. The check was added.
* The clock set tests did also use platform hierarchy. Here owner hierarchy can be
used.
> ESAPI: Fix tests using platform hierarchy.

- src/tss2-tcti/tctildr.c
Fix two issues found by coverity scan:
** CID 1484591:  Null pointer dereferences  (NULL_RETURNS)
/src/tss2-tcti/tctildr.c: 149 in tctildr_conf_parse()
** CID 1484590:  Memory - illegal accesses  (USE_AFTER_FREE)
/src/tss2-tcti/tctildr.c: 369 in Tss2_TctiLdr_GetInfo()
> tcti: fix issues found by coverity scan

- .travis.yml
- Makefile.am
- configure.ac
- test/unit/tctildr-tcti.c
Add the `enable-asan` configure option to allow building with `-fsanitize=address`.
I also fixed a simple leak in the unit tests detected by `LeakSanitizer`. There were a
few more memory errors that were detected with `enable-asan`, but I'd need a bit
more time to figure out the cause of them.
Comments and critiques are welcomed! :smile:
> Add the enable-asan configure option

- include/tss2/tss2_tpm2_types.h
It seems like these were generated by a scraper tool that goofed up on
these definitions.
Note that this change breaks backwards compatibility with downstream
applications that depended on the misspelled names. Those applications
shouldn't be relying on standard headers providing non-standard
definitions, and tpm2-tss as an implementation of a standard shouldn't
be providing non-standard behavior either.
If applications need to use these definitions and need to build
against an old version of tpm2-tss that lacks the definitions, they
should add their own compatibility macros. For example, see:
https://github.com/tpm2-software/tpm2-tools/pull/1719
Fixes #1500.
Signed-off-by: Matthew Dempsky <matthew@dempsky.org>
> types: fix misspelling of some macros

- .travis.yml
Rather than overriding CC with clang when compiler is gcc, just
exclude it from the build matrix. This will reduce the build
count by one.
Details can be found here:
- https://docs.travis-ci.com/user/build-matrix/
> travis: exclude gcc run with SCANBUILD=yes

- src/tss2-esys/esys_iutil.c
Rather than a byte for byte forloop, use memcmp() so the compiler can
use architectural optimizations.
> esys_iutil: use memcmp in byte array comparison

- sphinx/conf.py
The file is autogenerated from a template and includes these imports for an [option that is commented out](https://github.com/tpm2-software/tpm2-tss/blob/c42450a294c4267998aa16a477e9218ee5953aa9/sphinx/conf.py#L41). Remove the imports to make [LGTM](https://lgtm.com/projects/g/tpm2-software/tpm2-tss/snapshot/359631ab0822728ff1c16b578f1519afc4fa36d1/files/sphinx/conf.py) happy.
> sphinx: remove unused imports from conf.py

- Doxyfile.in
- README.md
The main page of the doxygen documentation index.html is broken both on readthedocs.io and after being built locally.
Changes:
1. adds the architecture image to the doxygen build in `Doxygen.in`
1. moves the *project layout* section into a code block to preserve the newlines
Fixes #1524
> doc: fix doxygen's index.html

- Makefile.am
As suggested in #1525, remove `libtss2-tcti-default.so` from the default installation.
> Revert "build: add install-exec-hook"

- doc/logging.md
- src/tss2-esys/esys_crypto_ossl.c
- src/tss2-tcti/tctildr.c
This are three pretty straightforward issues I wanted to fix:
- if `TSS2_LOG="all+ERROR,tcti+DEBUG" make check`, the test `test/unit/tctildr` will run into a segfault since `LOG_DEBUG()` wants to print an (for test purposes) enormous string. Therefore, `LOG_DEBUG()` needs to be moved further down (after a length check).
- in `esys_crypto_ossl.c`, a wrong key size is chosen for the ECC curve `TPM2_ECC_NISTP224 `.
- in `logging.md`, there is an unterminated inline code block
> Fix a segfault in the tests, a bug with ecc key sizes and a typo

- include/tss2/tss2_rc.h
Without the change, using Tss2_RC_Decode() or Tss2_RC_SetHandler() from
C++ code results in undefined reference error during linkage.
> Add C++ linkage to tss2_rc.h

- doc/doxygen.dox
- include/tss2/tss2_esys.h
- lib/tss2-esys.def
- lib/tss2-esys.map
- src/tss2-esys/esys_context.c
- test/unit/esys-crypto.c
In some cases it can be necessary to call the underlining
sys function before invoking esys function. One example
would be to retrieve cpHash buffer of a command that needs
to be fed to Esys_PolicySigned or Esys_PolicySecret calls.
This can be done by using the Tss2_Sys_GetCpBuffer()
sys call as long as the user can access the sys context.
That's one possible (and simple) solution.
See issue: #1533
> esys: add a new function to retrieve sys context from esys

- m4/misc.m4
If the program name contains characters that are not allowed in a shell variable, defining `result_$1` fails with an error like
```
configure.ac:177: error: AC_SUBST: `result_tpm2-simulator' is not a valid shell variable name
```
Use `AS_TR_SH` to replace all invalid characters with underscores.
> build: allow programs with special characters in ERROR_IF_NO_PROG

- Makefile-test.am
- test/unit/tctildr.c
Optimizations on this unit test cause segmentation faults on s390x.
The problem is only caught on "releases" though because of policy
selected in `configure.ac`.
Ideally after (or something similar) this is merged, it should backport to `2.3.x` branch as well.
> Disable optimizations for tctildr unit test (Fixes: #1547)

- lib/tss2-esys.pc.in
Since commit b258ab9618ded645777917a742b917a3ba72f107 the ESYS library is not linked to any TCTI libraries any more, they are dlopen()'ed if available instead. Removing them from the dependencies also fixes an error when using pkg-config to discover tss2-esys if tpm2-tss was built with `--disable-tcti-mssim`.
Fixes: https://github.com/tpm2-software/tpm2-tools/issues/1851
> pkg-config: remove TCTI loaders from ESYS dependencies

- src/tss2-sys/api/Tss2_Sys_SetCmdAuths.c
`TSS2L_SYS_AUTH_COMMAND.count` is [defined as uint16_t](https://github.com/tpm2-software/tpm2-tss/blob/1c99117f4d102fd465655ed86aca58909a13c10d/include/tss2/tss2_sys.h#L32), so the counter variable should be `uint16_t` as well. This fixes two [LGTM.com alerts](https://lgtm.com/projects/g/tpm2-software/tpm2-tss/snapshot/5c97851f920c69d2f2ebaca5ec52cb8444369751/files/src/tss2-sys/api/Tss2_Sys_SetCmdAuths.c#x262ec6826876f970:1).
> sys: match counter variable type for cmdAuthsArray->count

- Makefile-test.am
- include/tss2/tss2_esys.h
- lib/tss2-esys.def
- lib/tss2-esys.map
- src/tss2-esys/esys_tr.c
- test/integration/esys-tr-getTpmHandle-key.int.c
- test/integration/esys-tr-getTpmHandle-nv.int.c
Add routine Esys_TR_GetTpmHandle() which given an ESYS_TR retrieves the
TPM2_HANDLE which can be used with SAPI or for direct access to
handle values for comparisons or handle masks. Also, add tests.
> ESYS: add Esys_TR_GetTPMHandle

- src/tss2-fapi/fapi_util.c
- src/tss2-fapi/ifapi_keystore.c
- src/tss2-fapi/ifapi_policy_callbacks.c
When compiling with optimisation enabled (`./configure CFLAGS=-O2`), some warnings are generated that make compilation fail due to `-Werror`. Fix these by using the correct array length and avoiding comparison of signed and unsigned integers, resp.
> FAPI: fix compilation with optimisation enabled

- src/tss2-tcti/tctildr-dl.c
- src/util/log.c
tpm2-tss fails to build with gcc 4.8 due to initial declarations in for
loops:
```
src/tss2-tcti/tctildr-dl.c: In function 'get_info_default':
src/tss2-tcti/tctildr-dl.c:185:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (size_t i = 0; i < ARRAY_SIZE(tctis); i++) {
^
src/tss2-tcti/tctildr-dl.c:185:5: note: use option -std=c99 or -std=gnu99 to compile your code
src/tss2-tcti/tctildr-dl.c: In function 'tctildr_get_default':
src/tss2-tcti/tctildr-dl.c:238:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (size_t i = 0; i < ARRAY_SIZE(tctis); i++) {
^
make[3]: *** [Makefile:11004: src/tss2-tcti/tss2_esys_libtss2_esys_la-tctildr-dl.lo] Error 1
make[3]: *** Attente des tâches non terminées....
src/util/log.c: In function 'doLogBlob': …
```
> fix build with gcc 4.8

- Makefile.am
- configure.ac
- lib/tss2-fapi.pc.in
Fix the pkg-config file to include all required dependencies in <code>Requires<em>.private</em></code>, cf. #1417, and improve the linking a bit.
>  FAPI: fix pkg-config file

- dist/tpm-udev.rules
This will allow tpm2-abrmd.service to have `After=dev-tpm0.device` and similar dependencies.
Related tpm2-abrmd change: https://github.com/tpm2-software/tpm2-abrmd/pull/683
> udev: Allow tpm devices to be used as systemd dependencies

- test/tpmclient/tpmclient.int.c
The freshly released version 1563 of [IBM's Software TPM 2.0](https://sourceforge.net/projects/ibmswtpm2/) returns `TPM2_RC_RETRY` on the first invocation of `Tss2_Sys_NV_Write`, causing the test to fail. Repeat the write attempt until we get a non-transient response code.
> test/tpmclient: retry Tss2_Sys_NV_Write upon TPM2_RC_RETRY

- Makefile-test.am
- src/tss2-tcti/tcti-device.c
- test/unit/tcti-device.c
The tctildr library tries to open `/dev/tpmrm0` before `/dev/tpm0` if no tcti was specified. Previously, if the tcti `device` was specified, the tcti-device module would try to open `/dev/tpm0` only.
To streamline the loading behavior, have tcti-device try to open `/dev/tpmrm0` and fallback to `/dev/tpm0`.
Fixes #1564.
> tcti: try to open /dev/tpmrm0 before /dev/tpm0 during tcti-device init

- src/tss2-sys/sysapi_util.h
These functions have been declared as part of the SAPI for years but
were never _defined_ as part of the SAPI, only as part of test code.
The defintions of these functions in the test code were removed as part
of the 2.0 release, so there's no reason to keep their declarations.
See: https://github.com/tpm2-software/tpm2-tss/issues/331#issuecomment-280378592
Signed-off-by: Joe Richey <joerichey@google.com>
> sysapi_util: Remove InitSysContext and TeardownSysContext helpers

- Makefile-test.am
ChangeEPS was listed as optional test, even though it "bricks"TPMs' ability to use EKs.
Moved to destructive.
Should be backported.
> Tests/ESYS: Move ChangeEPS to destructive

- test/integration/fapi-nv-ordinary.int.c
Though there was a test sceletor for testing policy action, this was not triggered, since the wrong policy file was requested. Using the right policy to test policyAction.
> Test/FAPI: Add policy action test

- test/integration/fapi-nv-ordinary.int.c
The check did return true also in cases were the memory was not equal in
the test nv-ordinary.
> FAPI: Fix comparison of memory written and read from NV ram.

- test/unit/TPML-marshal.c
and tpml_digest_values types for null buffer case.
> test: mu: extend tpml marshal tests with tpml_digest

- src/tss2-mu/tpml-types.c
All of the `Tss2_MU_*_Marshal()` functions have the property that
`buffer` can be NULL, `offset` can be NULL, but both cannot be
NULL. Some Marshal functions check this directly (returning
`TSS2_MU_RC_BAD_REFERENCE` on error), but most do this by composing
existing Marshaling functions, and calling them with the same
`buffer`/`offset` arguments as the parent function.
The TMPL Marshal function macro does things differently. It creates a local
VLA `local_buffer[buffer_size]` and uses that as the buffer pointer if
a NULL buffer is given. This is unnecessary, as this pointer is only used:
- for debug logging
- as an argument to other Marshaling functions (which will correctly handle a NULL buffer).
Note that the VLA in the existing code is of length `buffer_size` (the
length of the _entire_ …
> mu: Remove use of VLAs for Marshalling TPML types

- src/tss2-esys/api/Esys_StartAuthSession.c
The ctx->salt is used to calculate session key during
startAuthSession call if the caller pass a valid tpmKey
parameter. There salt is calculated in the _Async call
and the the session key is calculated in the _Finish call.
The problem is that if in the same context an unsalted
session is created after a salted session the ctx->salt
will still hold the old value and it will incorrectly
be used for session key calculation in the the subsequent
_Finish call. To fix this the salt needs to be set to
cleaned after no longer needed.
Fixes: #1574
> esys: zero out ctx->salt after on startAuthSession_finish

- Makefile-test.am
- test/unit/tctildr-nodl.c
> test: Only build mssim-tcti unittest if enabled by config

- configure.ac
Use AM_PATH_LIBGCRYPT instead of AC_CHECK_LIB for checking
libgcrypt, with doesn't add -lgcrypt to the globac $LIBS.
Fixes: #1365
> build: don't link everything against libgcrypt

- src/tss2-tcti/tcti-device.c
One could only disable tcti-async which would disallow ESYS_SetTimeout(0) or not use tcti-async which would lead to indefinite blocking on some platforms.
Instead, we now switch to blocking mode whilst retaining a warning for the user.
This is needed in order to run FAPI on kernels < 5.0 (i.e. without async support)
> TCTI: tcti-device make non-async mode allways block

- Makefile.am
The auto-generaed aminclude_static.am file defines GITIGNOREFILES under
certain conditions and, the same is redefined in Makefile.am,
which triggers a warning when ./bootstrap it executed:
$ ./bootstrap
Generating file lists: src_vars.mk
aminclude_static.am:63: warning: GITIGNOREFILES was already defined in
condition TRUE, which includes condition AUTOCONF_CODE_COVERAGE_2019_01_06
and CODE_COVERAGE_ENABLED ...
Makefile.am:55:   'aminclude_static.am' included from here
Makefile.am:27: ... 'GITIGNOREFILES' previously defined here
Fixes: #1636
> build: remove double definition of GITIGNOREFILES

- src/tss2-fapi/ifapi_io.c
Fixes #1643
After file size computation now fclose is called instead of rewind.
> FAPI: Fix memory leak caused by fopen

- doc/doxygen.dox
- src/tss2-fapi/fapi_crypto.c
- src/tss2-fapi/fapi_util.c
- src/tss2-fapi/ifapi_eventlog.c
- src/tss2-fapi/ifapi_get_intl_cert.c
- src/tss2-fapi/ifapi_helpers.c
- src/tss2-fapi/ifapi_helpers.h
- src/tss2-fapi/ifapi_io.c
- src/tss2-fapi/ifapi_keystore.c
- src/tss2-fapi/ifapi_policy_calculate.c
- src/tss2-fapi/ifapi_policy_callbacks.c
- src/tss2-fapi/ifapi_policy_execute.c
- src/tss2-fapi/ifapi_policy_instantiate.c
- src/tss2-fapi/ifapi_policy_json_deserialize.c
- src/tss2-fapi/ifapi_policy_store.c
- src/tss2-fapi/ifapi_policyutil_execute.c
- src/tss2-fapi/tpm_json_deserialize.c
- src/tss2-fapi/tpm_json_serialize.c
* Functions were declared static if they were used only in one file.
* If necessary, functions were moved to the file where they were used.
* Dead code was removed.
* The doxygen documentation and inline comments were extended.
> Fapi Declare functions static if possible and add doxygen headers.

- src/tss2-fapi/fapi_crypto.c
Just some code that:
- simplifies the OSSL cleanup paths in FAPI
- Diffrentiates OSSL signature verification failure from OSSL errors.
> Fapi simplification

- src/tss2-fapi/ifapi_get_intl_cert.c
Usage of %lu for size_t caused an compliation error on raspian.
> FAPI: Fix wrong format directive.

- Makefile-test.am
- src/tss2-esys/api/Esys_Clear.c
- src/tss2-esys/esys_iutil.c
- test/integration/esys-tpm-clear-auth.int.c
After tpm2_clear command is executed it sets all ownerAuth, endorsementAuth, and lockoutAuth to the Empty Buffer and then this is used for a response auth calculation.
This requires to recalculate the esys session auth value after tpm2_clear is executed or the calculated response HMAC value will be invalid.
Fixes: #1641
> Tpm_clear auth

- dist/fapi-config.json.in
Remove a trailing comma from the last line of the default FAPI config
file, making it valid JSON.
Fixes: #1650
> FAPI: Ensure default config adheres to JSON spec

- include/tss2/tss2_esys.h
- src/tss2-esys/api/Esys_Hash.c
- src/tss2-esys/api/Esys_HierarchyControl.c
- src/tss2-esys/api/Esys_LoadExternal.c
- src/tss2-esys/api/Esys_SequenceComplete.c
- src/tss2-fapi/api/Fapi_ExportKey.c
- src/tss2-fapi/ifapi_policy_execute.c
- test/integration/esys-hash.int.c
- test/integration/esys-hashsequencestart.int.c
- test/integration/esys-hierarchy-control.int.c
- test/integration/esys-hmacsequencestart.int.c
- test/integration/esys-make-credential.int.c
- test/integration/esys-policy-ticket.int.c
- test/unit/esys-resubmissions.c
- test/unit/esys-tcti-rcs.c
- test/unit/esys-tpm-rcs.c
There is a discrepancy between ESYS specification v0.90 rev4 and the
ESYS implementation, where the specification defines hierarchy
as ESYS_TR type and the implementation uses TPMI_RH_HIERARCHY type.
The affected functions include: Esys_Hash(), Esys_HierarchyControl(),
Esys_LoadExternal(), and Esys_SequenceComplete() plus their _Async()
version. This change makes the spec and the implementation consistent.
> esys: change the hierarchy type according to the spec

- Makefile.am
Pull request #1531 broke ABI compatibility to align the library with the ESAPI specification. In addition to increasing the major version to 3 according to semantic versioning, I suggest bumping the soname from (the default) 0 to 1 as well. This signals an ABI-breaking change of the library and allows to collect a list of applications in need of a rebuild for the new tpm2-tss version more easily. Most Linux distributions have tooling to detect such soname version changes and perform the necessary rebuilds automatically, reducing the risk of broken packages.
> build: bump soname of libtss2-esys

- include/tss2/tss2_sys.h
- src/tss2-sys/api/Tss2_Sys_ReadClock.c
In addition to commit 1414f739 Tss2_Sys_ReadClock needs
to be extended with auths arrays.
> sys: add auth arrays to Tss2_Sys_ReadClock

- src/tss2-fapi/ifapi_keystore.c
- src/tss2-fapi/tpm_json_serialize.c
* The return code was not assigned before return code checking.
* A wrong type was used for size checking. 
Fixes #1658 
Fixes #1655
> Fapi fix issues #1655 and #1658 wrong return code and wrong size checking.

- src/tss2-esys/api/Esys_TestParms.c
- src/util/aux_util.h
The TestParams code is used to test paramters against the TPM to
understand if a specific algorithm and scheme is supported. Thus,
certain errors are expected. The expected errors are:
1. From any layer
2. Are Format 1 errors
3. Are P1 or Parameter 1 errors
4 are one of:
- RC_CURVE
- RC_VALUE
- RC_ASSYMETRIC
- RC_KEY_SIZE
Fixes: #1573
> Esys_TestParams: silence expected errors

- Makefile.am
Adapted `Makefile.am` to create 'tss' user and group as well as all FAPI
directories manually as a fallback solution, in case systemd is not available on the
system, such as in Docker (by default).
Signed-off-by: Michael Eckel <michael.eckel@sit.fraunhofer.de>
> Fixes #1611. Adapted Makefile.am to create FAPI folders without systemd.

- test/integration/esys-clockset.int.c
- test/integration/sapi-read-clock.int.c
Use of an authorization session might not be supported by TPMs before revision 1.38
> esys test: Add check whether session can be used by Esys_ReadClock.

- .ci/docker.run
The location of the CI build log is different
for make check and make distcheck, and if the later
fails nothing gets printed.
> ci: don't assume hardcode the location of test-suite.log

- src/tss2-fapi/api/Fapi_CreateNv.c
- src/tss2-fapi/api/Fapi_Provision.c
- src/tss2-fapi/fapi_util.c
- src/tss2-fapi/ifapi_keystore.c
- src/tss2-fapi/ifapi_keystore.h
- test/integration/fapi-nv-set-bits.int.c
* During provisioning and object creation it will be checked whether
the object already exists in key store.
* The test fapi-nv-set-bits which did include provisioning two times was
modified to check whether second provisioning was recognized.
> FAPI: Prevent overwriting ob objects in key store.

- .travis.yml
The location of the CI build log is different
for 'make check' and 'make distcheck', and currently
if the later fails nothing gets printed.
> ci: don't hardcode location of test-suite.log

- include/tss2/tss2_tcti.h
- src/tss2-tcti/tcti-common.c
- src/tss2-tcti/tcti-device.c
- src/tss2-tcti/tcti-mssim.c
- src/tss2-tcti/tcti-swtpm.c
- src/tss2-tcti/tcti-tbs.c
- src/tss2-tcti/tctildr.c
- test/unit/tcti-swtpm.c
- test/unit/tctildr-tcti.c
Return codes from macros in TCTI header are not
compliant with the spec. If context is NULL
TSS2_TCTI_RC_BAD_REFERENCE should be returned instead of
TSS2_TCTI_RC_BAD_CONTEX. TSS2_TCTI_RC_BAD_CONTEX is for
bad version and/or wrong magic field in the context.
Fixes: #1431
> tcti: fix return codes from tcti macros

- configure.ac
It is valid configuration so no need to warn the user.
Just use AC_MSG_NOTICE instead.
> build: relax notification method about fallback to mssim

- Makefile.am
- configure.ac
PKG_CHECK_MODULES needs to be wrapped inside squere
brackets when inside AS_IF, or it spit out errors:
./configure: line 13054: JSONC_CFLAGS: command not found
./configure: line 13055: C: command not found
./configure: line 13056: JSONC_LIBS: command not found
./configure: line 13155: CURL_CFLAGS: command not found
./configure: line 13156: CURL_LIBS: command not found
> configure.ac: wrap PKG_CHECK_MODULES in braces

- src/tss2-tcti/tcti-common.c
- src/tss2-tcti/tcti-common.h
- src/tss2-tcti/tcti-device.c
- src/tss2-tcti/tcti-mssim.c
- src/tss2-tcti/tcti-swtpm.c
- src/tss2-tcti/tcti-tbs.c
- test/fuzz/tcti/tcti-fuzzing.c
- test/tpmclient/tpmclient.int.c
The commit bc70b83 changed TCTIs to return TSS2_TCTI_RC_BAD_REFERENCE
instead of TSS2_TCTI_RC_BAD_CONTEXT when the ctx was NULL, to make it
spec compliant. After that another problem was found, where the
tcti cast functions still didn't handle it correctly.
The problem was that if the magic number was wrong a NULL was returned,
which caused the common_checks function to return wrong return code.
This PR changes the casts function to overwrite the magic to a known
bad value and common_check function to check for the expected magic
explicitly passed by each tcti type and return TSS2_TCTI_RC_BAD_CONTEXT
with compliance with the specification.
> tcti: fix invalid error code in case of wrong magic

- script/ekca/create_ca.sh
- script/fint-log-compiler.sh
The certificate generation is only needed for simulator tests but not for device tests.
> CI: Fix int-log-compiler script for FAPI.

- src/tss2-fapi/api/Fapi_Provision.c
For TPMs without stored certificate and without an implementation
of a special handling in TSS  now TSS2_FAPI_RC_NO_CERT instead of
TSS2_RC_SUCCESS will be returned.
This PR should be merged after PR 1969 for the tpm-tools has been merged, because otherwise the
tpm-tool integration tests would fail with the current tss master branch.
> FAPI: Fix certificate handling for TPMs without stored certificate.
