tpm2-software/tpm2-tss

test/unit/fapi-json.c

* Several deserialization error cases were checked.
* Tests for deserialization of bit masks were extended.

FAPI TEST: Extend unit tests.

---

src/tss2-esys/esys_crypto_ossl.c
src/tss2-fapi/fapi_crypto.c

ECC Functions with suffix GFp will become deprecated (DEPRECATED_1_2_0).

ESYS: Fix deprecated OpenSSL functions.

---

doc/doxygen.dox
src/tss2-fapi/fapi_crypto.c

* Some FAPI functions which were removed from code are also removed from doxygen file.
* A duplicate doxygen return value declaration was removed.

doxygen: Fix doxygen warnings.

---

src/tss2-esys/esys_context.c

An unintended free of the tcti parameter in cleanup was possible.

ESYS: Fix initialization of app data in Esys_Initialize (Fixes #1704).

---

src/tss2-fapi/api/Fapi_ExportKey.c

The async call to create sessions can be removed. The call is executed
in the function ifapi_load_key used by Fapi_ExportKey.

FAPI: Remove unecassary code from Fapi_ExportKey

---

src/tss2-fapi/api/Fapi_Import.c

The access to the context of Key_Create was replaces with access to the default profile.

FAPI: Fix wrong access to context of the command Key_Create.

---

src/tss2-sys/api/Tss2_Sys_CertifyCreation.c

No need to assign to rval since we are returning here.
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>

sys: Minor static analysis cleanup in Tss2_Sys_CertifyCreation_Complete

---

include/tss2/tss2_fapi.h
src/tss2-fapi/api/fapi_callback.c
src/tss2-fapi/fapi_int.h
src/tss2-fapi/fapi_util.c
src/tss2-fapi/fapi_util.h
src/tss2-fapi/ifapi_json_deserialize.c
src/tss2-fapi/ifapi_keystore.c
src/tss2-fapi/ifapi_keystore.h
src/tss2-fapi/ifapi_policy_callbacks.c
src/tss2-fapi/ifapi_policy_callbacks.h
src/tss2-fapi/ifapi_policy_execute.c
src/tss2-fapi/ifapi_policy_execute.h
src/tss2-fapi/ifapi_policyutil_execute.c
test/integration/fapi-data-crypt.int.c
test/integration/fapi-get-esys-blobs.int.c
test/integration/fapi-key-change-auth.int.c
test/integration/fapi-key-create-ckda-sign.int.c
test/integration/fapi-key-create-policies-sign.int.c
test/integration/fapi-key-create-policy-authorize-sign.int.c
test/integration/fapi-key-create-policy-or-sign.int.c
test/integration/fapi-key-create-policy-secret-nv-sign.int.c
test/integration/fapi-key-create-policy-signed.int.c
test/integration/fapi-key-create-sign-password-provision.int.c
test/integration/fapi-key-create-sign-policy-provision.int.c
test/integration/fapi-key-create-sign.int.c
test/integration/fapi-nv-extend.int.c
test/integration/fapi-nv-increment.int.c
test/integration/fapi-nv-ordinary.int.c
test/integration/fapi-nv-set-bits.int.c

* For callbacks instead of the FAPI context the object path of the object to be authorized will be  passed and callback parameters which should not be changed are declared const.
* The integration tests were adapted.

Fapi change callback API

---

Makefile.am

Bump soname due to commit e0636dd6fbec4f286cc908117ecef4d820a50f79 breaking the API and ABI of Fapi_CB_{Auth,Sign,Branch,PolicyAction}

FAPI: bump so-version

---

.cirrus.yml

Looks like the current tree is not stable.

cirrus: drop freebsd-13-CURRENT image

---

Makefile-test.am

Remove FAPI_LDFLAGS from Makefile-test.am alltogether. Instead use TESTS_LDADD to carry the JSONC_LIBS parameter to compilation units.
Fixes: #1725

Build: Fix warning on FAPI_LDFLAGS

---

Makefile.am

systemd-sysusers/-tmpfiles needs to be executed in `install-data-hook` instead of `install-exec-hook`, otherwise the configuration files `sysusers/tmpfiles_DATA` are not installed yet.
Automake only allows a single hook of each type, and there is already one for prepending the udev rules file with a prefix, so these hooks need to be consolidated: if `WITH_UDEVRULESPREFIX` is false, `udevrulesprefix` is empty, so the `mv` operation fails since source and target are the same file. Ignore this error since it is harmless.
Also consolidate `uninstall-hook` into `uninstall-local` for simplicity.
Fixes: 7502887b57246923fa965bfc56b5eddb473d613d

build: fix systemd-sysusers/-tmpfiles invocation

---

Makefile-test.am
lib/tss2-esys.pc.in

Due to an unfortunate merge overlap between #1457 and #1417, static linking of libtss2-esys
is currently broken because the pkg-config file contains a literal, unexpanded `@LIBDL_LDFLAGS@`. The new name coming from the `LT_LIB_DLLOAD` Autoconf macro is `LIBADD_DL`.
Also remove the now empty `LIBADD_DL` from `Makefile-test.am` so that nothing in the codebase depends on the old name any more.

dist/tss2-esys.pc.in: replace broken @LIBDL_LDFLAGS@ by @LIBADD_DL@

---

Makefile-test.am
src/tss2-fapi/api/Fapi_ChangeAuth.c
src/tss2-fapi/api/Fapi_CreateKey.c
src/tss2-fapi/api/Fapi_CreateNv.c
src/tss2-fapi/api/Fapi_GetInfo.c
src/tss2-fapi/api/Fapi_Import.c
src/tss2-fapi/api/Fapi_Provision.c
src/tss2-fapi/fapi_int.h
src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_config.c
src/tss2-fapi/ifapi_helpers.c
src/tss2-fapi/ifapi_helpers.h
src/tss2-fapi/ifapi_json_serialize.c
src/tss2-fapi/ifapi_json_serialize.h
src/tss2-fapi/ifapi_keystore.c
test/integration/fapi-check-wrong-paths.int.c

* Several FAPI fixes which also should be back ported to 2.4.x
* Fix handle usage in Fapi_ChangeAuth.
* Fix setting of default flags for key creation.
* Fix path usage in Fapi_Import.
* Fix get version with Fapi_GetInfo.
*  Fix path checking for keys.
* Fix NV index and path handling in NV creation.
* Add content of the config file to FAPI Info.

Fapi backport fixes

---

test/unit/fapi-json.c
test/unit/tcti-swtpm.c

* Two leaks in  in swtpm unit test were fixed.
* Several leaks if the fapi json unit test were fixed.

Fix memory leaks in unit tests

---

script/int-log-compiler-common.sh

Split sock tool and params into two separate vars in
int-log-compiler-common.sh to be able to test for the
tool presence with 'which' tool.

ci: split sock_tool and its params into two vars

---

Makefile-test.am
src/tss2-fapi/api/Fapi_Decrypt.c
src/tss2-fapi/api/Fapi_Encrypt.c
src/tss2-fapi/api/Fapi_GetEsysBlob.c
src/tss2-fapi/api/Fapi_Import.c
src/tss2-fapi/api/Fapi_Provision.c
src/tss2-fapi/api/Fapi_SetAppData.c
src/tss2-fapi/api/Fapi_SetCertificate.c
src/tss2-fapi/api/Fapi_SetDescription.c
src/tss2-fapi/api/Fapi_Unseal.c
src/tss2-fapi/fapi_int.h
src/tss2-fapi/fapi_util.c
test/integration/fapi-data-crypt.int.c
test/integration/fapi-key-create-sign.int.c
test/integration/fapi-unseal.int.c

FAPI: Fix usage of persistent handles.
* Persistent handles could not be defined for Fapi_CreateKey. The persistent handle
now can be passed with the key flags and EvictControl is executed for the persistent key.
* The cleanup for keys had to be adapted.
* Tests for derived persistent keys were added,

Fix fapi persistent keys

---

src/tss2-mu/base-types.c
src/tss2-mu/tpm2b-types.c
src/tss2-mu/tpma-types.c
src/tss2-mu/tpml-types.c
src/tss2-mu/tpmu-types.c

This is used to offset discovery and no warning needs
to be printed. Changed both marshal and unmarshal paths.
Fixes #1739

mu: change warnings to debug in case of insufficient buffer

---

src/tss2-fapi/api/Fapi_List.c
src/tss2-fapi/api/Fapi_Provision.c
src/tss2-fapi/fapi_int.h
src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_io.c
src/tss2-fapi/ifapi_io.h
src/tss2-fapi/ifapi_keystore.c
src/tss2-fapi/ifapi_policy_store.c

* Some checks were added to get more understandable messages during provisioning.
* Directories which are created during installation or by Fapi_Initialize will
not be deleted by Fapi_Delete.

Fapi verify state of provisioning

---

src/tss2-fapi/api/Fapi_Delete.c
src/tss2-fapi/api/Fapi_Provision.c
src/tss2-fapi/fapi_util.c

* A wrong execution of making a copy of the primary object during key loading was fixed.
* The selection of the hierarchy was added for EvictControl in Fapi_Delete.
* Some wrong format directives in Fapi_Provision were fixed.

Fix fapi load primary and hiearchy selection for Fapi_Delete

---

configure.ac

Previously, when running ./configure in the source directory of tpm2-tss in a system without doxygen installed a building error occurred stopping the installation completely. Doxygen is not required for tpm2-tss to work so it should continue building by default.
The changes were made to mantain the uses of --disable-doxygen-doc and --enable-doxygen-doc parameters coherent to the documentation (By default if the user does not use any parameters and doxygen is installed on the system, documentation will be generated, if not installed, the building continues without generated documentation).

Building now continues correctly if the "$enable_doxygen_doc" flag is not set. Fixed #1329

---

test/integration/fapi-check-wrong-paths.int.c

The success return code for wrong paths was not checked correctly in all cases.

FAPI: Fix the success check in integration test check wrong paths

---

src/tss2-fapi/api/Fapi_GetEsysBlob.c
src/tss2-fapi/fapi_int.h

The call was splitted into an async and finish call. The state machine was extended
by a new state.

FAPI: Fix non async call of Esys_ContextSave in Fapi_GetEsysBlobs.

---

dist/fapi-profiles/P_ECCP256SHA256.json
dist/fapi-profiles/P_RSA2048SHA256.json
src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_profiles.c
src/tss2-fapi/ifapi_profiles.h
test/data/fapi/P_ECC.json
test/data/fapi/P_RSA.json
test/data/fapi/P_RSA256.json
test/data/fapi/P_RSA_EK_persistent.json
test/data/fapi/P_RSA_sh_policy.json
test/integration/fapi-key-create-sign.int.c

* Now it's possible to define a description for the EK and the SRK int the profile.
The description will be added to the key object.
* Getting the description of an EK and SRK was added to an integration test.

FAPI: Add description for primary keys to profile.

---

Makefile.am

Force overwrite udevrules in case they already exist.
Fixes: #1763

build: force install udev rule files

---

.ci/docker.run
.ci/travis.run
configure.ac
test/integration/esys-ecc-parameters.int.c
test/integration/esys-get-capability.int.c

This commit adds the address sanitizer to the build CI. 
- In order to run the address sanitizer, the capability SYS_PTRACE needs to be passed to Docker.
- The address sanitizer found leaks in 2 esys integration tests that are fixed with this PR.
Signed-off-by: Christian Plappert <christian.plappert@sit.fraunhofer.de>

Add address sanitizer to CI

---

.travis.yml
Makefile.am
bootstrap
configure.ac
src/tss2-esys/esys_crypto.h
src/tss2-esys/esys_crypto_mbed.c
src/tss2-esys/esys_crypto_mbed.h

I've been working on adding TPM 2.0 support to [Zephyr](http://github.com/zephyrproject-rtos/zephyr). Since Zephyr's primary TLS stack is based on a fork of [mbedtls](https://github.com/zephyrproject-rtos/mbedtls), I've chosen to add mbedtlse's crypto-backend to tpm2-tss. The current code lacks `iesys_cryptmbed_get_ecdh_point` but pass all unit tests not using ECDH.
I've noticed that you are considering (#1676) to drop support for all crypto backends except OpenSSL. My current work does not require ECDH support. Nevertheless, if there is interest to include mbedtls support in tpm2-tss willing to fill that gap.

Support mbedtls as crypto-backend

---

doc/fapi-config.md
man/fapi-config.5.in
src/tss2-fapi/api/Fapi_Initialize.c

* A missing retry check in Fapi_Initialize_Finish was added (Fixes #1782).
* The man page fapi-config was updated.

Fapi Fix missing retry check and update man page (Fixes #1782)

---

Makefile.am

Issue a warning during install-data-hook if the FAPI keystore and eventlog directories could not be created.

Build: Issue warning on FAPI directory creation

---

src/tss2-fapi/ifapi_policy_store.c

Coverity is complaining about identical code for different
branches. Doesn't actually have any functional difference,
but looks weird. Fixing by changing the true branch.

fapi: fix static analysis issue - identical branches

---

include/tss2/tss2_esys.h
src/tss2-esys/api/Esys_Hash.c
src/tss2-esys/api/Esys_HierarchyControl.c
src/tss2-esys/api/Esys_LoadExternal.c
src/tss2-esys/api/Esys_SequenceComplete.c
src/tss2-esys/esys_iutil.c
src/tss2-esys/esys_iutil.h
test/integration/esys-hash.int.c
test/integration/esys-hashsequencestart.int.c
test/integration/esys-hierarchy-control.int.c
test/integration/esys-make-credential.int.c
test/unit/esys-dummy-defs.h

Since:
- 9d48cc7 esys: change the hierarchy type according to the spec
The interface types changed from TPMI_RH_HIERARCHY and TPMI_RH_ENABLES
to ESYS_TR, which from the ABI perspective nothing changed, asthey are
still just UINT32. However, ESYS_TR's do not equal the older TPM2_RH
values they replaced. However, their is no overlap, so we can detect
when a non ESYS_TR hiearchy value is passed and accept it. However, we
want to be noisy about it and the resulting logs will result:
ERROR:esys:src/tss2-esys/esys_iutil.c:389:iesys_handle_to_tpm_handle() Error: Esys invalid ESAPI handle (40000001).
WARNING:esys:src/tss2-esys/esys_iutil.c:411:iesys_is_platform_handle() Convert handle from TPM2_RH to ESYS_TR, got: 0x40000001
This will allow users/distro's to easily upgrade packages without having …

esys: make hiearchy API value change backwards compat

---

CHANGELOG.md

The change from TPM2_RH constants is an API break, not an ABI break. The
function paramters remain exactly the same, a uint32_t, passed as the
same argument to the function.

CHANGELOG: change ABI to API for the TPM2_RH_ change

---

src/tss2-fapi/api/Fapi_AuthorizePolicy.c
src/tss2-fapi/api/Fapi_Import.c
src/tss2-fapi/api/Fapi_Quote.c
src/tss2-fapi/api/Fapi_VerifyQuote.c
src/tss2-fapi/ifapi_json_serialize.c

This commit fixes some leaks on the error paths in FAPI.
Separate PR for 2.4.x coming.

FAPI: Fix memory leaks on error paths

---

Makefile.am

PR #1796 makes libtss2-esys ABI compatible with tpm2-tss 2.4, so applications using this library don't need to be recompiled right away, hence no need for a soname version bump. Since no version with the bumped soname has been released, we can just revert it.
This reverts commit c94a14e65cd482cb9b3767a49535976cfd66a687.

Revert "build: bump soname of libtss2-esys"

---

dist/fapi-config.json.in
src/tss2-fapi/api/Fapi_Provision.c

Switch the default profile of FAPI to be ECC instead of RSA and provide a good error message if no ECC EK cert was found.
Fixes: #1784

FAPI: Switch default profile to ECC

---

lib/tss2-esys.pc.in
lib/tss2-fapi.pc.in
lib/tss2-mu.pc.in
lib/tss2-rc.pc.in
lib/tss2-sys.pc.in
lib/tss2-tcti-cmd.pc.in
lib/tss2-tcti-device.pc.in
lib/tss2-tcti-mssim.pc.in
lib/tss2-tcti-swtpm.pc.in
lib/tss2-tctildr.pc.in

Fall all PC files do:
Currently, software building against the various libraries all include
the header files via a suffix directory. However, moving from spec
compliant SAPI implementations should just require a reconfiguration of
the software build parameters, not of the software itself.
Client's could perform their own magic to do this. Some examples I have
seen are to use a macro to define at buildtime where to pull in the
header file. However, since the specifications define the file name, a
include directive of that file name should be sufficient.
For this reason, place the tss2, or suffic directory, on the build
include path returned by pkg-config, so compliant SAPI stacks can be
easily swapped via normal pkg-config semantics. Thus, removing
additional burdens on client …

all/pkg-config: add root dir to CFLAGS

---

Makefile.am

Use install -C to install the udev files.
This will take care of a situation when the install
is trying to overwrite an existing installation and the files are the same.
Fixes: #1763

build: change install-hook to mv udev file only if prefix not empty

---

src/tss2-fapi/ifapi_eventlog.c

If an log string with invalid json is passed to Fapi_Extend fapi_object_put is
called twice. Depending on the version of lib-json-c this causes an error.

FAPI: Remove duplicate json_object_put in event log processing.

---

Makefile.am
dist/tmpfiles.d/tpm2-tss-fapi.conf.in

Files in the system keystore should be modifiable by any user in the `tss` group, not only by the user that created them. Apply the setgid bit to the keystore directory to make sure that all directories and files under the keystore directory (recursively) are owned by the `tss` group.
This change will be applied to existing keystore directories as well, so newly created files will be owned by the `tss` group from now on. Modifying the owner of already existing files is out of scope for this PR.
Using setgid makes sure that all newly created directories and files in the system keystore are owned by the `tss` group. However, permissions for new files are controlled by the current umask, which might not grant write access to the group. To solve this, set a default ACL for the system keystore …

FAPI: use setgid for system keystore

---

Makefile-test.am
Makefile.am
configure.ac
include/tss2/tss2_tcti_pcap.h
lib/tss2-tcti-pcap.def
lib/tss2-tcti-pcap.map
lib/tss2-tcti-pcap.pc.in
man/tss2-tcti-pcap.7.in
src/tss2-tcti/tcti-pcap-builder.c
src/tss2-tcti/tcti-pcap-builder.h
src/tss2-tcti/tcti-pcap.c
src/tss2-tcti/tcti-pcap.h
test/unit/tcti-pcap.c

Although wireshark features a [neat TPM traffic dissector](https://www.wireshark.org/lists/wireshark-commits/201804/msg00451.html), there is no way to log+parse non-simulator TPM traffic. Additionally, to my knowledge, there is no alternative TPM traffic parser for Linux.
Add a TCTI module which prints TPM traffic to a file `tpm2_log.pcap` in **pcap-ng** format. Via the env. variable`TCTI_PCAP_FILE`, the output can be redirected to another path/stream (`stdout`, `-`, and `stderr` are valid values). If `tpm2_log.pcap` already exists, the logs are appended.
```
+-----------+     +-----------+
SAPI ==>  | tcti-pcap | ==> | tcti-...  | ==> ...
+-----------+     +-----------+
||
\/
tpm2_log.pcap
```
To use this TCTI, just prepend the TCTI name:conf string with "pcap", e.g.
``` …
```

tcti: add pcap tcti

---

.ci/docker.run

A missing space meant that the mssim test run was [never executed](https://travis-ci.org/github/tpm2-software/tpm2-tss/jobs/715021461#L948):
```
/workspace/tpm2-tss/.ci/docker.run: line 77: [: missing `]'
```

ci: fix mssim-tcti build on travis

---

src/tss2-tcti/tcti-mssim.c
src/util/io.c
src/util/io.h

After mssim async change has been merged the FAPI integration
tests started to fail randomly on mssim. It looks like the
default timeout value for the poll that FAPI usese is zero,
which causes the return immediately if the response isn't ready, which
causes random hangs in the FAPI integ tests. The change also caused
appveyor CI build to fail. This also fixes the build for now,
by not enabling NONBLOCK on windows.
The way to do this would be to call ioctlsocket(*sock, FIONBIO);
in the socket_set_nonblock function.

tcti: fix random fapi integ test hang after mssim async change

---

configure.ac
test/integration/esys-certifyX509.int.c

Currently the `esys-certifyX509 integration` test enables `TPMA_OBJECT_X509SIGN`, which only works with the mssim TCTI at the moment, [depending on the existence of the `TCTI_MSSIM` macro](https://github.com/tpm2-software/tpm2-tss/blob/1361aa370994eea08b446f1de975f918f9574e8c/test/integration/esys-certifyX509.int.c#L82-L87). This macro is defined [if the mssim TCTI is enabled](https://github.com/tpm2-software/tpm2-tss/blob/1361aa370994eea08b446f1de975f918f9574e8c/configure.ac#L185-L191), i.e. if `libtss2-tcti-mssim` is built. This excludes that valid use case that the user wants to have the mssim TCTI enabled (e.g. for compatibility with other tpm2-software test suites), but also has swtpm available for running the tpm2-tss integration test suite with `libtss2-tcti-swtpm`. Introduce a new …

test/esys-certifyX509: use TPMA_OBJECT_X509SIGN depending on integration_tcti

---

src/tss2-tcti/tcti-pcap-builder.c
test/unit/tcti-pcap.c

On most 32-bit platforms, the unix epoch is stored in a 32-bit `long` (instead of a 64-bit `long`) which causes overflows in the pcap
builder and the test code. Add casts to account for 32-bit `longs`. For the test code: use a more realistic timestamp which is  small enough for a 32 bit `__time_t`.
Fixes #1826

tcti: fix pcap timestamp for 32-bit platforms

---

.cirrus.yml

Cirrus-ci does distcheck under /tmp/cirrus-ci-build/...
Dump the test-suit.log from there instead of current working dir.

CI: Dump log on cirrus-ci failures

---

src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_policyutil_execute.c

For successful execution policy sessions are closed automatically. In error cases the policy
sessions have to be flushed in the cleanup function.

FAPI: Fix cleanup of policy sessions in error case.

---

src/tss2-fapi/ifapi_policy_store.c

It was not checked whether the pathname for imported policies, which will be
used for the policy store, did contain invalid characters.

FAPI: Fix missing check of pathname used for imported policies.

---

Makefile-test.am
test/unit/tctildr-dl.c

No need to wrap dlerrors call.
Fixes: #1808

dlerror fix

---

src/tss2-fapi/api/Fapi_ChangeAuth.c
src/tss2-fapi/api/Fapi_Provision.c
src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_keystore.c
src/tss2-fapi/ifapi_keystore.h
src/tss2-fapi/ifapi_policy_execute.c
src/tss2-fapi/ifapi_policy_instantiate.c
src/tss2-fapi/ifapi_policy_store.c
src/tss2-fapi/ifapi_policyutil_execute.c

* Policy execution was fixed.
* Pathname check was added for policy files.
* New provisioning after deleting /HS was enabled.
* A missing return code check for ChangeAuth was added.

2.4.x fapi several fixes

---

src/tss2-tcti/tcti-pcap-builder.c
src/tss2-tcti/tcti-pcap-builder.h
test/unit/tcti-pcap.c

When multiple instances of tcti-pcap are writing to the same file at the same time collisions can appear. Fix the following three issues:
* The random host is seeded by the unix epoch in seconds. If multiple threads start roughly at the same time, their packages are associated with the same connection. Move to nanoseconds.
* A random port between 50k and 60k is prone to collisions. Instead use a fixed port and randomize both IP addresses.
* Wireshark sometimes seems to choke on the sequence and acknowledgement number not being implemented properly. Randomize their initial values and implement the acknowledge number properly.

tcti: fix collisions with multi-threading

---

src/util/io.c

Don't need to remap the AGAIN to TPM2 AGAIN since
we implement all retry logic araound the poll() calls.
All the error cases from the socket_recv_buf()
translate to TSS2_TCTI_RC_IO_ERROR in both mssim_tcti
and swtpm_tcti. These two are the only users of the
socket_recv_buf() function.
Fixes #1842

io.c: don't remap AGAIN to TSS2_TCTI_RC_TRY_AGAIN

---

.ci/docker.run

It appears the ref isn't available on checkouts, so fetch the full ref
when doing git diff --check
Clone command:
1.21s$ git clone --depth=50 https://github.com/tpm2-software/tpm2-tss.git tpm2-software/tpm2-tss
Cloning into 'tpm2-software/tpm2-tss'...
$ cd tpm2-software/tpm2-tss
3.11s$ git fetch origin +refs/pull/1706/merge:
From https://github.com/tpm2-software/tpm2-tss
* branch              refs/pull/1706/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
Fixes:
fatal: ambiguous argument 'origin/2.4.x': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
The command "./.ci/travis.run" exited with 128.

ci: fix not having branch ref in git diff --check

---

src/tss2-fapi/api/Fapi_CreateNv.c

An NV index defined by the user in the type parameter of Fapi_NvCreate was ignored.
The user defined index now will be used if the index is in valid range.

FAPI: Fix usage of user defined NV index (Fixes #1847).

---

doc/fapi-config.md
man/fapi-config.5.in

The property ek_cert_less was documented as ek_certless.

FAPI: Wrong property in doc (fixes #1851)

---

include/tss2/tss2_tctildr.h

tss2-tcti: add missing C++ compatibility in tss2_tctildr.h

---

src/tss2-fapi/ifapi_json_deserialize.c
src/tss2-fapi/ifapi_json_deserialize.h
src/tss2-fapi/ifapi_policy_json_deserialize.c
src/tss2-fapi/tpm_json_deserialize.c

* If mandatory fields are not found an error message with the field name
will be displayed instead of "BAD VALUE"
* If a field value  cannot be deserialized now here also the field name will
be part of the error message.

 FAPI: Improve error message for JSON deserialization.

---

src/tss2-fapi/ifapi_helpers.c
src/tss2-fapi/ifapi_helpers.h
src/tss2-fapi/ifapi_json_deserialize.c
src/tss2-fapi/ifapi_policy_json_deserialize.c
src/tss2-fapi/tpm_json_deserialize.c
src/util/aux_util.h
test/unit/fapi-json.c

For JSON objects of type "json_type_object" during desearialization it will be
checked whether the used keys are allowed. If the key is not allowed for the
object a warning will be displayed.
The check is added  especially for JSON objects which might be created
by the user.

FAPI: Check JSON objects during deserialization.

---

include/tss2/tss2_tcti.h

This addresses one of the two issues mentioned in #1555.

tss2-tcti: fix 'invalid application of 'sizeof' to a void type'

---

src/tss2-fapi/api/Fapi_CreateNv.c
src/tss2-fapi/ifapi_keystore.c

* Searching for objects in the key store did not work if policies did occur in the
path list before the object to be compared. The policy files are now skipped during searching.
*  The system flag for NV objects was set to TPM2_NO. So NV objects were
saved in the user store. The system flag now is set to TPM2_YES to
assure that NV objects are stored in the system store.

FAPI: Fix setting of the system flag of NV objects (Fixes #1869)

---

src/tss2-fapi/api/Fapi_Delete.c
test/integration/fapi-key-create-policy-authorize-nv-sign.int.c

* Exactly one policy file passed to Fapi_Delete could not be deleted, because the passed
path was used as directory.
* One integration test was extended to add this test case.

Fapi fix delete policy file

---

Makefile-test.am
Makefile.am
src/tss2-fapi/api/Fapi_NvExtend.c
src/tss2-fapi/api/Fapi_NvIncrement.c
src/tss2-fapi/api/Fapi_NvSetBits.c
src/tss2-fapi/ifapi_policy_calculate.c
test/data/fapi/policy/pol_nv_counter.json
test/integration/fapi-key-create-policy-nv-counter-sign.int.c

* The written flag was not set for increment, set bits, and extend, which caused wrong computation
of NV name after deserialization.
* For PolicyNV the WRITTEN bit is set during policy calculations, because during policy execution
it will be set.
*  To check whether the nv written flag was set correctly after fapi increment this
test was added.

Fapi: Fix setting of the written flag of NV objects in FAPI NV commands

---

src/tss2-fapi/api/Fapi_CreateNv.c
src/tss2-fapi/api/Fapi_Delete.c
src/tss2-fapi/api/Fapi_NvExtend.c
src/tss2-fapi/api/Fapi_NvIncrement.c
src/tss2-fapi/api/Fapi_NvSetBits.c
src/tss2-fapi/ifapi_keystore.c
src/tss2-fapi/ifapi_policy_calculate.c

* Fix setting written flag for NV commands and PolicyNV.
* Fix deleting exactly one policy file.
* Fix setting of the system flag of NV objects (Fixes #1869)
* Fix wrong file loading during object search.

Fapi: several fixes for 3.0.x

---

src/tss2-fapi/api/Fapi_CreateNv.c
src/tss2-fapi/api/Fapi_Delete.c
src/tss2-fapi/api/Fapi_NvExtend.c
src/tss2-fapi/api/Fapi_NvIncrement.c
src/tss2-fapi/api/Fapi_NvSetBits.c
src/tss2-fapi/ifapi_keystore.c
src/tss2-fapi/ifapi_policy_calculate.c

* Fix setting written flag for NV commands and PolicyNV.
* Fix deleting exactly one policy file.
* Fix setting of the system flag of NV objects (Fixes #1869)
* Fix wrong file loading during object search.

Fapi: Several fixes for 2.4.x

---

lib/tss2-esys.pc.in
lib/tss2-fapi.pc.in
lib/tss2-mu.pc.in
lib/tss2-rc.pc.in
lib/tss2-sys.pc.in
lib/tss2-tcti-cmd.pc.in
lib/tss2-tcti-device.pc.in
lib/tss2-tcti-mssim.pc.in
lib/tss2-tcti-swtpm.pc.in
lib/tss2-tctildr.pc.in

Replace false $includedir/tss with $includedir/tss2.
Fixes: #1876

PKG-CONFIG: Fix include-dir (backport)

---

.ci/travis.run
.travis.yml

Switch from Dockerhub to Github Container Registry. This is due to
Dockerhub limiting pulls for unauthenticated users. Also, change
DOCKER_TAG to DOCKER_IMAGE since it's no longer a "tag" and is the name
of the image itself.

CI: switch to github container registry

---

src/tss2-fapi/ifapi_keystore.c

Fix a memory leak in async keystore load.
Signed-off-by: John Andersen <johnandersenpdx@gmail.com>

Fapi: Fix memory leak

---

src/tss2-fapi/fapi_crypto.c

Vendor certificates are not guaranteed to include CRL distribution
points.  When seeing such a certificate, get_crl_from_cert still tries
to download the CRL from NULL url and fails due to an error returned
from libcurl; the error is then propagated up the stack and causes the
whole operation to fail.
Handle certificates with no CRL dist points gracefully, by returning
success and NULL crl.  The caller, ifapi_verify_ek_cert, is already
prepared to deal with NULL crls.
Signed-off-by: Roman Kagan <rvkagan@gmail.com>

FAPI: accept certificates with no CRL dist points

---

src/tss2-fapi/api/Fapi_List.c
src/tss2-fapi/ifapi_keystore.c
test/integration/fapi-check-wrong-paths.int.c

* If a certain path is not found only a warning will be produced.
A null pointer will be returned for the object list.
* The return code "path not" found will be changed to "bad path" if
the search path cannot be mapped to a possible FAPI entity.
* The test check wrong paths was adapted.

FAPI: Fix return codes of Fapi_List  (Addresses #1888)

---

src/tss2-fapi/ifapi_policy_execute.c

TPM nonces were not freed in error cases for policy signed and policy secret.

FAPI: Fix memory leak in policy execution.

---

src/tss2-fapi/api/Fapi_Provision.c

This case should not occur, but due to a signaled coverity error the
NULL pointer check for path was added.

FAPI: Add check for path of hierarchies in provisioning.

---

Makefile-test.am
Makefile.am
src/tss2-fapi/fapi_crypto.c
src/tss2-fapi/ifapi_helpers.c
src/tss2-fapi/ifapi_policy_callbacks.c
src/tss2-fapi/ifapi_policy_callbacks.h
src/tss2-fapi/ifapi_policy_execute.c
src/tss2-fapi/ifapi_policy_execute.h
src/tss2-fapi/ifapi_policy_instantiate.c
src/tss2-fapi/ifapi_policy_json_deserialize.c
src/tss2-fapi/ifapi_policy_json_serialize.c
src/tss2-fapi/ifapi_policy_types.h
test/data/fapi/policy/pol_authorize_ecc_pem.json
test/data/fapi/policy/pol_authorize_rsa_pem.json
test/data/fapi/policy/pol_pcr16_0_ecc_authorized.json
test/data/fapi/policy/pol_pcr16_0_rsa_authorized.json
test/integration/fapi-key-create-policy-authorize-pem-sign.int.c

* Usage of PEM keys in Policy Authorizations is now supported. Externally produced
signatures together with the public PEM key now can be added to the policy file.
*  policyRef is now included in the comparison for policy search.
*  A test for PolicyAuthorize with PEM keys was added.

FAPI:  Enable usage of PEM keys for  policy authorization.

---

src/tss2-fapi/api/Fapi_List.c
src/tss2-fapi/api/Fapi_Provision.c
src/tss2-fapi/fapi_crypto.c
src/tss2-fapi/ifapi_keystore.c
src/tss2-fapi/ifapi_policy_callbacks.c
src/tss2-fapi/ifapi_policy_callbacks.h
src/tss2-fapi/ifapi_policy_execute.c
src/tss2-fapi/ifapi_policy_execute.h
test/integration/fapi-check-wrong-paths.int.c

* Include policyRef into policy search for policy authorize.
* Add check for path of hierarchies in provisioning.
* Fix memory leak in policy execution.
* Adapt return codes of the test check wrong paths.
* Fix return codes of Fapi_List (Addresses #1888)
* Accept certificates with no CRL dist points

Fapi backport fixes 3.0.x

---

src/tss2-fapi/fapi_crypto.c
src/tss2-fapi/ifapi_policy_callbacks.c
src/tss2-fapi/ifapi_policy_callbacks.h
src/tss2-fapi/ifapi_policy_execute.c
src/tss2-fapi/ifapi_policy_execute.h

* Include policyRef into policy search for policy authorize.
* Fix memory leak in policy execution.
* Accept certificates with no CRL dist points

Fapi backport fixes 2.4.x

---

doc/doxygen.dox

In the current FAPI version the first callback parameter is objectPath. In doxygen
FAPI_CONTEXT was used as first parameter.

Doxygen: Fix typedefs of FAPI callback parameters (Addresses #1901).

---

src/tss2-fapi/api/Fapi_List.c
src/tss2-fapi/ifapi_keystore.c
src/tss2-fapi/ifapi_keystore.h
test/integration/fapi-get-random.int.c
test/integration/fapi-key-create-policy-authorize-sign.int.c

* It will be checked whether the profile directory exists for expanded
pathnames which start with a profile name.
If the profile directory does not exist TSS2_FAPI_RC_NOT_PROVISIONED
will be returned by Fapi_List, and the function which computes absolute
pathnames to read objects from the keystore.
* One integration test was extended to test the profile checking.

Fapi add provisioning check

---

src/tss2-fapi/api/Fapi_List.c
src/tss2-fapi/ifapi_keystore.c
src/tss2-fapi/ifapi_keystore.h
test/integration/fapi-get-random.int.c

It will be checked whether the profile directory exists for expanded
pathnames which start with a profile name.
If the profile directory does not exist TSS2_FAPI_RC_NOT_PROVISIONED
will be returned by Fapi_List, and the function which computes absolute
pathnames to read objects from the keystore.

FAPI: Add provisioning check for 3.0.x.

---

src/tss2-esys/esys_crypto_ossl.c

* Reduce usages of OSSL _ex suffixed routines when not needed.
* Remove duplicate calls of EVP_EncryptInit and EVP_DecryptInit as key and iv are set in the initial call; no need for the piecemeal style setting of key and iv.

ESYS OSSL Crypto: Cleanups

---

src/tss2-fapi/ifapi_keystore.c

* Misleading error messages were changed.
* The return code for not existing hierarchies was fixed.

FAPI: Fix path error handling for not existing files.

---

src/tss2-fapi/ifapi_keystore.c

Commit 05d9ebd1c3ffe7011fc5062211c3a7013f9b33df added a provisioning check to `rel_path_to_abs_path()` that always returns early with `TSS2_FAPI_RC_PATH_NOT_FOUND` if the FAPI is provisioned. This leads to dead code in the rest of the function and possibly wrong return codes, breaking software that relies on a return value of `TSS2_FAPI_RC_KEY_NOT_FOUND` instead of `TSS2_FAPI_RC_PATH_NOT_FOUND`, e.g. [tpm2-pkcs11](https://github.com/tpm2-software/tpm2-pkcs11/blob/8f2b96fbbbeb6c236d719857f86fdc672bf3b6fc/src/lib/backend_fapi.c#L385-L387).

FAPI: fix provisioning check in rel_path_to_abs_path()

---

src/tss2-fapi/ifapi_keystore.c

Backport #1913 to the 3.0.x branch since the latest release [3.0.2](https://github.com/tpm2-software/tpm2-tss/releases/tag/3.0.2) is affected as well.

[3.0.x] FAPI: fix provisioning check in rel_path_to_abs_path()

---

src/tss2-fapi/ifapi_policy.c

* Computed policy list for evaluation was not deleted in error cases.
* The pointer to the computed policy list was not set to NULL after cleanup.

FAPI: Fix cleanup in policy digest computation (2.4.x).

---

src/tss2-fapi/ifapi_policy.c

* Computed policy list for evaluation was not deleted in error cases.
* The pointer to the computed policy list was not set to NULL after cleanup.

FAPI: Fix cleanup in policy digest computation (3.0.x).

---

src/tss2-fapi/ifapi_policy_execute.c

The error message "Load external key" was misleading.

FAPI: Fix error message for the execution of PolicyAuthorize.

---

Makefile-test.am
Makefile.am
src/tss2-fapi/api/Fapi_ExportPolicy.c
src/tss2-fapi/fapi_int.h
src/tss2-fapi/ifapi_policy.c
test/data/fapi/P_RSA_nameAlg_sha1.json
test/integration/fapi-export-policy.int.c

* One bugfix for cleanup after policy evaluation with errors was added.
* The computation of policy digests was added to Fapi_ExportPolicy if
the policy to be exported was read from the policy store.
* An integration test for all polices used in integration tests was added.

Fapi export policy compute digest

---

README.md

Since the readme was written, several updates to the TCG specification occurred.
The implementation followed these new specs, but the readme was not updated.
This patch updates the urls to the latest specification versions and references
the official names for the specifications.
Signed-off-by: Peter Huewe <peter.huewe@infineon.com>

Readme: Update to latest TCG Specs

---

test/integration/fapi-key-create-policy-authorize-pem-sign.int.c

If the integration tests were compiled with --enable-debug in one integration test
undeclared variables were used.

FAPI: Fix compilation error for integration tests in debugging mode.

---

src/tss2-fapi/ifapi_config.c
src/tss2-fapi/ifapi_profiles.c

* If mandatory fields are not found an error message with the field name
will be displayed instead of "BAD VALUE"
* If a field value  cannot be deserialized now here also the field name will
be part of the error message.

FAPI: Improve error messages for reading of config and profile files.

---

src/tss2-tcti/tcti-cmd.c
src/tss2-tcti/tcti-device.c
src/tss2-tcti/tcti-mssim.c

TCTIs are supposed to populate the pollevent structure such that it can be used with the `poll()` syscall.
However many did not set the events field, leading to infinite waits in poll.
I'm not entirely sure on the bits each of the tctis needs.
@williamcroberts what are the poll-events for tcti-cmd for example ?

TCTIs: Add missing events bits to pollhandles

---

src/tss2-fapi/ifapi_helpers.c

The type of the path "/nv/" was not determined correctly as an NV path.
It did work e.g. for "/nv" and "/nv/..." but not for "/nv/".
So Fapi_List could not be called with path "/nv/".

FAPI: Fix determination of object type from path.

---

src/tss2-fapi/ifapi_helpers.c

The type of the path "/nv/" was not determined correctly as an NV path.
It did work e.g. for "/nv" and "/nv/..." but not for "/nv/".
So Fapi_List could not be called with path "/nv/".

FAPI: Fix determination of object type from path (3.0.x).

---

src/tss2-fapi/ifapi_helpers.c

The type of the path "/nv/" was not determined correctly as an NV path.
It did work e.g. for "/nv" and "/nv/..." but not for "/nv/".
So Fapi_List could not be called with path "/nv/".

FAPI: Fix determination of object type from path (2.4.x).

---

Makefile-test.am
Makefile.am
src/tss2-fapi/ifapi_policy_callbacks.c
src/tss2-fapi/ifapi_policy_execute.c
src/tss2-fapi/ifapi_policy_json_deserialize.c
test/data/fapi/policy/pol_or_read_write_secret.json
test/integration/fapi-policy-or-nv-read-write.int.c

* In some policy execution functions the policy state was not initialized
correctly after successful policy execution.
The policies "secret", "authorize_nv",and "action" were affected.
* An integration test with a test case, which caused this error, was added.

FAPI: Fix state handling in policy execution (Fixes #1937).

---

src/tss2-fapi/ifapi_policy_callbacks.c
src/tss2-fapi/ifapi_policy_execute.c

In some policy execution functions the policy state was not initialized
correctly after successful policy execution.
The policies "secret", "authorize_nv", and "action" were affected.
Fixes Issue #1937.

FAPI: Fix state handling in policy execution (3.0.x).

---

src/tss2-fapi/ifapi_policy_callbacks.c
src/tss2-fapi/ifapi_policy_execute.c

In some policy execution functions the policy state was not initialized
correctly after successful policy execution.
The policies "secret", "authorize_nv", and "action" were affected.
Fixes Issue #1937.

FAPI: Fix state handling in policy execution (2.4.x).

---

include/tss2/tss2_fapi.h

Add missing stdint.h and stddef.h header files for things like uint32_t
and size_t respectively.

include/tss2_fapi.h: add stddef and stdint h files

---

src/tss2-esys/esys_context.c
src/tss2-fapi/api/Fapi_Finalize.c

The warning if a NULL pointer was passed is deleted to allow customary
NULL passing to the functions without producing a warning.
Addresses Issue #1942.

ESYS/FAPI: Remove warning from Esys_Finalize and Fapi_Finalize.

---

src/tss2-fapi/fapi_certificates.h

Unlike other certificates in fapi_certificates.h, STM root certificates
are not self-signed.  Rather, they are signed by the respective (RSA or
ECC) GlobalSign TPM Root CA certificates.
As a result, the certificate chain built for STM devices does not
terminate in a self-signed certificate, and openssl's X509_verify_cert
refuses to verify it, so provisioning fails with ifapi_verify_ek_cert()
reporting "unable to get issuer certificate".
Arguably it's a bug in OpenSSL -- to try to search for issuer's
certificate in the chain prior to checking the current certificate's
trust status.  However, it appears easier to work it around here.
So add the proper root CAs to the trusted certificate store.  At the
time of this writing, the certificates are available (in DER format) at …

tss2-fapi: add GlobalSign TPM Root CA certs

---

configure.ac

With autoconf 2.70, not quoting the second argument to one of the AS_IF
macro expansions leads to generation of invalid shell code affecting the
first nested ERROR_IF_NO_PROG expansion.
The invalid shell code leads to an error resembling:
```
./configure: line 18826: syntax error near unexpected token `newline'
./configure: line 18826: `    '''
```
Fix the issue by quoting the second argument to the affected AS_IF,
similar to the quoting found elsewhere in configure.ac.
Signed-off-by: Patrick McCarty <patrick.mccarty@intel.com>

configure.ac: fix compatibility with autoconf 2.70

---

configure.ac

Autoconf 2.70 [has been released](https://lists.gnu.org/archive/html/autoconf/2020-12/msg00002.html) and does not like it when `AS_IF` arguments are not quoted using square brackets, producing wrong macro expansions leading to errors like
```
checking for CURL... yes
./configure: line 18882: syntax error near unexpected token `newline'
./configure: line 18882: `    '''
```

configure.ac: quote AS_IF arguments to avoid errors with Autoconf 2.70

---

src/tss2-fapi/ifapi_config.c

When "log_dir" was missing from the FAPI configuration a segmentation fault was produced
in Fapi_Finalize because free was called for a string constant.
Fixes issue #1959.

FAPI: Fix initialization of default log_dir.

---

Makefile-test.am
src/tss2-esys/api/Esys_Create.c
src/tss2-esys/api/Esys_CreateLoaded.c
src/tss2-esys/api/Esys_CreatePrimary.c
src/tss2-esys/api/Esys_NV_DefineSpace.c
src/tss2-esys/esys_int.h
src/tss2-esys/esys_iutil.c
src/tss2-esys/esys_iutil.h
src/tss2-esys/esys_tr.c
test/integration/esys-create-session-auth.int.c
test/integration/esys-nv-ram-counter.int.c

* The size of the auth value for keys and NV objects is restricted to the size
of the name hash algorithm of these objects.  Esapi will use the
hash of the user auth values as auth value for these object.
The maximal size will be sizeof(TPMU_HA).
* Test cases for keys and NV objects with large auth values were added.

ESYS: Enable large auth value for keys and NV objects (Addresses #1008).

---

src/tss2-sys/api/Tss2_Sys_Initialize.c

It should be fine to use the `TSS2_ABI_VERSION_CURRENT` defined in tss2_common.h

code review: Why ABI version number was defined in 2 different places?

---

.cirrus.yml
Makefile-test.am
src/tss2-fapi/ifapi_config.c
src/tss2-fapi/ifapi_get_intl_cert.c
src/tss2-fapi/ifapi_io.c
src/tss2-fapi/ifapi_profiles.c
test/unit/fapi-config.c
test/unit/fapi-get-intl-cert.c
test/unit/fapi-helpers.c
test/unit/fapi-io.c
test/unit/fapi-profiles.c

* Fix clean-up in several error cases which could occur in file reading and
retrieving certificates.
* Unit tests were added for profile and config reading, for FAPI io, for FAPI helper
functions, and retrieving the INTEL certificates.
*The  update in cirrus ci was fixed.

FAPI:  Fix error clean-up for file reading and certificate searching and unit tests

---

src/tss2-fapi/ifapi_config.c

`out` needs to be fully initialised from the beginning because the `ifapi_json_IFAPI_CONFIG_deserialize` function [uses `return_if_error`](https://github.com/tpm2-software/tpm2-tss/blob/b211887403f646a7d09be1059a94ed943955c9b7/src/tss2-fapi/ifapi_config.c#L56), potentially leaving the struct only partly initialised when there is an error during JSON deserialisation. This causes a problem as `ifapi_config_initialize_finish` [tries to free all struct members in case of an error](https://github.com/tpm2-software/tpm2-tss/blob/b211887403f646a7d09be1059a94ed943955c9b7/src/tss2-fapi/ifapi_config.c#L260-L268). Attempting to free an uninitialised pointer can lead to a segfault crash.
This can be observed when running the [`fapi-config` unit …

FAPI: initialise 'out' parameter in ifapi_json_IFAPI_CONFIG_deserialize

---

.cirrus.yml

Rather than ignoring an error, set to the newest stable FreeBSD cirrus
version of 12-2. This seems to avoid the package/kernel mismatch errors.

ci/cirrus: drop IGNORE_OSVERSION and set to 12-2

---

src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_config.c
src/tss2-fapi/ifapi_get_intl_cert.c
src/tss2-fapi/ifapi_io.c
src/tss2-fapi/ifapi_policy_callbacks.c
src/tss2-fapi/ifapi_policyutil_execute.c
src/tss2-fapi/ifapi_profiles.c

* Fix error cleanup for key loading and policy execution.
* Fix initialization of default log_dir.
* Fix cleanup in several error cases.
* initialise 'out' parameter in ifapi_json_IFAPI_CONFIG_deserialize

FAPI: Several backport fixes for 3.0.x

---

include/tss2/tss2_mu.h

Remove double define from API header `tss2/tss2_mu.h`.
They are also defined here:
https://github.com/tpm2-software/tpm2-tss/blob/27d3bd8295a58d5788cf4ea220f614603d5c2fee/include/tss2/tss2_mu.h#L1998-L2010

marshal: remove double define

---

configure.ac
doc/logging.md
src/util/log.c

Add support for logging to a file specified via the env variable `TSS2_LOGFILE`. Log file support can be disabled via the configure flag `--disable-log-file.`
Creates the log file if it does not exist, appends to it otherwise. Prints to stderr if the file cannot be opened.
Examples:
* `TSS2_LOGFILE=tpm2-tss.log ./test/integration/esys-get-random.int`
* `TSS2_LOGFILE=stderr ./test/integration/esys-get-random.int`
* `TSS2_LOGFILE=stdout ./test/integration/esys-get-random.int`
* `TSS2_LOGFILE=- ./test/integration/esys-get-random.int`
Signed-off-by: Johannes Holland <johannes.holland@infineon.com>

log: add support for logging to a file

---

src/tss2-sys/api/Tss2_Sys_CertifyCreation.c

No need to assign to rval since we are returning here.
Signed-off-by: Jerry Snitselaar <jsnitsel@redhat.com>

sys: Minor covscan cleanup in Tss2_Sys_CertifyCreation_Complete

---

src/tss2-fapi/fapi_crypto.c

The error should indicate a problem with the intermediate certificate not the EK Certificate.

Fix copy paste typo

---

Makefile-test.am
test/integration/esys-encrypt-decrypt.int.c

The integration test Esys_EncryptDecrypt was extended to test also
Esys_EncryptDecrypt2.

FAPI: Add integration test for Esys_EncryptDecrypt2.

---

Makefile-test.am
src/tss2-fapi/ifapi_io.c
test/unit/fapi-io.c

* Before trying to open a file for reading it will be checked whether the file is
a directory and wheter read access is possible.
* The return codes for fseek, ftell, and fopen will be checked in all cases.
* Fixes  #1978

FAPI: Improve checks for file access.

---

doc/doxygen.dox

Doxygen definitions for some functions which were removed are deleted.

FAPI: Update doxygen

---

Makefile-test.am
src/tss2-esys/api/Esys_StartAuthSession.c
test/integration/esys-create-session-auth.int.c

* If ESYS_TR_RH_NULL was used as bind parameter for Esys_StartAuthSession the wrong HMAC
was computed, because the session was not treated as unbound session.
It will be checked whether no tpm key is passed and ESYS_TR_RH_NULL is used as bind
parameter to skip KDF computation of the session key.
* Integration tests to check bind with ESYS_TR_RH_NULL was added,

 ESYS: Fix binding of ESYS_TR_RH_NULL (Fixes #1993)

---

Makefile-test.am

When we enable unit tests only but not integration tests there will be a ‘TOP_SOURCEDIR’ undeclared error
See below
#./configure --enable-unit
#make check -j1
make  test/unit/CommonPreparePrologue test/unit/CopyCommandHeader test/unit/io test/unit/key-value-parse test/unit/log test/unit/tctildr test/unit/tctildr-dl test/unit/tctildr-nodl test/unit/tctildr-tcti test/unit/tctildr-getinfo test/unit/UINT8-marshal test/unit/UINT16-marshal test/unit/UINT32-marshal test/unit/UINT64-marshal test/unit/TPMA-marshal test/unit/TPM2B-marshal test/unit/TPMS-marshal test/unit/TPML-marshal test/unit/TPMT-marshal test/unit/TPMU-marshal test/unit/sys-execute test/unit/tss2_rc test/unit/tcti-mssim test/unit/tcti-swtpm test/unit/tcti-device test/unit/tcti-pcap test/unit/tcti-cmd test/unit/esys-context-null …

Fix TOP_SOURCEDIR undeclared error when enable unit test checks only

---

.ci/docker.run
.cirrus.yml
configure.ac
src/tss2-fapi/api/Fapi_Provision.c

* The root certificate defined by the environment variable FAPI_TEST_ROOT_CERT will
only be used if it's allowed to use self generated root certificate with
./configure  --enable-self-generated-certificate
* This option is added to all integration tests which are using the TPM simulator.

FAPI: Fix reading of the root certificate for provisioning.

---

include/tss2/tss2_common.h
include/tss2/tss2_sys.h
include/tss2/tss2_tcti.h
include/tss2/tss2_tpm2_types.h

Currently, the struct/union typedef definitions are in the form of:
typedef struct {
int thing1;
int thing2;
} TYPE_NAME;
This has the side affect of causing an anonomous structure definition,
which causes code that uses the 'struct' keyword to fail with errors
like:
- expected ‘TPM2B_DIGEST **’ {aka ‘struct <anonymous> **’} but argument is of type ‘struct TPM2B_DIGEST **
To correct this, make them non-anonymous by declaring the typedef fully
and then defining the structure.
Further reading:
- https://stackoverflow.com/questions/32999739/gcc-gives-confusing-warning-message-when-using-pointer-to-struct-typedef
- https://stackoverflow.com/questions/17720223/c-typedef-struct-name-vs-typedef-struct-name/23660072
This will take updates to the TCG TSS spec as well.
Signed-off-by: William …

headers: fix typedef/struct declarations

---

configure.ac
test/integration/main-fapi.c

Since commit 199b4edc265b2f4758aa22ebf4ed6472a34b9a7a ("FAPI: Fix reading of the root certificate for provisioning.") it is required to specify `--enable-self-generated-certificate` in order to make the FAPI integration tests pass. This is an option that should usually not be enabled in production builds for security reasons, but still some form of integration testing might be desirable in this case to verify whether the compiled library works as expected. Use `FAPI_TEST_EK_CERT_LESS` in this case to run the tests without EK certificate validation.

FAPI: use FAPI_TEST_EK_CERT_LESS with --disable-self-generated-certificate

---

src/util/io.h

The random build failures on Cirrus CI seems to be related
to IO errno 35: Resource temporarily unavailable error.
https://cirrus-ci.com/task/5455668787281920?command=main#L2013
Handling for retries is done in select() on Linux,
but on FreeBSD select() returns immediately.
Need to add read() retry handling for FreeBSD specifically.
Fixes: #2002

tcti: add read eagain handling for freeBSD

---

src/tss2-tcti/tcti-mssim.c

Windows build failes with
error : member reference base type 'TSS2_TCTI_POLL_HANDLE'
(aka 'void *') is not a structure error.
https://ci.appveyor.com/project/tstruk/tpm2-tss/build/job/rshu41fripqevvoi#L717

tcti: fix windows build

---

configure.ac

When fuzzing is enabled we enforce clang and check if $CC == "clang".
That was fine before, but now the OSS fuzz compiler is called
/src/aflplusplus/afl-clang-fast.
Fixes: #2005

configure: fix oss fuzz build

---

src/tss2-fapi/ifapi_io.c
src/tss2-fapi/ifapi_keystore.c

* The check could be removed. Errors will be handled by fopen.
* The error messages related to fopen were improved.
* One leak related to file opening was fixed: If access to the file to
be loaded was not possible the computed path string was not freed.

FAPI: Fix invalid check of read access rights.

---

src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_config.c
src/tss2-fapi/ifapi_get_intl_cert.c
src/tss2-fapi/ifapi_io.c
src/tss2-fapi/ifapi_policy_callbacks.c
src/tss2-fapi/ifapi_policyutil_execute.c
src/tss2-fapi/ifapi_profiles.c

* Fix error cleanup for key loading and policy execution.
* Fix initialization of default log_dir.
* Fix cleanup in several error cases.
* initialise 'out' parameter in ifapi_json_IFAPI_CONFIG_deserialize

FAPI: Several backport fixes for 2.4.x

---

INSTALL.md
Makefile.am
configure.ac

install-data-hook uses systemd helpers for creating users and tmpfiles,
but on systems where there is no systemd or not all the helpers are
installed it needs to fall back to the old methods.
This should improve the make install step on some old systems
like ubuntu 16.04.
Fixes: #2016

configure: improve make install on systems without systemd

---

test/integration/fapi-key-create2-sign.int.c

The changed owner auth had to be reset in order not to brick physical TPMs.

FAPI: Fix integration test with changed owner auth.

---

Makefile.am

PR #2019 made the installation routine abort with an error if the `tss` user or the FAPI directories cannot be created.
However, these actions are expected to fail if the installation is not run as root, e.g.  for distribution packaging using `DESTDIR`. In this case, the failure leads to a potentially incomplete installation, additionally suppressing the exit status of make might hide actual build failures.
Furthermore, `systemd-sysusers` and `systemd-tmpfiles` are run on every system start, so a failure is not a huge problem since it will be fixed by the next reboot. Print a noisy warning to inform the user that something is potentially wrong, but continue with the installation.

configure: make tss user and FAPI directory creation non-fatal

---

Makefile.am

The name of the file with the configuration data had to be added as parameter
to the commands systemd-tmpfiles and systemd-sysusers.
Fixes #2025.

configure: Add pathname of config file to systemd-tmpfiles

---

src/tss2-fapi/api/Fapi_Import.c
src/tss2-fapi/ifapi_keystore.c
src/tss2-fapi/ifapi_policy_store.c
src/tss2-fapi/ifapi_policy_store.h
test/integration/fapi-ext-public-key.int.c
test/integration/fapi-key-create-policy-pcr-sign.int.c

* If files to be imported exist in the keystore or in the policy store the
error FAPI_RC_PATH_ALREADY_EXISTS will be returned.
Fixes #2028.
* It should not be possible to overwrite file with Fapi_Import. If the
files already exist in keystore or policy store they will be deleted before
the execution of Fapi_Import.
* A potential memory corruption in Fapi_Import was fixed.

FAPI: Fix check overwriting of files in Fapi_Import.     

---

src/tss2-fapi/api/Fapi_Import.c

An illegal free was executed for non key objects in Fapi_Import.

FAPI: Fix potential memory corruption in Fapi_Import 3.0.x

---

src/tss2-fapi/api/Fapi_Import.c

An illegal free was executed for non key objects in Fapi_Import.

FAPI: Fix potential memory corruption in Fapi_Import 2.4.x

---

src/tss2-esys/esys_iutil.c

The @retval documentation was removed for this void function.
Fixes #2036.

ESYS: fix doxygen header of function iesys_update_session_flags

---

src/tss2-esys/esys_iutil.c

Fixes #2037
TPM2.0 Architecture 19.6.5 Note 7
If the same session (not the first session) is used for decrypt and
encrypt, its nonceTPM is only used once. If different sessions are
used for decrypt and encrypt, both nonceTPMs are included.
Signed-off-by: Imran Desai <imran.desai@intel.com>

esys_iutil.c: Fix issue where nonceTPM was included twice in hmac

---

src/tss2-fapi/fapi_crypto.c
src/tss2-fapi/ifapi_policy_calculate.c
src/tss2-tcti/tcti-swtpm.c

This patch fixed the setting of maxloglevel during configure wrt unused variables throughout the stack.
No clue how far this needs to be backported

Enable lower maxlog levels

---

src/tss2-esys/esys_crypto_mbed.c
src/tss2-esys/esys_crypto_mbed.h
src/tss2-esys/esys_crypto_ossl.c
src/tss2-esys/esys_crypto_ossl.h
src/tss2-esys/esys_iutil.c
test/unit/esys-crypto.c

AES block size is const.
Remove redundant blk_size param from enc() and dec() functions.

esys_crypto: remove redundant blk size param

---

src/tss2-esys/esys_crypto_mbed.c
src/tss2-fapi/api/Fapi_ChangeAuth.c
src/tss2-fapi/api/Fapi_CreateNv.c
src/tss2-fapi/api/Fapi_Import.c
src/tss2-fapi/api/Fapi_NvExtend.c
src/tss2-fapi/api/Fapi_NvIncrement.c
src/tss2-fapi/api/Fapi_NvSetBits.c
src/tss2-fapi/api/Fapi_NvWrite.c
src/tss2-fapi/api/Fapi_Provision.c
src/tss2-fapi/api/Fapi_SetAppData.c
src/tss2-fapi/api/Fapi_SetCertificate.c
src/tss2-fapi/api/Fapi_SetDescription.c
src/tss2-fapi/api/Fapi_WriteAuthorizeNV.c
src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_keystore.c
src/tss2-fapi/ifapi_keystore.h
src/tss2-fapi/ifapi_policy_calculate.c
src/tss2-fapi/ifapi_policy_execute.c
src/tss2-fapi/ifapi_policy_store.c
src/tss2-fapi/ifapi_policy_store.h
src/tss2-mu/tpms-types.c
src/util/aux_util.h
test/integration/esys-create-session-auth.int.c

Corrects:
- src/util/aux_util: drop NDEBUG from  MAYBE_UNUSED_MACRO
- test: conditionally include primaryHandle_AuthSession
- test: simplify conditional compilation expression
- test: fix preprocessor if statements
- fapi: remove UNUSED variables
- tpms-types.c: mark param as UNUSED not MAYBE_UNUSED

fix issues with MAYBE_UNUSED

---

src/tss2-tcti/tcti-device.c

If partial read is not supported then tcti_common->partial will be used
uninitialized in tcti_device_receive().
Signed-off-by: Jeffrey Ferreira <jeffpferreira@gmail.com>

tcti-device: 'partial' may be used uninitialized

---

test/data/fapi/P_RSA_sh_policy.json

One profile was left out during commit "TEST: Change used hash
algorithm from sha1 to sha256."
Fix this as well.
Maybe we can include this in 3.1.0 ?

TEST: Change remaining used hash algorithm from sha1 to sha256.

---

include/tss2/tss2_mu.h

It would be good to get this commit into 3.0.x as the double BYTE marshal functions doesn't work well with python cffi.

cherry-pick: marshal: remove double define

---

doc/doxygen.dox
include/tss2/tss2_esys.h
include/tss2/tss2_sys.h
src/tss2-esys/api/Esys_EncryptDecrypt.c
src/tss2-esys/api/Esys_EncryptDecrypt2.c
src/tss2-fapi/ifapi_profiles.c
src/tss2-fapi/ifapi_profiles.h
src/tss2-fapi/tpm_json_deserialize.c
src/tss2-fapi/tpm_json_deserialize.h
src/tss2-fapi/tpm_json_serialize.c
src/tss2-fapi/tpm_json_serialize.h
src/tss2-sys/api/Tss2_Sys_EncryptDecrypt.c
src/tss2-sys/api/Tss2_Sys_EncryptDecrypt2.c
test/integration/esys-encrypt-decrypt.int.c
test/integration/sys-util.c
test/unit/esys-resubmissions.c
test/unit/esys-tcti-rcs.c
test/unit/esys-tpm-rcs.c

Update EncryptDecrypt and EncryptDecrypt2 function definitions
and change the mode type from TPMI_ALG_SYM_MODE to TPMI_ALG_CIPHER_MODE.
to make it complient with the TPM2.0 1.59 specification.
These types are the same (UINT16) so there is no impact to existing code.

sys: esys: EncryptDecrypt change mode type

---

README.md

I changed how appveyor was integrated and used the Integrations over the
webhook which just piggybacks off of Github Permissions over creating
your own thing like coverity, thus I disabled the webhook. It appears
that appveyor is still building, but it's now building under my
namespace. The old appveyor link was displaying builds over 2mo ago and
not updating anyways, while PRs were built under tstruk users history.

README: update appveyor

---

src/tss2-fapi/ifapi_io.c

in my opinion, the possibility of attempting a double freeing is visible. I propose to fix this with a simple solution.

fix for possible dual freeing.

---

Makefile-test.am
src/tss2-fapi/ifapi_io.c
test/unit/fapi-io.c

* According to RFC PR #2070 unnecessary function calls were removed.
* According to the recommendation of the lockf man page fcntl was used instead
of lockf to lock files to assure that the code is portable.
* The usage of lockf was replaced with usage of fcntl in the corresponding
unit test.

Fapi fix file locking

---

src/tss2-fapi/ifapi_policy.c

the specified condition will skip the value 16, which will cause a write outside the allocated memory.

fix of possible access outside the array.

---

configure.ac

Bumping the version manually in configure.ac is a recipe for disaster. It doesn't take into account the git tree state. Rather use git describe output. The only thing this really changes is you have to build from release tarball or git, you cant use the zip snapshot feature of github.
-----
Currently master will produce a version of 3.1.0-rc0, even though its 27
commits ahead of the tag at this moment and contain local uncommited
changed.
git describe --tags --always --dirty
3.1.0-rc0-27-gc6b77ca306dc-dirty
So we have three scenarios to consider:
release: version
rc: version + -rc<N>
dev: verions + anything tacked on (thats not just -rc<N>)
Release and dev versions stay the same, since nothing in their version
information is changing.
In the development scenario, pkg-config will consider …

configure: use git version over hardcode in init

---

test/unit/TPM2B-marshal.c
test/unit/TPMS-marshal.c
test/unit/UINT16-marshal.c
test/unit/UINT32-marshal.c
test/unit/UINT64-marshal.c
test/unit/UINT8-marshal.c

GCC 11 tightens static checks, leading to additional compiler warnings that are treated as errors due to `-Werror`.
<s>Since `-Werror` is enabled in release builds as well, it would be good to get these changes into the pending 3.1.0 release as well.</s> `-Werror` is [disabled](https://github.com/tpm2-software/tpm2-tss/blob/2bae50a3551cd8b0123ef609ea973678339df5ae/configure.ac#L435-L436) for releases, so this shouldn't directly affect the upcoming 3.1.0 release.

Avoid compiler warnings/errors in the unit test suite when building with GCC 11

---

src/tss2-fapi/api/Fapi_Quote.c
src/tss2-fapi/fapi_crypto.c

* A leak in Fapi_Quote was fixed.
* The useless code get_engine was removed.

Fapi fix leak in Fapi_Quote and remove useless code

---

src/tss2-fapi/api/Fapi_Provision.c
src/tss2-fapi/fapi_int.h

If a persistent handle is defined for the SRK and this persistent key does already
exist the key will be used if the name computed for this persistent key is equal
to the name for the key defined by the SRK attributes defined in the profile.
Addresses #1626

FAPI: Enable usage of existing persisting SRK for provisioning.

---

src/tss2-fapi/ifapi_helpers.c

The action string was not duplicated when the policy was copied.
Fixes: #2089

FAPI: Fix double free for policy action

---

src/tss2-fapi/api/Fapi_GetPlatformCertificates.c

The init state of the state machine ifapi_get_certificates was not set before the
first call. Fixes #2091.

FAPI: Set the init state of ifapi_get_certificates.

---

src/tss2-fapi/api/Fapi_Delete.c
src/tss2-fapi/api/Fapi_Provision.c
src/tss2-fapi/ifapi_json_deserialize.c
src/tss2-fapi/ifapi_json_serialize.c
src/tss2-fapi/ifapi_keystore.h

If the SRK did already exist during provisioning the persistent SRK will not be removed
by Fapi_Delete. Only the corresponding files in the keystore will be deleted.
Addresses #2098.

FAPI: Prohibit deletion of already existing persistent SRK.

---

src/tss2-fapi/ifapi_helpers.c

The action string was not duplicated when the policy was copied.
Fixes: #2089

FAPI: Fix double free for policy action 3.0.x

---

src/tss2-fapi/ifapi_helpers.c

The action string was not duplicated when the policy was copied.
Fixes: #2089

FAPI: Fix double free for policy action 2.4.x

---

src/tss2-fapi/api/Fapi_GetPlatformCertificates.c

The init state of the state machine ifapi_get_certificates was not set before the
first call. Fixes #2091.

FAPI: Set the init state of ifapi_get_certificates 2.4.x.

---

src/tss2-fapi/api/Fapi_GetPlatformCertificates.c

The init state of the state machine ifapi_get_certificates was not set before the
first call. Fixes #2091.

FAPI: Set the init state of ifapi_get_certificates 3.0.x

---

Makefile-test.am
src/tss2-fapi/api/Fapi_GetPlatformCertificates.c
src/tss2-fapi/ifapi_helpers.c
src/tss2-fapi/ifapi_io.c
test/unit/fapi-io.c

* Fix usage of lockf in fapi-io.
* Adapt unit test for fapi-io
* Fix double free for policy action.
* Set the init state of ifapi_get_certificates.

Fapi several backports for 3.1.x

---

script/ekca/intermed-ca.cnf

I double-searched and triple-searched-- these fields are (to my best knowledge) not used anywehere. Hence we can remove them to avoid conflicts when OpenSSL 3.0 is used, because it does natively recognize these OIDs.

Test: Remove unused configuration fields

---

src/tss2-esys/esys_crypto.c

If trace is activated LOGBLOB_TRACE is called with a wrong pointer to display
the obfuscated data. Fixes #2115.

ESYS: Fix buffer overflow in xor parameter obfuscation.

---

src/tss2-fapi/ifapi_config.c
src/tss2-fapi/ifapi_eventlog.c
src/tss2-fapi/ifapi_get_intl_cert.c
src/tss2-fapi/ifapi_helpers.c
src/tss2-fapi/ifapi_json_serialize.c
src/tss2-fapi/ifapi_keystore.c
src/tss2-fapi/ifapi_policy_store.c
src/tss2-fapi/ifapi_profiles.c
src/tss2-fapi/tpm_json_deserialize.c
src/tss2-fapi/tpm_json_deserialize.h
test/unit/fapi-json.c

For invalid JSON currently the position an type of the error is not displayed
in the error message. The user has to check the JSON data with another tool.
Now the line number and the column of the error will be displayed.

FAPI: Improve error messages for invalid JSON.

---

src/tss2-esys/esys_crypto.c

If trace is activated LOGBLOB_TRACE is called with a wrong pointer to display
the obfuscated data. Fixes #2115.

ESYS: Fix buffer overflow in xor parameter obfuscation 2.4.x.

---

src/tss2-esys/esys_crypto.c

If trace is activated LOGBLOB_TRACE is called with a wrong pointer to display
the obfuscated data. Fixes #2115.

ESYS: Fix buffer overflow in xor parameter obfuscation 3.0.x.

---

src/tss2-esys/esys_crypto.c

If trace is activated LOGBLOB_TRACE is called with a wrong pointer to display
the obfuscated data. Fixes #2115.

ESYS: Fix buffer overflow in xor parameter obfuscation 3.1.x.

---

src/tss2-fapi/ifapi_get_intl_cert.c

Intel certificates are decoded from a base64 string. The base64 decode function
returns NULL in error cases without error messages. Some error messages were added.
Addresses #2113 (check_get_intl_cert_ok).

FAPI: Improve error messages for decoding base64 data.

---

src/tss2-fapi/api/Fapi_Decrypt.c

The `cipherText` is a binary structure, so logging with `%s` often overflows the buffer as there is no NULL at the end, besides printing non-ASCII characters.

FAPI: Fix cipherText logging in Fapi_Decrypt_Async

---

Makefile.am

There is `$(LIBCRYPTO_LIBS)` but no `$(LIBCRYPTO_CFLAGS)` used when building FAPI. As a consequence one cannot build FAPI against an openssl from a non-standard location.
This PR fixes this.

Makefile.am: Use LIBCRYPTO_CFLAGS when building FAPI

---

script/ekca/create_ca.sh

The `openssl req -new` command is called twice, which is superfluous. Both the key and the certificate are created already by the first `openssl req -new` command.

Test: Remove duplicate openssl req -new

---

test/integration/fapi-data-crypt.int.c
test/integration/fapi-key-create-policy-signed.int.c

OpenSSL EVP API is not used correctly, which (mysteriously) works in OpenSSL 1.x, but fails with OpenSSL 3.0. This PR makes the code compatible with OpenSSL 1.0 through 3.0.
This PR combines two commits of a similar nature:
* The `EVP_DigestSignInit` should be called only once and before calling `EVP_PKEY_CTX_set_rsa_padding`. See a corresponding example [here](https://www.openssl.org/docs/man1.0.2/man3/EVP_PKEY_sign_init.html).
* The `EVP_PKEY_base_id` is the right way to detect key type, used also by OpenSSL itself. This function is available since OpenSSL 1.0.0 (as is the `EVP_DigestSignInit`) so it can be used also here.

FAPI Test: Fix incorrect usage of OpenSSL EVP API

---

INSTALL.md
configure.ac

To reduce the amount of `#ifdefs` and version-specific code we drop support for OpenSSL prior 1.1.0, including all forks such as LibreSSL, which are not API compatible with OpenSSL >= 1.1.0. This simplifies code review and maintenance. Moreover, the old OpenSSL versions are not maintained anymore, so using these libraries is not recommended from security reasons anyway.

Require OpenSSL >= 1.1.0

---

Makefile-test.am
src/tss2-fapi/ifapi_get_intl_cert.c
test/unit/fapi-get-intl-cert.c

This PR should work with OpenSSL 1.1.0 through 3.0.0 only, hence it depends on #2130.
Although the `EVP_DigestUpdate` functions are available in all OpenSSL versions and the `EVP_DigestFinal_ex` was added in OpenSSL 0.9.7, the `EVP_MD_CTX_new` was introduced in OpenSSL 1.1.0 (it was called `EVP_MD_CTX_create` before).
The `SHA256_Update` function was deprecated in OpenSSL 3.0.0, so it needs to be replaced.

FAPI: Change SHA256_Update to EVP_DigestUpdate

---

test/integration/sys-util.c

Drop support for OpenSSL < 1.1.0 and add support for OpenSSL >= 3.0.0.
The `HMAC_Update` is deprecated in OpenSSL 3.0, but the replacement `EVP_MAC_update` was added just in OpenSSL 3.0, so version specific code is needed.

Test: Use EVP_MAC_xxx with OpenSSL 3.0

---

src/tss2-esys/esys_crypto_ossl.c
src/tss2-esys/tss2-esys.vcxproj
src/tss2-fapi/fapi_crypto.c
test/helper/tpm_getek.c
test/helper/tpm_getek_ecc.c

This is the main (and last) PR for OpenSSL 3.0 support. For easier review it is split into two commits:
1) Drop support for OpenSSL < 1.1.0, which includes removal of code intended for old OpenSSL versions as well as functions that have no effect in OpenSSL >= 1.1.0
2) Implement EVP_PKEY export/import for OpenSSL 3.0, which covers TSS to OSSL and OSSL to TSS key conversion for RSA and ECC at ESYS and FAPI layers.
For more technical explanation please see the individual commit messages.

Implement EVP_PKEY export/import for OpenSSL 3.0

---

src/tss2-fapi/ifapi_helpers.c

For the download of some certificates 3xx redirects are used by the provider.
Thus redirects have to be allowed.
If https URLs are used the certificate needed for verification must exists in the ssl
certificate store.

FAPI: Allow following of redirects for curl downloads.

---

src/tss2-fapi/api/Fapi_Encrypt.c
src/tss2-fapi/fapi_int.h

The field out_data in IFAPI_Data_EncryptDecrypt was not used but freed in Fapi_Encrypt.

FAPI: Remove faulty free of an unused field.

---

src/tss2-fapi/api/Fapi_Encrypt.c
src/tss2-fapi/fapi_int.h

The field out_data in IFAPI_Data_EncryptDecrypt was not used but freed in Fapi_Encrypt.

FAPI: Remove faulty free of an unused field 3.1.x.

---

src/tss2-fapi/api/Fapi_Encrypt.c
src/tss2-fapi/fapi_int.h

The field out_data in IFAPI_Data_EncryptDecrypt was not used but freed in Fapi_Encrypt.

FAPI: Remove faulty free of an unused field 3.0.x

---

src/tss2-fapi/api/Fapi_Encrypt.c
src/tss2-fapi/fapi_int.h

The field out_data in IFAPI_Data_EncryptDecrypt was not used but freed in Fapi_Encrypt.

FAPI: Remove faulty free of an unused field 2.4.x

---

src/tss2-esys/esys_crypto_ossl.c
src/tss2-fapi/ifapi_get_intl_cert.c

From OpenSSL 1.1.0 it is deprecated. No explicit initialisation or de-initialisation is required.
This change should have been included in 73d25d6834ad362f9a9a907cb78452deaa336ec0, but it slipped off.

Remove deprecated OpenSSL_add_all_algorithms

---

src/tss2-fapi/fapi_crypto.c

The EVP_PKEY_bits can be used to get the key size instead, which simplifies the code. The function is available even in OpenSSL 1.0.2.

FAPI: Simplify key size retrieval

---

Makefile-test.am
Makefile.am
test/unit/dlopen-fail.c
tss2-dlopen/tss2-dlopen-esys.c
tss2-dlopen/tss2-dlopen-fapi.c
tss2-dlopen/tss2-dlopen-mu.c
tss2-dlopen/tss2-dlopen-rc.c
tss2-dlopen/tss2-dlopen-tctildr.c

Add a tss2-dlopen-esys that can be copied into project that do not want to link against libtss2-esys at compile time.
Same for tctildr, mu, rc and fapi.
Also added tests for esys, mu, rc, fapi and failure.

Add tss2-dlopen-esys.c

---

.cirrus.yml
.lgtm.yml
Makefile-test.am
Makefile.am
configure.ac
include/tss2/tss2_tcti_libtpms.h
lib/tss2-tcti-libtpms.def
lib/tss2-tcti-libtpms.map
lib/tss2-tcti-libtpms.pc.in
man/Tss2_Tcti_Libtpms_Init.3.in
man/tss2-tcti-libtpms.7.in
src/tss2-tcti/tcti-libtpms.c
src/tss2-tcti/tcti-libtpms.h
test/integration/sys-nv-policy-locality.int.c
test/unit/tcti-libtpms.c

Add `tcti-libtpms`. As of now, localities and pollhandles are not implemented. While the TPM state is unique to the tcti context, it cannot be shared across processes.

Add tct-libtpms

---

Makefile-test.am
Makefile.am
configure.ac

All of the tpm2-software projects that need libcrypto, the configure.ac check
using PKG_CHECK_MODULES uses "CRYPTO" except the tss project which uses
LIBCRYPTO. This means that when exporting variables for building against a
custom libcrypto, the variables will be LIBCRYPTO_CFLAGS and LIBCRYPTO_LIBS,
where as all the other projects are just CRYPTO_CFLAGS and CRYPTO_LIBS. Unify
this by changing it to CRYPTO.

configure: change LIBCRYPTO to CRYPTO

---

Makefile-test.am

#2156 accidentally removed the include directory from `TEST_CFLAGS` (due to a conflict when rebasing), leading to a [build failure](https://github.com/tpm2-software/tpm2-tss/runs/3730707245#step:3:1526):
```
../tss2-dlopen/tss2-dlopen-rc.c:21:10: fatal error: tss2/tss2_rc.h: No such file or directory
#include <tss2/tss2_rc.h>
^~~~~~~~~~~~~~~~
compilation terminated.
```

Makefile-test.am: re-add accidentally removed directory to TEST_CFLAGS

---

configure.ac

Autodetection of tpm_library for tcti-libtpms did not work correctly.
PR #2165 did not work.
Here's my attempt at fixing...

Build: Fix auto-detection of tcti-libtpms

---

Makefile-test.am
test/unit/tcti-pcap.c
test/unit/tctildr-dl.c

For some reason wrapping clock_gettime doesn't work with musl on 32 bit systems, but wrapping __clock_gettime64 does.
Tested (via alpine linux aports CI) on x86, x86_64, armv7, armhf, aarch64 and ppc64le.
Also tested on my laptop running debian unstable x86_64, but I haven't been able to test it on 32 bit systems using glibc.
Edit: added the same type of fix for dlsym, with the same level of testing, which fixes https://github.com/tpm2-software/tpm2-tss/issues/1808

test: add wrapper fix for musl on 32 bit systems

---

src/tss2-tcti/tcti-device.c

In Tss2_Tcti_Device_Init function, the file descriptor will be leaked when it fails.

Fix file descriptor leak when tcti initialization failed

---

test/integration/test-fapi.h

When JSO_STRING is found in LIST, it enters the branch i >= n. But json2 has been freed in for loop, it invokes double free. So when i >=n, I think json_object_put(jso2) should be deleted.

fix the double free problem in CHECK_JSON_LIST

---

src/tss2-tcti/tcti-device.c

tcti: Fix file descriptor leak when tcti initialization failed(3.1.x)

---

src/tss2-fapi/ifapi_policy.h

ifapi_policy.h and fapi_policy.h cyclically are cyclically dependent on each other.

FAPI: Header file circular dependency

---

man/tss2-tcti-swtpm.7.in

Per the discussion in bug #918, add the virtual tpm driver example and
discourage use of the CUSE interface.
Fixes: https://github.com/tpm2-software/tpm2-tss/issues/1918

man: add vtpm example in tss2-tcti-swtpm

---

src/tss2-fapi/fapi_crypto.c

A leak in the case "out of memory" detected by scan-build was fixed.

FAPI: Fix leak in fapi crypto with ossl3

---

test/integration/fapi-key-create-primary-sign.int.c

The auth value for the storage hierarchy was set in provisioning but not reset at
the end of the test fapi-key-create-primary-sign.

FAPI TEST: Auth value for storage hierarchy was not reset 3.1.x.

---

test/integration/fapi-key-create-primary-sign.int.c

The auth value for the storage hierarchy was set in provisioning but not reset at
the end of the test fapi-key-create-primary-sign.

FAPI TEST: Auth value for storage hierarchy was not reset 3.0.x.

---

test/integration/fapi-key-create-primary-sign.int.c

The auth value for the storage hierarchy was set in provisioning but not reset at
the end of the test fapi-key-create-primary-sign.

FAPI TEST: Auth value for storage hierarchy was not reset.

---

Makefile.am
configure.ac

Busybox does not support usseradd and groupadd. So for systems with busybox
(e.g. Alpine Linux) adduser and addgroup have to be used for FAPI configuration.

configure: Check system with busybox.

---

test/integration/fapi-pcr-test.int.c

The check whether a valid result did occur was fixed.

FAPI Tests: Fix check of test results in fapi-pcr-test 3.1.x.

---

test/integration/fapi-pcr-test.int.c

The check whether a valid result did occur was fixed.

FAPI Tests: Fix check of test results in fapi-pcr-test 3.0.x.

---

test/integration/fapi-pcr-test.int.c

The check whether a valid result did occur was fixed.

FAPI Tests: Fix check of test results in fapi-pcr-test.

---

test/integration/esys-get-capability-act.int.c

The integration test esys-get-capability-act must check the error value if this capability
does not exist. Fixes #2232

ESYS Tests: Check whether capability TPM2_CAP_ACT exists.

---

Makefile.am
include/tss2/tss2_mu.h
include/tss2/tss2_tpm2_types.h

Deprecate the type TPMS_ALGORITHM_DESCRIPTION as well as its
coresponding MU routines.
Fixes: #2228

tss2_tpm2_types: deprecate TPMS_ALGORITHM_DESCRIPTION

---

src/tss2-tcti/tcti-mssim.c
src/tss2-tcti/tcti-mssim.h
src/tss2-tcti/tcti-swtpm.c
src/tss2-tcti/tcti-swtpm.h
src/util/io.c
src/util/io.h
test/unit/io.c
test/unit/tcti-mssim.c
test/unit/tcti-swtpm.c

socket_connect() provides TCP, so we add socket_connect_unix() for unix
domain sockets, which takes 'path' rather than 'host'+'port'.
The convention for data/control pairs of sockets with TCP is that they use
a common hostname and consecutive port numbers. This patch adds a
'control' parameter to both API functions, and updates existing callers of
socket_connect() to provide it. Calls to create control sockets no longer
increment the port number caller-side, it is incremented within the
implementation instead. For the socket_connect_unix() case, the control
socket is implemented by appending ".ctrl" to the path.
Signed-off-by: Geoff Thorpe <geoffrey@twosigma.com>

tcti: support swtpm and mssim running over unix domain sockets

---

test/integration/fapi-key-create-sign.int.c
test/integration/fapi-key-create2-sign.int.c

In fapi-key-create2-sign.int.c and fapi-key-create-sign.int.c, when test_fapi_key_create_sign and test_fapi_key_create_sign fails, it will go to “error” to exit.  the certifacate needs to free.

FAPI: Free certificate when failed

---

.ci/docker.run
.github/workflows/main.yml
src/tss2-esys/esys_crypto.c
src/tss2-tcti/tcti-libtpms.c

* esys: Mark variable only used for logging maybe-unused.
* tcti: Mark variables only used for logging maybe-unused.
* ci: Set fetch-depth to 0 fot github actions.
* ci: Check whether sanitizer libs are available.

Fix errors if log is disabled and check availability of sanitizer

---

src/tss2-tcti/tctildr-dl.c

TCTI: Remove the redundant type conversions in info_from_name

---

src/tss2-esys/esys_tr.c

A segfault was produced in this case. Fixes #2243.

esys: Return an error if ESYS_TR_NONE is passed to Esys_TR_GetName.

---

test/integration/fapi-key-create-sign.int.c
test/integration/fapi-key-create2-sign.int.c

In fapi-key-create2-sign.int.c and fapi-key-create-sign.int.c, when test_fapi_key_create_sign and test_fapi_key_create_sign fails, it will go to “error” to exit. the certifacate needs to free.

FAPI: Free certificate when failed 3.1.x

---

src/tss2-fapi/ifapi_io.c

The input stream in ifapi_io_read_async was closed twice.

fapi: Fix close of stream twice.

---

test/integration/fapi-key-create-sign.int.c

In fapi-key-create-sign.int.c, when test_fapi_key_create_sign and test_fapi_key_create_sign fails, it will go to “error” to exit. the certifacate needs to free.

FAPI: Free certificate when failed 3.0.x

---

src/tss2-esys/esys_tr.c

A segfault was produced in this case. Fixes #2243.

esys: Return an error if ESYS_TR_NONE is passed to Esys_TR_GetName 3.0.x

---

src/tss2-esys/esys_tr.c

A segfault was produced in this case. Fixes #2243.

esys: Return an error if ESYS_TR_NONE is passed to Esys_TR_GetName. 3.1.x

---

Makefile-test.am
src/tss2-fapi/api/Fapi_Import.c
src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_helpers.c
src/tss2-fapi/ifapi_helpers.h
src/tss2-fapi/ifapi_json_deserialize.c
src/tss2-fapi/ifapi_keystore.c
src/tss2-fapi/ifapi_keystore.h
src/tss2-fapi/ifapi_policy_callbacks.c
test/integration/fapi-export-policy.int.c
test/integration/fapi-key-create-he-sign.int.c
test/integration/fapi-key-create-sign-password-provision.int.c
test/unit/fapi-json.c

The default policy "policy secret" for the endorsement key is defined for the
endorsement hierarchy. The corresponding object had to be searched in the
keystore during policy execution. This search did not work, due to various
bugs.
* A erroneous cleanup of the EK was executed where the policy was deleted.
* The name needed for the search in the keystore was not stored in the
hierarchy object.
* The esys handle stored in the hierarchy object was not correct.
To ensure compatibility with existing system keystores the initialization
of the hierarchy objects was fixed as follows:
* The initialization of the hierarchy object was moved to to object
deserialization.
* Depending on the pathname the esys handle in the hierarchy initialized.
* The name of the hierarchy object was computed.
* The …

FAPI: Fix the authorization of hierarchy objects.

---

src/tss2-fapi/api/Fapi_VerifyQuote.c
test/integration/fapi-quote.int.c

* It was not checked whether the qualifying data is equal to the extraData
field in the quoteInfo.
* An integration test was extanded to check also invalid qualifying data.
Fixes #2255

FAPI: Fix check of qualifying data in Fapi_VerifyQuote

---

src/tss2-fapi/api/Fapi_GetEsysBlob.c
src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_keystore.c
test/integration/fapi-key-create-policy-nv-sign.int.c

1. In ifapi_get_certificates, when ifapi_keystore_load_async or ifapi_keystore_load_finish or ifapi_initialize_object failed, it leads to leak memory that is allocated for context->cmd.Provision.nvPublic.
2. In keystore_search_obj, object may be leak when ifapi_keystore_load_finish failed.
3. command->data may be leak when Fapi_GetEsysBlob_Finish failed. Because when it successed, *data =  command->data .
4. In test_fapi_key_create_policy_nv_sign, when Fapi_List_Finish failed, Fapi_List will failed and pathlist may be leaked.

Fixed some memory leak in FAPI

---

Makefile-test.am
src/tss2-fapi/api/Fapi_Import.c
src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_helpers.c
src/tss2-fapi/ifapi_helpers.h
src/tss2-fapi/ifapi_json_deserialize.c
src/tss2-fapi/ifapi_keystore.c
src/tss2-fapi/ifapi_keystore.h
src/tss2-fapi/ifapi_policy_callbacks.c
test/integration/fapi-key-create-he-sign.int.c
test/integration/fapi-key-create-sign-password-provision.int.c

The default policy "policy secret" for the endorsement key is defined for the
endorsement hierarchy. The corresponding object had to be searched in the
keystore during policy execution. This search did not work, due to various
bugs.
* A erroneous cleanup of the EK was executed where the policy was deleted.
* The name needed for the search in the keystore was not stored in the
hierarchy object.
* The esys handle stored in the hierarchy object was not correct.
To ensure compatibility with existing system keystores the initialization
of the hierarchy objects was fixed as follows:
* The initialization of the hierarchy object was moved to to object
deserialization.
* Depending on the pathname the esys handle in the hierarchy initialized.
* The name of the hierarchy object was computed.
* The …

FAPI: Fix the authorization of hierarchy objects. 3.0.x

---

src/tss2-fapi/api/Fapi_Delete.c
src/tss2-fapi/api/Fapi_GetEsysBlob.c
src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_keystore.c
test/integration/fapi-key-create-policy-nv-sign.int.c

1. In ifapi_get_certificates, when ifapi_keystore_load_async or ifapi_keystore_load_finish or ifapi_initialize_object failed, it leads to leak memory that is allocated for context->cmd.Provision.nvPublic.
2. In keystore_search_obj, object may be leak when ifapi_keystore_load_finish failed.
3. command->data may be leak when Fapi_GetEsysBlob_Finish failed. Because when it successed, *data = command->data .
4. In test_fapi_key_create_policy_nv_sign, when Fapi_List_Finish failed, Fapi_List will failed and pathlist may be leaked.
5. Clean up memory when Fapi_Delete_Async failed.
6. Clean up memory when Fapi_GetEsysBlob_Async failed

Fapi fix some leaks 3.0.x

---

Makefile-test.am
src/tss2-fapi/api/Fapi_Import.c
src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_helpers.c
src/tss2-fapi/ifapi_helpers.h
src/tss2-fapi/ifapi_json_deserialize.c
src/tss2-fapi/ifapi_keystore.c
src/tss2-fapi/ifapi_keystore.h
src/tss2-fapi/ifapi_policy_callbacks.c
test/integration/fapi-export-policy.int.c
test/integration/fapi-key-create-he-sign.int.c
test/integration/fapi-key-create-sign-password-provision.int.c
test/unit/fapi-json.c

The default policy "policy secret" for the endorsement key is defined for the
endorsement hierarchy. The corresponding object had to be searched in the
keystore during policy execution. This search did not work, due to various
bugs.
* A erroneous cleanup of the EK was executed where the policy was deleted.
* The name needed for the search in the keystore was not stored in the
hierarchy object.
* The esys handle stored in the hierarchy object was not correct.
To ensure compatibility with existing system keystores the initialization
of the hierarchy objects was fixed as follows:
* The initialization of the hierarchy object was moved to to object
deserialization.
* Depending on the pathname the esys handle in the hierarchy initialized.
* The name of the hierarchy object was computed.
* The …

FAPI: Fix the authorization of hierarchy objects 3.1.x.

---

src/tss2-fapi/api/Fapi_Delete.c
src/tss2-fapi/api/Fapi_GetEsysBlob.c
src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_keystore.c
test/integration/fapi-key-create-policy-nv-sign.int.c

1. In ifapi_get_certificates, when ifapi_keystore_load_async or ifapi_keystore_load_finish or ifapi_initialize_object failed, it leads to leak memory that is allocated for context->cmd.Provision.nvPublic.
2. In keystore_search_obj, object may be leak when ifapi_keystore_load_finish failed.
3. command->data may be leak when Fapi_GetEsysBlob_Finish failed. Because when it successed, *data = command->data .
4. In test_fapi_key_create_policy_nv_sign, when Fapi_List_Finish failed, Fapi_List will failed and pathlist may be leaked.
5. Clean up memory when Fapi_Delete_Async failed
6. Clean up memory when Fapi_GetEsysBlob_Async failed

Fapi fix some leaks 3.1.x

---

src/tss2-fapi/ifapi_keystore.c

For an empty keystore a cleanup of an uninitialized object was executed. No the object
type now is initialized with IFAPI_OBJ_NONE to prevent the cleanup.

FAPI: Initialize object used for keystore search.

---

src/tss2-fapi/ifapi_keystore.c

For an empty keystore a cleanup of an uninitialized object was executed. No the object
type now is initialized with IFAPI_OBJ_NONE to prevent the cleanup.

FAPI: Initialize object used for keystore search 3.1.x.

---

src/tss2-fapi/ifapi_keystore.c

For an empty keystore a cleanup of an uninitialized object was executed. No the object
type now is initialized with IFAPI_OBJ_NONE to prevent the cleanup.

FAPI: Initialize object used for keystore search 3.0.x.

---

src/tss2-esys/esys_crypto_ossl.c
src/tss2-fapi/fapi_crypto.c
test/integration/sys-util.c

Use also OPENSSL_NO_SM3 to check whether SM3 is available and the correct library is used.
Fixes #2287.

ossl: Fix check whether SM3 is available

---

git.mk

With out-of-tree builds with read only source directory the
generation of .gitignore failed the build.
Update it to issue a warning and continue.
Taken from upstream.
Fixes: #2271

Build: Update git.mk to support R/O src-dir

---

src/tss2-fapi/ifapi_helpers.c

- The third argument of [`curl_url_set`](https://curl.se/libcurl/c/curl_url_set.html) is of type `const char *`, leading to the following compiler warning/error with GCC 11.2.0 and curl 7.81.0:
```C
rc/tss2-fapi/ifapi_helpers.c:2529:44: error: pointer targets in passing argument 3 of 'curl_url_set' differ in signedness [-Werror=pointer-sign]
2529 |     rc = curl_url_set(urlp, CURLUPART_URL, url, CURLU_ALLOW_SPACE | CURLU_URLENCODE);
|                                            ^~~
|                                            |
|                                            unsigned char *
/usr/include/curl/urlapi.h:132:48: note: expected 'const char *' but argument is of type 'unsigned char *'
132 |                                    const char *part, unsigned int flags);
|  
```
- The …

FAPI: fix curl_url_set call

---

Makefile.am

The files in a release tarball should not depend on whether the corresponding feature was enabled on the system or not when cutting the release, since this will break the feature on all systems building from that tarball. Therefore move all `EXTRA_DIST` instructions out of conditionals to the top level, which is possible since all of these are static, non-generated files anyway.
References: #2313

Makefile.am: make all EXTRA_DIST includes unconditional

---

Makefile-test.am

Makefile-test.am: use $(JSONC_LIBS) over -libjson-c

---

.cirrus.yml

Fixes CI Error:
pkg update -f
Updating FreeBSD repository catalogue...
Fetching meta.conf: . done
Fetching packagesite.pkg: .......... done
Processing entries:
Newer FreeBSD version for package php74-pear-channel-pirum:
To ignore this error set IGNORE_OSVERSION=yes
- package: 1203000
- running kernel: 1202000
Ignore the mismatch and continue? [y/N]: pkg: repository FreeBSD contains packages for wrong OS version: FreeBSD:12:amd64
Processing entries... done
Unable to update repository FreeBSD
Error updating repositories!
Seems as though 12-2 is EOL so update to something newer.
Related to:
- https://forums.freebsd.org/threads/pkg-repository-freebsd-contains-packages-for-wrong-os-version-freebsd-12-amd64.78856/
- http://soulrace.top:3000/mirror_group/curl/commit/7db6bc5ecaef321f32639149ba3737 …

cirrus: update to FreeBSD 13-0

---

src/tss2-esys/esys_tr.c

When the provided value of  esys_handle is ESYS_TR_NONE the call to esys_GetResourceObject will set esys_object to NULL, which get dereferenced below.
We mitigate the issue by returning TSS2_ESYS_RC_BAD_TR when the handle value is ESYS_TR_NONE

Fixing an issue when Null deref occures in Esys_TR_SetAuth

---

configure.ac

Only check for useradd/adduser and groupadd/addgroup when
systemd_sysusers is not present on the system.

Conditionally check for user/group manipulation commands

---

Makefile.am
bootstrap
configure.ac

This way autoreconf can still be run on release tarballs (e.g. to apply patches to the build system) while preserving the version number. The tpm2-abrmd already uses this approach.
Fixes: #2329

Store VERSION into the release tarball (3.2.x)

---

Makefile.am
bootstrap
configure.ac

This way autoreconf can still be run on release tarballs (e.g. to apply patches to the build system) while preserving the version number. The tpm2-abrmd already uses this approach.
Fixes: #2329

Store VERSION into the release tarball

---

MAINTAINERS

New address is: juergen_repp@web.de

MAINTAINERS: Change e-mail address Juergen

---

test/integration/policy-execute.int.c
test/unit/tss2_policy.c

Check whether `fread` was able to read the complete file and fail with an assertion if not. This fixes the following warnings/errors when building with GCC 12.1.0:
```C
test/integration/policy-execute.int.c: In function 'read_all':
test/integration/policy-execute.int.c:73:5: error: ignoring return value of 'fread' declared with attribute 'warn_unused_result' [-Werror=unused-result]
73 |     fread(buffer, fsize, 1, f);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~
```
```C
test/unit/tss2_policy.c: In function 'read_all':
test/unit/tss2_policy.c:53:5: error: ignoring return value of 'fread' declared with attribute 'warn_unused_result' [-Werror=unused-result]
53 |     fread(buffer, fsize, 1, f);
|     ^~~~~~~~~~~~~~~~~~~~~~~~~~
CC       test/integration/sys_asymmetric_encrypt_decrypt_int-sys-asymmetric-en …
```

test: check return value of fread

---

src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_json_deserialize.c
src/tss2-fapi/ifapi_json_serialize.c
src/tss2-fapi/ifapi_keystore.h

Currently only CreationData and CreationHash were stored in the FAPI keystore.
Creation hash is now added to provide the possibility for the tpm2 tool command
tss2_gettpm2object to extract also CreationData, CreationTicket, and CreationHash.
Also the initialization of cretionTicket during deserialization was fixed.
Addresses #2360

FAPI: Add CreationHash to keystore

---

.ci/docker.run
Makefile.am

* If DESTDIR is defined to create a staging installation  systemd-sysusers and systemd-tmpfiles
should not be called.
* The directories defined by --with-sysusersdir and --with-tmpfilesdir have to be used for the
corresponding systemd commands.
* If DESTDIR is provided and systemd-tmpfiles is available the eventlog and keystore directory
will be created under DESTDIR but the owner will not be changed.
Fixes #2344

Makefile: Fix usage of DESTDIR for make install

---

.ci/docker-prelude.sh
.ci/docker.run
.github/workflows/main.yml

* lcov ist not available for alpine. Thus compiling with --enabable-coverage will
only used for the action test-coverage.
* To test version of mbedtls 3.1 thei image ubuntu-22.04-mbedtls-3.1 was added.

ci: add alpine 3.15 and ubuntu-22.04-mbedtls-3.1

---

src/tss2-esys/esys_iutil.c

Clang-10 scan-build reports:
src/tss2-esys/esys_iutil.c:1366:56: warning: Dereference of null pointer
auths->auths[auths->count].sessionHandle = session->rsrc.handle;
^~~~~~~~~~~~~~~~~~~~
1 warning generated.
The code above the report checks that session might be NULL:
RSRC_NODE_T *session = esys_context->session_tab[session_idx];
if (session != NULL) {
IESYS_SESSION *rsrc_session = &session->rsrc.misc.rsrc_session;
if (rsrc_session->type_policy_session == POLICY_PASSWORD) {
Thus suggesting/indicating session may be NULL in subsequent code where
session is dereferenced.

esys_iutil: fix possible NPD

---

src/tss2-sys/sysapi_util.c

Fixes #2382 
The lookup table for the number of command handles for
Tss2_Sys_FlushContext has the count set to 1, when in reality the
command takes no handles in the handle area but a handle as the input
parameter. This works currently because handles and parameters are just
concatenated and the parsing logic on the TPM just unpacks them, so in
this case, thet're in the same spot with the same value. This goes
unnoticed until you call Tss2_Sys_GetCpBuffer and the buffer is empty as
the logic things its a handle in the handle area and not a handle in the
parameter area.

SAPI: fix number of handles for FlushContext

---

Makefile-test.am
Makefile.am
include/tss2/tss2_policy.h
src/tss2-fapi/fapi_int.h
src/tss2-fapi/ifapi_policy_callbacks.c
src/tss2-fapi/ifapi_policy_callbacks.h
src/tss2-fapi/ifapi_policy_instantiate.c
test/data/fapi/policy/pol_nv_tpm_idx.json
test/integration/fapi-key-create-policy-nv-sign.int.c
test/unit/tss2_policy.c

* Currently it was not possible to define a policy nv with a TPM nv index.
The callback to get the public nv data related to the policy was extended
to get public nv data from the TPM in this case.
Addresses #2383
* Also an integration test was added.

fapi: fix usage of policy_nv.

---

Makefile.am
test/data/fapi/policy/pol_ek_high_range_sha256.json
test/data/test-fapi-policies.h
test/integration/policy-execute.int.c

* TCG EK Credential Profile TPM 2.0, Version 2.4 Rev. 3, 2021 defines policies
for the low and high address range of EK templates.
* A policy for a high range template with sha256 was added to the test policies
and The policy digests for policy A, B, and C defined in the profile were computed
in the integration test for Fapi_PolicyExport.
* This policy could be used in a FAPI profile as "ek_policy".

FAPI: Add an integration test for a high range EK policy.

---

doc/doxygen.dox

Fixes:
/home/wcrobert/workspace/tpm2-tss/doc/doxygen.dox:1024: warning: documented symbol 'TSS2_RC iesys_cryptossl_hash_update2b' was not declared or defined.
/home/wcrobert/workspace/tpm2-tss/doc/doxygen.dox:1026: warning: documented symbol 'TSS2_RC iesys_cryptossl_hash_finish2b' was not declared or defined.
/home/wcrobert/workspace/tpm2-tss/doc/doxygen.dox:1029: warning: documented symbol 'TSS2_RC iesys_cryptossl_hmac_start2b' was not declared or defined.
/home/wcrobert/workspace/tpm2-tss/doc/doxygen.dox:1031: warning: documented symbol 'TSS2_RC iesys_cryptossl_hmac_update2b' was not declared or defined.
/home/wcrobert/workspace/tpm2-tss/doc/doxygen.dox:1033: warning: documented symbol 'TSS2_RC iesys_cryptossl_hmac_finish2b' was not declared or defined. …

doxygen: fix warns on doc symbol was not defined

---

include/tss2/tss2_policy.h
src/tss2-fapi/ifapi_helpers.c
src/tss2-fapi/ifapi_helpers.h
src/tss2-fapi/ifapi_policy_calculate.c
src/tss2-fapi/ifapi_policy_callbacks.c
src/tss2-fapi/ifapi_policy_callbacks.h
src/tss2-fapi/ifapi_policy_instantiate.c
src/tss2-fapi/ifapi_policy_json_deserialize.c
src/tss2-fapi/ifapi_policy_json_serialize.c
src/tss2-fapi/ifapi_policy_types.h
test/unit/tss2_policy.c

Rather then using types like TPM2B_NV_PUBLIC just use the TPMS_NV_PUBLIC
since the size field is never needed. Keep the ondisk representation
in JSON going through the same routines and convert between the two
types this way we don't break on disk representation of existin objects.
Fixes: #2383

policy: drop complex TPM2B from callback interface

---

Makefile-test.am

When building tpm2-tss with slibtool instead of GNU libtool the build will fail during 'make check'. This happens because there is an extra erroneous comma which is then passed to gcc causing it to fail to find a non-existent file. With GNU libtool it appears that the comma is silently removed while slibtool does not do this.
```
rdlibtool --tag=CC --mode=link gcc -I./src -I./include/tss2 -I./test/fuzz/tcti -std=c99 -Wall -Wextra -Wformat-security -Werror -fstack-protector-all -fpic -fPIC -Wno-missing-braces -Wstrict-overflow=5 -DINTERNALBUILD=1 -I./include -I./src/tss2-mu -I./src/tss2-sys -I./src/tss2-esys -I./src/tss2-fapi -I./test/data -Wno-unused-parameter -Wno-missing-field-initializers -DTOP_SOURCEDIR="." -DTOP_SOURCEDIR="." -g -Wl,--wrap=read -Wl,--wrap=write, -Wl,--wrap=poll …
```

build: Remove erroneous comma

---

include/tss2/tss2_policy.h
src/tss2-fapi/ifapi_policy_execute.c
src/tss2-rc/tss2_rc.c
test/unit/test_tss2_rc.c

TSS2_BASE_RC_NULL_CALLBACK is not defined, FAPI uses TSS2_BASE_RC_CALLBACK_NULL so use that
Fix two cases where the wrong callback/userdata is used and add support for decoding policy return codes

policy: use correct base RC for NULL callback

---

src/tss2-esys/esys_int.h
src/tss2-esys/esys_tr.c
test/integration/esys-tr-fromTpmPublic-nv.int.c

The ESAPI spec states that it must be possible to use HMAC sessions
for Esys_TR_FromTPMPublic.
Currently it was not implemented to call Esys_TR_FromPublic twice.
The first call has to be used to determine the object name which
will be used to compute the HMAC of the session.
If the esys object already exists the existing object will be used.
If a session is used in this case the name retrieved from the
TPM will be compared with name stored in the object.
The integration test for the test with Esys_TR_FromTPMPublic was
extended to add a call with a HMAC session.
Addresses: #2171

esys: fix usage of HMAC sessions for Esys_TR_FromTPMPublic

---

src/tss2-esys/esys_int.h
src/tss2-esys/esys_tr.c
test/integration/esys-tr-fromTpmPublic-nv.int.c

The ESAPI spec states that it must be possible to use HMAC sessions
for Esys_TR_FromTPMPublic.
Currently it was not implemented to call Esys_TR_FromPublic twice.
The first call has to be used to determine the object name which
will be used to compute the HMAC of the session.
If the esys object already exists the existing object will be used.
If a session is used in this case the name retrieved from the
TPM will be compared with name stored in the object.
The integration test for the test with Esys_TR_FromTPMPublic was
extended to add a call with a HMAC session.
Addresses: #2171

esys: fix usage of HMAC sessions for Esys_TR_FromTPMPublic (3.2.x)

---

src/tss2-fapi/fapi_crypto.c

Currently the number of curves not implemented are displaye as
hex number but not marked with 0x.
Integers are used in the corresponding openssl h file.
To make debugging easier the curve number now is displayed as
integer.

fapi: improve error message curve not implemented.

---

src/tss2-esys/api/Esys_Commit.c
src/tss2-esys/api/Esys_EC_Ephemeral.c
src/tss2-esys/api/Esys_GetCapability.c
src/tss2-esys/api/Esys_GetTestResult.c
src/tss2-esys/api/Esys_PCR_Allocate.c
src/tss2-esys/api/Esys_PCR_Read.c
src/tss2-tcti/tcti-swtpm.c

Several [out] pointers are described in the comments as
"callee-allocated" but this seems incorrect - they would need to be
pointers to pointers to be callee-allocated. This removes the
"callee-allocated" notes from comments where they are incorrect.
Signed-off-by: Erik Bryan <erik.bryan@hp.com>

Correct [out] param documentation

---

test/integration/esys-clear.int.c

This aligns it with the other tests.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>

test: Skip esys-clear test if platform auth is not possible

---

src/tss2-mu/base-types.c
src/tss2-mu/tpm2b-types.c
src/tss2-mu/tpma-types.c

You can enabled this warnings on gcc/clang via -Wconversion. I guess do we want to enable this for libmu?

Tss2 mu precision fixes

---

include/tss2/tss2_esys.h

More or less copied the documentation from esys_crypto_ossl.c

esys: fix documentation for ESYS_CRYPTO_GET_ECDH_POINT_FNP

---

test/integration/policy-execute.int.c

The integration tests for the policylib failed when a physical TPM was used.
The tests should not fail if a policy is not available on the TPM.

test policylib: Fix error handling.

---

.cirrus.yml
test/unit/fapi-io.c

The unit test had a static FILE structure used to pass to stdio FILE * routines as a dummy value to indicate to use the __real_xxx variant of the mocked function. This doesn't work when FILE is opaque as the compiler cannot figure out how much storage space is needed for a FILE struct.
Fix this by passing a dummy pointer to a data type the compiler knows about and casting it to FILE pointer.
Fixes: #2419

test: fix usage of FILE in unit test fapi-io

---

include/tss2/tss2_rc.h
src/tss2-rc/tss2_rc.c
test/unit/test_tss2_rc.c

As discussed in https://github.com/tpm2-software/tpm2-tss/pull/2416 add format fields to users don't need to check the parameter, session and handle fields unless needed and ensure that the struct is initialized when decoding

rc: add format field to TSS2_RC_INFO and clear it when decoding

---

src/tss2-tcti/tcti-common.h
src/tss2-tcti/tctildr-dl.c
src/tss2-tcti/tctildr-nodl.c
src/tss2-tcti/tctildr.c
test/helper/tpm_cmd_tcti_dummy.c
test/unit/tcti-device.c
test/unit/tctildr-getinfo.c

tcti: drop unused inclusions of errno.h

---

Makefile.am
test/data/fapi/P_ECC384.json
test/integration/fapi-key-create-policy-pcr-sign.int.c

The profile P_ECC384 defined in PR #2418 was added. The ci tests failed for this test. The failed integration test was adapted to run with this additional profile.
The curveID TPM2_ECC_NIST_P384, the nameAlg SHA384, and the autpolicy according to the EK Template (TPMT_PUBLIC) H-2: ECC NIST P256 were used in the profile.

FAPI: Add test profile P_ECC384

---

src/tss2-fapi/ifapi_io.c
test/integration/fapi-key-create-policy-pcr-sign.int.c

`ifapi_io_dirfiles()` currently uses `readdir()` to list all the entries of a directory, which does not guarantee any particular ordering. This is a problem because some structures are dependent on the ordering of the profiles in the profile directory: e.g. [`Fapi_ExportPolicy()` loops over all profiles in the order that they have been added and extracts the hash algorithms from them](https://github.com/tpm2-software/tpm2-tss/blob/9288970a3e657cdee85d08d3813199ec864de3ad/src/tss2-fapi/api/Fapi_ExportPolicy.c#L263-L265). This means that the ordering of its JSON output depends on the ordering of the profiles array.
This problem surfaced with commit 67f72e4741b1d50d43d845c5a99fd976b4210f66 ("FAPI: Add profile P_ECC384"): it adds a new profile file for P_ECC384. Since it is a new file, many …

fapi: make ordering of search directories filesystem-independent

---

src/tss2-fapi/ifapi_io.c

Memory allocated by scandir when reading the fapi profile was not freed.
Should fix the failures in:
https://github.com/tpm2-software/tpm2-tools/pull/3144

FAPI: Fix memory leak caused by scandir.

---

test/integration/fapi-quote-destructive.int.c

Subsequent tests expect PCR 16 to be clear so clean up after setting it in the testcase.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>

fapi/tests: Clear PCR 16 after setting it

---

src/tss2-fapi/ifapi_profiles.c

The usage of a second profile in a path was not possible because allways the default profile was used.
So after a second provisioning with a second fapi config file this profile could not be uses in fapi pathnames.

FAPI: Fix usage of second profile in path 3.2.x

---

src/tss2-fapi/ifapi_profiles.c

The usage of a second profile in a path was not possible because allways the default profile was used.
So after a second provisioning with a second fapi config file this profile could not be uses in fapi pathnames.

FAPI: Fix usage of second profile in path.

---

src/tss2-fapi/ifapi_policy_callbacks.c
src/tss2-fapi/ifapi_policy_json_deserialize.c
src/tss2-fapi/ifapi_policy_json_serialize.c
src/tss2-fapi/ifapi_policy_types.h

The current implementation did use the field keyPEMhashAlg in the structure TPMS_POLICYAUTHORIZATION instead of hashAlg as defined in "TCG TSS 2.0 JSON Data Types and Policy Language Specification". Also in the JSON represention keyPEMhashAlg was used instead of hashAlg. To achieve backward compatibility keyPEMhashAlg is still allowed.

FAPI: Fix deviation from spec.

---

Makefile.am
test/data/fapi/P_ECC_sh_eh_policy_sha384.json
test/data/fapi/policy/pol_authorize_ecc_pem_sha384.json
test/data/fapi/policy/pol_authorize_nv_complex_tpm2b_sha384.json
test/data/fapi/policy/pol_authorize_nv_sha384.json
test/data/fapi/policy/pol_authorize_nv_tpms_sha384.json
test/data/fapi/policy/pol_cphash_sha384.json
test/data/fapi/policy/pol_pcr16_0_ecc_authorized_sha384.json
test/integration/fapi-key-create-he-sign.int.c
test/integration/fapi-key-create-policy-authorize-nv-sign.int.c
test/integration/fapi-key-create-policy-authorize-pem-sign.int.c
test/integration/fapi-key-create-policy-pcr-sign.int.c
test/integration/fapi-nv-authorizenv-cphash.int.c
test/integration/fapi-nv-extend.int.c
test/integration/fapi-second-provisioning.int.c

* Usage of NIST P-384 ECC keys was prepared by: #2418 .
* The integration tests now were adapted to enable the running with
A device provisioned with an ECC-384 EK instead of ECC-256.
* Several policies appropriate for the P_ECC384 were added.
* If necessary it's checked what policy has to be used depending
on the profile.
* If e.g The device is provisioned with swtpm-setup and an EK
certificate for ECC NIST P-384 is produced, the integration
test with the device can be configured  as follows:
```
configure --enable-integration --enable-unit
--with-device=/dev/tpm0  \
--with-default-test-fapi-profile=P_ECC384 \
--enable-self-generated-certificate```
* Before running the test the test certificates from swtpm must be assigned:
`export …

FAPI: Enable usage of profile P_ECC384 for integration test.

---

include/tss2/tss2_rc.h
lib/tss2-rc.def
lib/tss2-rc.map
src/tss2-rc/tss2_rc.c
test/unit/test_tss2_rc.c

As discussed in https://github.com/tpm2-software/tpm2-tss/pull/2416 this adds a method to get the "raw" error message without any layers or any of the parameters, handles or sessions.

rc: add function to get a human readable error message from TSS2_RC_INFO

---

include/tss2/tss2_tpm2_types.h

Missing TPM2_ prefix for HR_SHIFT, so add it
Fixes tpm2-pytss builds against tpm2-tss master

types: fix define for TPM2_HR_NV_AC

---

src/tss2-fapi/ifapi_policy_callbacks.c
src/tss2-fapi/ifapi_policy_callbacks.h
src/tss2-fapi/ifapi_policy_execute.c
src/tss2-fapi/ifapi_policy_execute.h

The authorization did not work when key objects were used as secret. The current object to be authorized was overwritten by the secret object. To fix this problem backups of the objects to be authorized were stored in the policy stack. The loaded secret key is  flushed after policy execution if it's a transient key.
Fixes #2448.

FAPI: Fix policy secret.

---

src/tss2-tcti/tctildr.h

tctildr.h: drop extra tcti_from_info declaration

---

dist/tpm-udev.rules

Requiring user to be tss doesn't really add a whole lot, the root user should be able to use the interface as well.
Fixes: #2292

dist/tpm-udev.rules: drop owner root from tpmrm*

---

Makefile-test.am
Makefile.am
src/tss2-fapi/api/Fapi_Sign.c
src/tss2-fapi/fapi_int.h
src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_policy_callbacks.c
src/tss2-fapi/ifapi_policy_callbacks.h
src/tss2-fapi/ifapi_policy_execute.c
test/data/fapi/policy/pol_secret_key.json
test/integration/fapi-key-create-policy-secret-key-sign.int.c

* The wrong context usage during key loading in the callback for object authorization was fixed.
* An integration test, also with testing wrong authentication was added.

FAPI: Fix loading of keys during policy execution

---

src/tss2-esys/api/Esys_HMAC_Start.c
src/tss2-esys/api/Esys_HierarchyChangeAuth.c
src/tss2-esys/api/Esys_MAC_Start.c
src/tss2-esys/api/Esys_NV_ChangeAuth.c
src/tss2-esys/api/Esys_NV_DefineSpace.c
src/tss2-esys/api/Esys_PCR_SetAuthValue.c
src/tss2-esys/esys_int.h
test/integration/esys-pcr-auth-value.int.c

- Simplification cleanups on how internal authValues we're stored in the ESAPI_CONTEXT
- Add support for Esys_PCR_SetAuthValue

Fix pcr setauthvalue

---

src/tss2-fapi/api/Fapi_ChangeAuth.c
src/tss2-fapi/fapi_int.h

For every profile there is a hierarchy object in keystore. After changing the auth value of one hierarchy with Fapi_ChangeAuth the information whether an auth value is used was only changed for the object of the default profile. Now the information is synchronized for all hierarchy objects in keystore.

FAPI: Fix hierarchy storage In Fapi_ChangeAuth

---

src/tss2-fapi/api/Fapi_Sign.c
src/tss2-fapi/fapi_int.h
src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_policy_callbacks.c
src/tss2-fapi/ifapi_policy_callbacks.h
src/tss2-fapi/ifapi_policy_execute.c
src/tss2-fapi/ifapi_policy_execute.h

The authorization did not work when key objects were used as secret. The current object to be authorized was overwritten by the secret object. To fix this problem backups of the objects to be authorized were stored in the policy stack. The loaded secret key is  flushed after policy execution if it's a transient key.
Fixes #2448.

FAPI: Fix policy secret 3.2.x.

---

src/tss2-fapi/api/Fapi_ChangeAuth.c
src/tss2-fapi/fapi_int.h

For every profile there is a hierarchy object in keystore. After changing the auth value of one hierarchy with Fapi_ChangeAuth the information whether an auth value is used was only changed for the object of the default profile. Now the information is synchronized for all hierarchy objects in keystore.

FAPI: Fix hierarchy storage In Fapi_ChangeAuth 3.2.x

---

src/tss2-esys/api/Esys_PCR_SetAuthValue.c

Use in.PCR not in.NV when getting the stored authValue. This worked, coincidentally, becuase the unions overlapped.

Esys_PCR_SetAuthValue: use correct union selection

---

src/tss2-fapi/ifapi_eventlog.c
src/tss2-fapi/ifapi_json_eventlog_serialize.c
src/tss2-fapi/ifapi_json_eventlog_serialize.h

CEL management and advisory only events were added to the event list although PCR0 was not selected.
Now these events will only be added if PCR0 is selected. Fixes: #2454

FAPI: Fix usage of management events in event list.

---

Makefile-test.am

Test was moved because a TPM clear was needed afterwards.

esys test: move test esys-pcr-auth-value.int to destructive tests.

---

Makefile-test.am

Test was moved because a TPM clear was needed afterwards.

esys test: move test esys-pcr-auth-value.int to destructive tests 3.2.x

---

.ci/docker.run
src/tss2-fapi/api/Fapi_ChangeAuth.c
src/tss2-fapi/api/Fapi_Sign.c
src/tss2-fapi/fapi_int.h
src/tss2-fapi/ifapi_policy_callbacks.c

* The check in docker.run whether libasan and libubsan are available
did not work. Thus the sanitizer was not used in the CI.
* All leaks which were not detected are now fixed.
* Fixes #2470.

CI: Fix usage of sanitizer 3.2.x.

---

src/tss2-esys/esys_crypto_mbed.c
test/unit/esys-crypto.c

* sha512 now is possible in iesys_cryptmbed_hash_start.
* The corresponding unit test was adapted.
Fixes: #2490

ESYS: Allow usage of sha512 for mbedtls.

---

src/tss2-fapi/ifapi_keystore.c

If the keystore contains invalid JSON data for an object a double free during the object cleanup occurs.
The corresponding value in the object is now set to NULL after the first free.

FAPI: Fix double free if keystore is corrupted.

---

Makefile-test.am

When configure time flags --disable-tcti-spi-helper and --enable-unit are used in conjunction, the unit tests for the spi tcti helper are built but the code is not, causing undefined references at link. Correct this by guarding the tests in AM conditionals based on if spi helper tcti is enabled.
Corrects Error:
/usr/bin/ld: test/unit/tcti_spi_helper-tcti-spi-helper.o: in function `tcti_spi_no_wait_state_success_test': /.../tpm2-tss/test/unit/tcti-spi-helper.c:215: undefined reference to `Tss2_Tcti_Spi_Helper_Init' /usr/bin/ld: /.../tpm2-tss/test/unit/tcti-spi-helper.c:224: undefined reference to `Tss2_Tcti_Spi_Helper_Init' /usr/bin/ld: test/unit/tcti_spi_helper-tcti-spi-helper.o: in function `tcti_spi_with_wait_state_success_test': /.../tpm2-tss/test/unit/tcti-spi-helper.c:244: undefined …

tests: rm tcti-spi-helper tests when not enabled

---

include/tss2/tss2_mu.h
include/tss2/tss2_tpm2_types.h
test/unit/TPML-marshal.c

CFFI doesn't like if !defined(xxx), update all the DISABLE_VENDOR calls and make the style consistent through the source for those macros only.
Fixes:
cffi.CDefError: cannot parse "#if !defined(DISABLE_VENDOR)" <cdef source string>:2193:2: before: if
[end of output]

headers: use ifndef over if !defined for CFFI

---

test/integration/fapi-key-create-policy-or-sign.int.c

Somewhere between 3.0.0 and 3.1.0 we fixed double free but, but we did not maintain commit atomicity and therfore my efforts to bisect were thwarted. I checked a few patches by hand and couldn't find the source of the fix. However, add a regression test.

test/fapi: test Fapi_SetBranchCB NULL

---

src/tss2-fapi/fapi_util.c

If no description exists Fapi_GetDescription returns NULL. The FAPI specification states:
If no description is present, description SHALL be set to an empty string.

FAPI: Fix deviation from specification in Fapi_GetDescription.

---

configure.ac
src/tss2-fapi/ifapi_curl.c

Fix undefined reference to curl_url_strerror for libcurl versions prior to 7.80.0, see:
- https://curl.se/libcurl/c/curl_url_strerror.html

fapi: fix curl curl_url_strerror not found error

---

Makefile.am
src/tss2-fapi/ifapi_policy_calculate.c
src/tss2-fapi/ifapi_policy_execute.c
src/tss2-fapi/ifapi_policy_json_deserialize.c
src/tss2-fapi/ifapi_policy_json_serialize.c
src/tss2-fapi/ifapi_policy_types.h
src/tss2-fapi/tpm_json_deserialize.c
test/data/fapi/policy/pol_template.json
test/data/test-fapi-policies.h

* The calculation and execution of PolicyTemplate was added.
* The policy unit tests was extended with an test for PolicyTemplate.
* The deserialization of TPMT_PUBLIC was simplified.
* Fixes #2509.

FAPI:  Add the policy PolicyTemplate

---

src/tss2-fapi/ifapi_curl.c

Add handling of the http return code to the downloading of the EK intermediate CA certificates.
Signed-off-by: Andreas Fuchs <andreas.fuchs@infineon.com>

FAPI: Add http return code handling

---

src/tss2-fapi/ifapi_policy_store.c

FAPI returns FAPI_RC_IO_ERROR if a policy does not exist in keystore. The Spec requires the return value FAPI_RC_BAD_PATH.

FAPI: Fix return value if policy does not exist.

---

src/tss2-tcti/tcti-mssim.c

The get_poll_handles function for the mssim TCTI returns a windows HANDLE object. Current code was returning a SOCKET which was an integer type. To fix this use an event HANDLE and set up the events to listen to.
Fixes: #2520
Signed-off-by: robedpixel <3531281-robedpixel@users.noreply.gitlab.com>

tcti: fix get_poll_handles for mssim TCTI

---

src/tss2-rc/tss2_rc.c
test/unit/test_tss2_rc.c

The commit (on 4.0.1 and master):
- 49107d65d5c7 tss2_rc: ensure layer number is in bounds
Introduces a bug where the right shift by 8 drops the lower byte going into the unknown_layer handler function. This will effectively drop rc error bits for unknown layers. The largest impact will be on windows where their resource manager is not a registered handler.
Fix this by just dumping all the bytes and not get fancy with masking things out.
Fixes: #2550

tss2-rc: fix unknown layer handler dropping bits

---

.cirrus.yml
.github/workflows/codeql.yml
INSTALL.md
Makefile-test.am
Makefile.am
configure.ac
doc/tcti-spi-lt2go.md
include/tss2/tss2_tcti_spi_lt2go.h
lib/tss2-tcti-spi-lt2go.def
lib/tss2-tcti-spi-lt2go.map
lib/tss2-tcti-spi-lt2go.pc.in
man/tss2-tcti-spi-lt2go.7.in
src/tss2-tcti/tcti-spi-helper.c
src/tss2-tcti/tcti-spi-lt2go.c
src/tss2-tcti/tcti-spi-lt2go.h
test/unit/tcti-spi-lt2go.c

Bringing up a TCTI module to support the LetsTrust-TPM2Go, a USB TPM from @PaulKissinger. It's a combined effort and resources are taken from:
- @PeterHuewe: https://github.com/PeterHuewe/tpm2-tss/tree/letstrust2go, https://github.com/PeterHuewe/tpm2-tss/tree/letstrust2go-wo-waitstates
- @tobyp: https://gist.github.com/tobyp/aed5598188088f4abbeb737b408e5287
The CI is expected to fail at this stage since the library `libusb-1.0-0-dev` is missing from the CI container image.

TCTI: Add USB TPM (LetsTrust-TPM2Go) TCTI module

---

configure.ac

Make support for tcti-spi-lt2go behave as tcti-libtpms in the sense that it should only be enabled by default if the dependencies are installed.

tcti: only enable tcti-spi-lt2go if libusb is installed

---

configure.ac

The tss build for the tpm tools on free bsd failed because the usb1.0 header file was not found but the check for the lib was ok.

tcti: Added libusb1.0 header test.

---

src/tss2-esys/esys_crypto_ossl.c
src/tss2-fapi/fapi_crypto.c

The NID_sm2 algorithm is not currently supported by LibreSSL which causes build failures. However instead of checking the OpenSSL version number it is possible to just check if NID_sm2 is defined instead. This way it will be automatically enabled when LibreSSL does support it and disabled in the event the OpenSSL stops supporting it.
LibreSSL issue: https://github.com/libressl/portable/issues/841
I am splitting this off from PR https://github.com/tpm2-software/tpm2-tss/pull/2380 since it is more general.

src: Check if NID_sm2 is defined

---

dist/fapi-profiles/P_ECCP256SHA256.json
dist/fapi-profiles/P_RSA2048SHA256.json
test/data/fapi/P_ECC.json
test/data/fapi/P_ECC_error.json
test/data/fapi/P_ECC_sh_eh_policy.json
test/data/fapi/P_ECC_system.json
test/data/fapi/P_RSA.json
test/data/fapi/P_RSA2.json
test/data/fapi/P_RSA_sh_policy.json

An unnecessary comma was used in the definition of the EK policy. The comma was ignored by json-c but did cause errors in other tools (e.g. jq).

FAPI: Fix json syntax in FAPI profiles.

---

src/tss2-mu/tpm2b-types.c
test/tpmclient/tpmclient.int.c

There is a size check for the destination object whether the size is zero. If the memory of the destination object is no cleared this might cause a race conditions.
Unneeded tests from the integration test tpmclient were removed. Fixes: #2564

MU: Fix unneeded size check in TPM2B unmarshaling

---

Makefile.am

tss2-tcti-swtpm.7 was added wrongly to EXTRA_DIST, which caused a build fail after make clean.
Fixes: #2557

Makefile: Add tss2-tcti-swtpm.7.in to EXTRA_DIST (3.2.x)

---

src/tss2-rc/tss2_rc.c
test/unit/test_tss2_rc.c

The commit (on 4.0.1 and master):
- 49107d65d5c7 tss2_rc: ensure layer number is in bounds
Introduces a bug where the right shift by 8 drops the lower byte going into the unknown_layer handler function. This will effectively drop rc error bits for unknown layers. The largest impact will be on windows where their resource manager is not a registered handler.
Fix this by just dumping all the bytes and not get fancy with masking things out.
Fixes: #2550

tss2-rc: fix unknown layer handler dropping bits (3.2.x)

---

test/integration/fapi-provisioning-with-template.int.c

This tests works only if for builds with --enable-self-generated-certificate. The test is now skipped if this option is disabled.

FAPI: Fix test provisioning with template.

---

test/integration/fapi-provisioning-with-template.int.c

If the configure option --enable-self-generated-certificate is not used this test can't be executed because no certificate will be stored in NV ram. The test will be skipped if no certificate is available.
Fixes: #2558

FAPI: Skip test fapi-fix-provisioning-with template without certificate.

---

afl-fuzzing/fuzz-ima.sh
afl-fuzzing/fuzz-system.sh
src/tss2-fapi/ifapi_ima_eventlog.c
src/tss2-fapi/ifapi_ima_eventlog.h
test/integration/fapi-quote-destructive.int.c
test/unit/fapi-check-ima-log.c
test/unit/fapi-eventlog.c

* For eventlogs in little endian format on big endian machines the data will be converted to big endian. That can occur if the option --ima_canonical_fmt is used.
* The tests with system events are skipped because the test data uses little endian.
* For the IMA test files in little endian format the little endian numbers are converted to big endian. The tests with little endian data in the json fields are skipped.
Addresses: #2521

FAPI: Fix event logging for big endian machines.

---

src/tss2-fapi/ifapi_keystore.c

The provisioning test in ifapi_check_provisioned will be skipped for ext nv and profile paths. The test did produce inappropriate error messages if the corresponding paths did not exist in keystore. The test is only needed for pathnames starting with the profile. Fixes: #2596

FAPI: Skip provisioning test for nv ext and profile paths.

---

src/tss2-fapi/tpm_json_serialize.c

Currenlty FAPI_GetInfo did produce errors if the TPM implements SHA3 hash algs. Now a warning is displayed.

FAPI: Fapi_GetInfo display warning for SHA3 hash algs

---

src/tss2-fapi/tpm_json_serialize.c

Currenlty FAPI_GetInfo did produce errors if the TPM implements SHA3 hash algs. Now a warning is displayed.

FAPI: Fapi_GetInfo display warning for SHA3 hash algs. 3.2.x

---

src/tss2-fapi/ifapi_keystore.c

The provisioning test in ifapi_check_provisioned will be skipped for ext nv and profile paths. The test did produce inappropriate error messages if the corresponding paths did not exist in keystore. The test is only needed for pathnames starting with the profile. Fixes: #2596

FAPI: Skip provisioning test for nv ext and profile paths. 3.2.x

---

.cirrus.yml
.github/workflows/codeql.yml
INSTALL.md
Makefile-test.am
Makefile.am
configure.ac
doc/tcti-spi-ftdi.md
include/tss2/tss2_tcti_spi_ftdi.h
lib/tss2-tcti-spi-ftdi.def
lib/tss2-tcti-spi-ftdi.map
lib/tss2-tcti-spi-ftdi.pc.in
man/tss2-tcti-spi-ftdi.7.in
src/tss2-tcti/mpsse/mpsse.c
src/tss2-tcti/mpsse/mpsse.h
src/tss2-tcti/mpsse/support.c
src/tss2-tcti/mpsse/support.h
src/tss2-tcti/tcti-spi-ftdi.c
src/tss2-tcti/tcti-spi-ftdi.h
test/unit/tcti-spi-ftdi.c

Bringing up a TCTI module to support the FTDI MPSSE USB to SPI bridge for communication with a SPI-based TPM. Example of a FTDI MPSSE USB to SPI bridge is the product "USB 2.0 Hi-Speed to MPSSE Cable (SPI/I2C/JTAG master) with +3.3V digital level signals", part no: C232HM-DDHSL-0. It is used for current development and testing.
A little background about the dependencies and options:
- **[current implementation]** Option 1:<br>tcti-spi-ftdi -> libmpsse from [devttys0](https://github.com/devttys0/libmpsse) -> [libftdi](http://www.intra2net.com/en/developer/libftdi/).
- libmpsse from devttys0: BSD-2-Clause; maintainer inactive since 2016
- libftdi: GNU Lesser General Public License (LGPL); open source USB driver library; easy to install via package managers
- Option 2:<br>tcti-spi-ftdi -> …

TCTI: Add USB TPM (FTDI MPSSE USB to SPI bridge) TCTI module

---

configure.ac

If no option was used for tcti-spi-ftdi no error should occur if libttdi ist not installed.

tcti-spi-ftdi: fix configure without libftdi.

---

src/tss2-fapi/ifapi_json_eventlog_serialize.c

Reading an eventlog > UINT16_MAX produced a segfault. This error is fixed and the buffer allocation was changed to reallocation.

FAPI: Fix read large system eventlog.

---

src/tss2-fapi/ifapi_helpers.c

The list of pcr registers was was allocated with the wrong size in the function copy_policy_element which caused a segfault if more than one pcr was used.

FAPI: Fix wrong allocation of pcr policy 3.2.x

---

src/tss2-fapi/ifapi_helpers.c

The list of pcr registers was was allocated with the wrong size in the function copy_policy_element which caused a segfault if more than one pcr was used.

FAPI: Fix wrong allocation of pcr policy.

---

INSTALL.md

Errors with autotools-archive 2018.03.13 did occur (#2624). Therefore the version is updated to 2019.01.06.

INSTALL.md Update autotool-archive version.

---

Makefile-test.am
test/unit/tcti-spi-ftdi.c
test/unit/tcti-spi-lt2go.c

To nullify the effect of the timeout in the unit test, as the runtime environment of the unit test is unpredictable. This is to address the reported issue https://github.com/tpm2-software/tpm2-tss/issues/2610

Fix unstable test/unit/tcti-spi-ftdi

---

test/integration/esys-act-set-timeout.int.c
test/integration/esys-certifyX509.int.c

Two integration tests failed for tests with /dev/tpmrm0 because the layer of the return code was not checked.

esys tests: Fix layer check for TPM2_RC_COMMAND_CODE.

---

test/integration/fapi-key-create-policies-sign.int.c

A bit mask for the layer of the return code was not used in one case of the  integration test fapi-key-create-policies-sign.int.c

fapi tests: Fix layer check for TPM2_RC_COMMAND_CODE.

---

Makefile.am
configure.ac

--without-sysusersdir and --without-tmpfilesdir does not work as expected. Since there's already machinery to exclude them, this patch adds onto it so they may be excluded through the normal autoconf mechanisms.

configure.ac: Make sysusers and tmpfiles optional

---

README.md

I stripped the first section down a lot to make it as clean as possible. I stripped some information that is crucial (because only what is crucial should be at the beginning of the README).
I might also add a `doc/tcti.md` in a later PR because this has developed a lot and could be documented better.
If you wonder about the non-breaking space in the table header: those are a hack for controlling the column width. Otherwise the spec column would take over.

README: replace wall of text with a table

---

Makefile.am

The invalid character e in the function fapi_set_permissions was deleted.

Makefile.am Delete invalid character.

---

Makefile-test.am
Makefile.am
configure.ac
doc/tcti-i2c-ftdi.md
doc/tcti-i2c-helper.md
include/tss2/tss2_tcti_i2c_ftdi.h
include/tss2/tss2_tcti_i2c_helper.h
lib/tss2-tcti-i2c-ftdi.def
lib/tss2-tcti-i2c-ftdi.map
lib/tss2-tcti-i2c-ftdi.pc.in
lib/tss2-tcti-i2c-helper.def
lib/tss2-tcti-i2c-helper.map
lib/tss2-tcti-i2c-helper.pc.in
man/tss2-tcti-i2c-ftdi.7.in
man/tss2-tcti-i2c-helper.7.in
src/tss2-tcti/tcti-i2c-ftdi.c
src/tss2-tcti/tcti-i2c-ftdi.h
src/tss2-tcti/tcti-i2c-helper.c
src/tss2-tcti/tcti-i2c-helper.h
test/unit/tcti-i2c-ftdi.c
test/unit/tcti-i2c-helper.c

Implement the tcti modules `tcti-i2c-ftdi` and `tcti-i2c-helper`:
- **`tcti-i2c-ftdi`:** The I2C TCTI FTDI can be used for communication with an I2C-based TPM over the FTDI MPSSE USB to I2C bridge. The FTDI module utilizes the `tcti-i2c-helper` library for handling the PTP I2C protocol and the `libftdi-dev` library for handling the USB to I2C communication.
- **`tcti-i2c-helper`:** The I2C TCTI helper can be used for TPM communication over I2C e.g. in embedded systems. It uses user supplied methods for I2C and timing operations in order to be platform independent. These methods are supplied to `Tss2_Tcti_I2c_Helper_Init` via the `TSS2_TCTI_I2C_HELPER_PLATFORM` struct. `tcti-i2c-ftdi` is an example implementation that utilizes the I2C TCTI helper.

TCTI: Implement tcti-i2c-helper and tcti-i2c-ftdi

---

src/tss2-fapi/ifapi_profiles.c

The deprecated index function is replaced by strchr. Fixes: #2656

fapi: remove deprecated index function.

---

doc/doxygen.dox

The function was not added to doc/doxygen.doc
Fixes: #2654

doxygen: Add function Esys_StartAuthSession_Finish

---

src/tss2-fapi/ifapi_keystore.c

The standard-library includes should be inside the ifdef? Fixes: #2660

fapi: remove includes from ifdef HAVE_CONFIG_H

---

test/unit/tcti-libtpms.c

When running the test on 32-bit platforms, we should not convert pointers to integers. expect_value() will convert the cmd to an integer value thus we should use expect_memory() instead.

test: unit: tcti-libtpms: fix test failed at 32-bit platforms.

---

doc/tcti-spi-ltt2go.md

Fix documentation for VID and PID
Signed-off-by: Paul Kissinger [paul.kissinger@letstrust.de](mailto:paul.kissinger@letstrust.de)

TCTI-SPI-LTT2GO: Fix documentation for VID and PID

---

src/tss2-esys/api/Esys_EvictControl.c
test/integration/esys-tr-fromTpmPublic-key.int.c

The TSS ESAPI spec (1.00 rev 14) says:
> If the ESYS_TR object on input was a persistent object, [the ESYS_TR
> output] parameter will not return a ESYS_TR object but instead will
> return ESYS_TR_NULL. Also the metadata in the ESYS_CONTEXT regarding
> the ESYS_TR object will be removed and the ESYS_TR object will be
> marked as invalid.
However, currently although the output parameter is set to ESYS_TR_NONE, the input ESYS_TR object isn't closed. Other than the obvious leak, this can cause an error when Esys_TR_FromTPMPublic is called twice, with the object having been recreated with different public data and persisted with Esys_EvictControl in between, since Esys_TR_FromTPMPublic now verifies that the public data hasn't changed for the ESYS_TR object (which it now has).
Address this by …

esys: close TR handle for input persistent handle in EvictControl_Finish

---

src/tss2-esys/api/Esys_EvictControl.c
test/integration/esys-tr-fromTpmPublic-key.int.c

The TSS ESAPI spec (1.00 rev 14) says:
> If the ESYS_TR object on input was a persistent object, [the ESYS_TR
> output] parameter will not return a ESYS_TR object but instead will
> return ESYS_TR_NULL. Also the metadata in the ESYS_CONTEXT regarding
> the ESYS_TR object will be removed and the ESYS_TR object will be
> marked as invalid.
However, currently although the output parameter is set to ESYS_TR_NONE, the input ESYS_TR object isn't closed. Other than the obvious leak, this can cause an error when Esys_TR_FromTPMPublic is called twice, with the object having been recreated with different public data and persisted with Esys_EvictControl in between, since Esys_TR_FromTPMPublic now verifies that the public data hasn't changed for the ESYS_TR object (which it now has).
Address this by …

esys: close TR handle for input persistent handle in EvictControl_Finish 3.2.x

---

src/tss2-fapi/api/Fapi_ChangeAuth.c
src/tss2-fapi/api/Fapi_CreateNv.c
src/tss2-fapi/api/Fapi_Decrypt.c
src/tss2-fapi/api/Fapi_Delete.c
src/tss2-fapi/api/Fapi_ExportKey.c
src/tss2-fapi/api/Fapi_Import.c
src/tss2-fapi/api/Fapi_NvExtend.c
src/tss2-fapi/api/Fapi_NvIncrement.c
src/tss2-fapi/api/Fapi_Provision.c
src/tss2-fapi/api/Fapi_Quote.c
src/tss2-fapi/api/Fapi_Unseal.c
src/tss2-fapi/fapi_int.h
src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_policy_callbacks.h
src/tss2-fapi/ifapi_policy_execute.c
src/tss2-fapi/ifapi_policy_execute.h
src/tss2-fapi/ifapi_policyutil_execute.c
test/integration/fapi-nv-authorizenv-cphash.int.c

For policy sessions the auth value is needed to generate the key for parameter encryption if the encryption is activated. To avoid the usage of the auth value for policy sessions a second session will be used to activate parameter encryption.

FAPI: Use a second session for parameter encryption.

---

.cirrus.yml

13-1 caused errors during package installation.

cirrus-ci update image-family to freebsd-13-2

---

src/tss2-fapi/api/Fapi_ChangeAuth.c
src/tss2-fapi/api/Fapi_CreateNv.c
src/tss2-fapi/api/Fapi_Decrypt.c
src/tss2-fapi/api/Fapi_Delete.c
src/tss2-fapi/api/Fapi_ExportKey.c
src/tss2-fapi/api/Fapi_Import.c
src/tss2-fapi/api/Fapi_NvExtend.c
src/tss2-fapi/api/Fapi_NvIncrement.c
src/tss2-fapi/api/Fapi_Provision.c
src/tss2-fapi/api/Fapi_Quote.c
src/tss2-fapi/api/Fapi_Unseal.c
src/tss2-fapi/fapi_int.h
src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_policy_callbacks.h
src/tss2-fapi/ifapi_policy_execute.c
src/tss2-fapi/ifapi_policy_execute.h
src/tss2-fapi/ifapi_policyutil_execute.c

For policy sessions the auth value is needed to generate the key for parameter encryption if the encryption is activated. To avoid the usage of the auth value for policy sessions a second session will be used to activate parameter encryption.

FAPI: Use a second session for parameter encryption 3.2.x.

---

src/tss2-fapi/api/Fapi_Delete.c
src/tss2-fapi/api/Fapi_NvIncrement.c
src/tss2-fapi/api/Fapi_Provision.c
src/tss2-fapi/fapi_util.c

A second session for encryption can only be used if the command has TPM2B parameters which can be encrypted. If no such parameter exists the TPM produces an error.
The call of the macro ENC_SESSION_IF_POLICY is replaces with ESYS_TR_NONE in these cases.

FAPI: Fix unneeded encryption.

---

src/tss2-fapi/api/Fapi_Delete.c
src/tss2-fapi/api/Fapi_NvIncrement.c
src/tss2-fapi/api/Fapi_Provision.c
src/tss2-fapi/fapi_util.c

A second session for encryption can only be used if the command has TPM2B parameters which can be encrypted. If no such parameter exists the TPM produces an error.
The call of the macro ENC_SESSION_IF_POLICY is replaces with ESYS_TR_NONE in these cases.

FAPI: Fix unneeded encryption 3.2.x

---

src/tss2-tcti/tcti-i2c-helper.c
src/tss2-tcti/tcti-spi-helper.c

If the TPM does not automatically transition from TPM_Init -> idle -> ready after waiting for TIMEOUT_B, manually initiate the transition by writing 1 to `TPM_STS_x.commandReady`.
resolves #2671

tcti-helper: Properly handle state transition from init to ready

---

src/tss2-tcti/tcti-libtpms.c

Due to tcti_libtpms->response_len and tcti_libtpms->response_buffer_len are size_t. We cannot convert the (size_t *) to (uint32_t *) on big-endian platforms. Thus we create temp uint32_t variables. Make the call and then assign it back to size_t variables.
This commit partially fix the test failure on big-endian platforms.

tss2-tcti: tcti-libtpms: fix test failure on big-endian platform

---

src/tss2-esys/api/Esys_FlushContext.c
src/tss2-esys/esys_int.h
src/tss2-esys/esys_tr.c
test/integration/esys-tr-fromTpmPublic-key.int.c

For every call of Esys_TR_FromTPMPublic the reference counter is incremented
to ensure that the created esys object is only freed by Esys_Close if the reference
count will be zero or decreased to zero.
An integration test was extended to test the reference counting.
Fixes: #2693

ESYS:  Add reference counting for Esys_TR_FromTPMPublic

---

src/tss2-esys/api/Esys_FlushContext.c
src/tss2-esys/esys_int.h
src/tss2-esys/esys_tr.c

For every call of Esys_TR_FromTPMPublic the reference counter is incremented to ensure that the created esys object is only freed by Esys_Close if the reference count will be zero or decreased to zero.

ESYS: Add reference counting for Esys_TR_FromTPMPublic 3.2.x

---

Makefile-test.am
Makefile.am
configure.ac
doc/tcti.md
include/tss2/tss2_tcti_spidev.h
lib/tss2-tcti-spidev.def
lib/tss2-tcti-spidev.map
lib/tss2-tcti-spidev.pc.in
man/tss2-tcti-spidev.7.in
src/tss2-tcti/tcti-spidev.c
test/unit/tcti-spidev.c

Add a new TCTI module that can talk to TPMs connected via spidev to the host.

TCTI: Add tcti-spidev

---

Makefile-test.am
doc/tcti.md
lib/tss2-tctildr.def
lib/tss2-tctildr.map
src/tss2-tcti/tctildr-dl.c
src/tss2-tcti/tctildr.c
src/tss2-tcti/tctildr.h
test/unit/tctildr-dl.c
test/unit/tctildr.c

Currently the tctildr is *almost* a tcti. I stumbled upon that when I wanted to create an abstraction for tctis in Rust.
* it misses the `Tss2_Tcti_Info` symbol which enables dynamic loading
* it does not have a caller-allocated init function, only callee-allocated ones
So I added the init function and the symbol. Technically it is a tcti now, so you can load the tctildr by specifying its path now:
```bash
tpm2 startup -c -T "/path/to/libtss2-tctildr.so"
```
Unfortunately, it does not keep to the `libtss2-tcti-<name>.so` convention, so I added a commit which enables loading by just passing `tctildr` and the loading mechanism will try `libtss2-<name>.so` as well.
```bash
tpm2 startup -c -T "tctildr"
```
You might ask yourself: _why would I want tctildr to be loadable_? No idea, but there …

tctildr: turn tctildr into a tcti

---

test/integration/esys-pcr-basic.int.c

When it is not possible to use Platform authorization, a 'goto error' is missing to skip the test

test esys-pcr-basic: fix platform auth management

---

src/tss2-fapi/fapi_util.c

In several cases the wrong handle TPM2_RH_EK was used instead of TPM2_RH_ENDORSEMENT.
This caused a wrong recreation of keys (except the EK) under the endorsement hierarchy.
Addresses: #2709

FAPI: Fix usage of endorsement handle

---

src/tss2-fapi/fapi_util.c

In several cases the wrong handle TPM2_RH_EK was used instead of TPM2_RH_ENDORSEMENT.
This caused a wrong recreation of keys (except the EK) under the endorsement hierarchy.
Now the correct hierarchy handle is used and a check whether the recreated public key of the recreated primary corresponds to the keystore.

FAPI: Fix usage of endorsement handle 3.2.x

---

src/tss2-fapi/fapi_int.h
src/tss2-fapi/fapi_util.c

If no policy is used the sessíon2 in FAPI context must be initialized with ESYS_TR_NONE in the authorization function.
The macro ENC_SESSION_IF_POLIY did produce an invalid ESYS handle if session2 was not initialized.

FAPI: Fix authorization session handling. 3.2.x

---

include/tss2/tss2_tctildr.h
lib/tss2-tctildr.map

tctildr: add symbol Tss2_Tcti_TctiLdr_Init to .map file

---

src/tss2-fapi/fapi_certificates.h
src/tss2-fapi/ifapi_curl.c

If a certificate which is downloaded from the uri defined in the EK certificate is self signed it can't be verified. It will not be stored in the certificate store. Self signed certificates have to be defined in the list of root certificates of FAPI.
Further Nuvoton root certificates TPM Root CA 1210 and 2112 are added.
Fixes #2738

FAPI: Fix intermediate self signed certificate.

---

Makefile-test.am
src/tss2-fapi/api/Fapi_Import.c
src/tss2-fapi/fapi_crypto.c
src/tss2-fapi/fapi_crypto.h
src/tss2-fapi/fapi_int.h
test/integration/fapi-import-ossl-key.int.c

A private OSSL PEM key now can be imported under a parent key in the FAPI keystore.

FAPI: Enable importing of private OSSL keys.

---

src/tss2-tcti/tcti-libtpms.c
test/unit/tcti-libtpms.c

On FreeBSD, `mremap()` is a stub returning `-1`/`ENOMEM`. Return `TSS2_TCTI_RC_BAD_VALUE` if tcti-libtpms conf is non-empty.
Fixes: #2730

tcti-libtpms: remove state file support for FreeBSD

---

Makefile-test.am
src/tss2-esys/api/Esys_Create.c
src/tss2-esys/api/Esys_CreateLoaded.c
src/tss2-esys/api/Esys_CreatePrimary.c
src/tss2-esys/api/Esys_HierarchyChangeAuth.c
src/tss2-esys/api/Esys_NV_ChangeAuth.c
src/tss2-esys/api/Esys_NV_DefineSpace.c
src/tss2-esys/api/Esys_ObjectChangeAuth.c
src/tss2-esys/esys_iutil.c
src/tss2-esys/esys_iutil.h
src/tss2-esys/esys_tr.c
test/integration/esys-check-auth-with-trailing-zero.int.c

When TPM Calulates the HMAC trailing zeros are rmoved. Therfore the
trailing zeros are removed in Esys_TR_SetAuth, Esys_Create, Esys_CreateLoded,
Esys_NV_DefineSpace, and Esys_CreatePrimary.
The auth value is also adapted in the ChangeAuth programs
Addresses  #2664

esys: remove trailing zeros in auth value.

---

.appveyor.yml
INSTALL.md
src/tss2-esys/openssl.props
src/tss2-esys/tss2-esys.vcxproj
src/tss2-mu/tss2-mu.vcxproj
src/tss2-rc/tss2-rc.vcxproj
src/tss2-sys/tss2-sys.vcxproj
src/tss2-tcti/tss2-tcti-mssim.vcxproj
src/tss2-tcti/tss2-tcti-swtpm.vcxproj
src/tss2-tcti/tss2-tcti-tbs.vcxproj
src/tss2-tcti/tss2-tctildr.vcxproj
tpm2-tss.sln

This MR simplifies the windows build with these updates:
- add a openssl.props to replace the openssl path magic strings
- update the platform toolset to ClangCL, which aligns it with the tpm2-provider project. (Also v141_clang_c2 is experimental)
- generalize the windows target platform to 10.0 (which will make it pick the latest installed one)
- update the VS version in the .sln file to 17 (the same as in the tpm2-provider project)
- update image to VS 2019 in .appveyor.yml
- update INSTALL.md to reflect ClangCL / VS 2019 changes
No changes to actual source code are made.

Simplify windows build

---

doc/tcti.md
src/tss2-esys/esys_context.c
src/tss2-tcti/tcti-device.c
src/tss2-tcti/tctildr-dl.c
src/tss2-tcti/tctildr-nodl.c
src/tss2-tcti/tctildr.c
test/unit/tcti-device.c
test/unit/tctildr-dl.c
test/unit/tctildr-nodl.c

A standard similar to TPM has been released in China, called TCM(Trusted Cryptography Module), and its device path is /dev/tcm0. 
The TCM standard is compatible with TPM, and TSS can be used to manage its device path.

tcti: Add '/dev/tcm0' to default conf

---

src/tss2-fapi/fapi_util.c

The session cleanup in error cases tried to flush a password session. Fixes: #2735

FAPI: Fix session cleanup.

---

.github/workflows/main.yml
INSTALL.md
Makefile.am
test/integration/main-fapi.c

* Error messages for the FAPI tests are improved.
* Ubuntu 18.04 will no longer be supported.
* INSTALL.md includes a list of operating systemes in the CI.

ci: remove ubuntu 18.04

---

src/tss2-fapi/ifapi_ima_eventlog.c
src/tss2-fapi/ifapi_json_eventlog_serialize.c
src/tss2-fapi/ifapi_json_serialize.c
src/tss2-fapi/ifapi_policy_json_serialize.c
src/tss2-fapi/tpm_json_serialize.c
test/integration/fapi-key-create-sign.int.c
test/integration/fapi-key-create2-sign.int.c

It was not checked whether the return code is equal 0 for the functions json_object_array_add and json_object_object_add.

FAPI: Add missing error check for json object add functions

---

src/tss2-fapi/api/Fapi_AuthorizePolicy.c
src/tss2-fapi/api/Fapi_ChangeAuth.c
src/tss2-fapi/api/Fapi_CreateKey.c
src/tss2-fapi/api/Fapi_Decrypt.c
src/tss2-fapi/api/Fapi_Delete.c
src/tss2-fapi/api/Fapi_ExportPolicy.c
src/tss2-fapi/api/Fapi_GetAppData.c
src/tss2-fapi/api/Fapi_GetCertificate.c
src/tss2-fapi/api/Fapi_GetDescription.c
src/tss2-fapi/api/Fapi_GetEsysBlob.c
src/tss2-fapi/api/Fapi_GetRandom.c
src/tss2-fapi/api/Fapi_GetTpmBlobs.c
src/tss2-fapi/api/Fapi_Import.c
src/tss2-fapi/api/Fapi_NvExtend.c
src/tss2-fapi/api/Fapi_NvIncrement.c
src/tss2-fapi/api/Fapi_NvRead.c
src/tss2-fapi/api/Fapi_NvSetBits.c
src/tss2-fapi/api/Fapi_NvWrite.c
src/tss2-fapi/api/Fapi_PcrExtend.c
src/tss2-fapi/api/Fapi_PcrRead.c
src/tss2-fapi/api/Fapi_Provision.c
src/tss2-fapi/api/Fapi_Quote.c
src/tss2-fapi/api/Fapi_SetAppData.c
src/tss2-fapi/api/Fapi_SetCertificate.c
src/tss2-fapi/api/Fapi_SetDescription.c
src/tss2-fapi/api/Fapi_Sign.c
src/tss2-fapi/api/Fapi_Unseal.c
src/tss2-fapi/api/Fapi_VerifyQuote.c
src/tss2-fapi/api/Fapi_WriteAuthorizeNV.c
src/tss2-fapi/fapi_util.c

* In some sub state machines, which had no async function, the state was not reset to the initial state in error cases.
* In some FAPI commands in the async part it was not checked whether the command is state is equal _FAPI_STATE_INIT.
* In several FAPI commands the current state of the FAPI context was not reset to _FAPI_STATE_INIT in error cases.
Thus it was possible that a sequence error did occur after  a normal error case.

FAPI: Fix error handling in state machines 3.2.x

---

.readthedocs.yml

To fix the error "Config validation error in build.os. Value build not found".

readthedocs: Add configuration key build to the readthedocs yaml file.

---

src/tss2-fapi/api/Fapi_Quote.c
src/tss2-fapi/fapi_int.h
src/tss2-fapi/ifapi_helpers.c

* Invalid free was executed when the event list is empty.
* QuoteInfo was not freed in error cases.
* Initialization of certificate was moved to last state of state machine.

FAPI: Fix Fapi_Quote errors.

---

src/util/aux_util.h

Fixes: ./src/util/aux_util.h:22:40: error: expected ')' before 'PRIx32'

aux_util: fix missing format specifier

---

Makefile-test.am
test/integration/fapi-provisioning-cert-error.int.c

* The test is now skipped if no ek_cert_less is set.
* The test is moved to the tests without device.

FAPI Test: Fix check with self signed certificate.

---

src/tss2-fapi/ifapi_helpers.c

The error message when an event from the eventlog for a certain PCR register had no digest in the selected PCR bank was confusing. Therefore, the error message now explains how the problem can be solved.

FAPI: Improve error message Fapi_Quote

---

test/unit/esys-vendor.c
test/unit/tcti-spidev.c

Conversions of max uint64 numbers to pointers did produce compile errors on 32bit systems. A cast to size_t is now added before the casting to a pointer.

unit tests: fix pointer casts on 32 bit systems.

---

src/tss2-fapi/ifapi_policyutil_execute.c

The state was not initialized correctly in error cases in the policy utility state machines.

FAPI: Fix state handling in policy execute 3.2.x.

---

configure.ac

tss does not support json-c versions < 0.13. The version is now checked by configure.
Addresses #2767

configure.ac Check json-c version.

---

Makefile-test.am
test/integration/test-common.c

The functions needed for ESYS anf FAPI test are activated with an ifdef now.
Fixes: #2770

TEST: Fix test with ESYS and FAPI disabled.

---

src/tss2-fapi/fapi_crypto.c
src/tss2-fapi/ifapi_ima_eventlog.c

* Possible out of bound array access in ima parser was fixed.
* Possible null pointer access in error cases in fapi crypto is fixed.

Fix coverity errors

---

src/tss2-fapi/fapi_crypto.c
src/tss2-fapi/ifapi_ima_eventlog.c

Coverity scan

---

src/tss2-fapi/fapi_util.c
src/tss2-fapi/ifapi_policy_execute.c

Policy sessions were not flushed if the policy session was successfully executed but the command where the policy was used for authorization was executed with an error.
Fixes: #2784

FAPI: Fix cleanup of policy sessions.

---

src/tss2-fapi/fapi_crypto.c
src/tss2-fapi/ifapi_profiles.c

On some platforms, compiler warnings are generated due to not include <strings.h> (note plural) when using index(3) as well as not utilizing the return value to BIO_flush().

FAPI: Fix compiler warnings

---

src/tss2-fapi/fapi_util.c

The max size of the value returned by the auth value callback sizeof(TPMU_HA) is now checked.

FAPI: Fix length check in auth callback.

---

src/tss2-fapi/fapi_util.c

The max size of the value returned by the auth value callback sizeof(TPMU_HA) is now checked.

FAPI: Fix length check in auth callback. 4.1.x

---

src/tss2-mu/tpmu-types.c

If a wrong selector was used for a TPMU objects to be marshalled only the error bad value was returned.
Now an error log message is displayed.

MU: Display error message for errors with wrong selectors.

---

Makefile.am

Bug: https://bugs.gentoo.org/931240
The 4.1.0 tarballs are currently broken since they are missing the files for ftdi.

Fix conditional EXTRA_DIST for tss2-tcti-spi-ftdi.*

---

configure.ac

* `==` is bash and not POSIX Bug: https://bugs.gentoo.org/931239

Remove bash syntax

---

src/tss2-fapi/api/Fapi_Provision.c
src/tss2-fapi/fapi_util.c

Currently FAPI provisioning tries to create the EK and SRK with the NULL auth value for the hierarchies.
Now first the corresponding flag in  TPM2_CAP_TPM_PROPERTIES with the property TPM2_PT_PERMANENT is checked. If an auth value is used for the hierarchy the auth value callback will be called. The "retry" code in the BAD_AUTH case is removed.

FAPI: Add check whether auth values exist for hierarchies.

---

src/tss2-fapi/ifapi_curl.c

The error message
"curl_url_set for CURUPART_URL failed: Unsupported URL scheme" was displayed if a self signed EK certificate was stored in the TPM. Now a better error message is displayed to explain that FAPI can be used if "ek_cert_less" is set to "yes" in the FAPI config file. Addresses: #2833

FAPI: Improve the error message for self signed EK certificates.

---

src/tss2-tcti/tctildr.c

The return code of tctildr_init_context_data was not checked in Tss2_TctiLdr_Initialize_Ex. The cleanup part of this function was not executed and so a leak was produced.
Fixes #2842

TCTI: Fix leak produced in Tss2_TctiLdr_Initialize_Ex

---

CHANGELOG.md
src/tss2-tcti/tcti-cmd.c
src/tss2-tcti/tcti-device.c
src/tss2-tcti/tcti-i2c-ftdi.c
src/tss2-tcti/tcti-i2c-helper.c
src/tss2-tcti/tcti-libtpms.c
src/tss2-tcti/tcti-mssim.c
src/tss2-tcti/tcti-pcap.c
src/tss2-tcti/tcti-spi-ftdi.c
src/tss2-tcti/tcti-spi-helper.c
src/tss2-tcti/tcti-spi-ltt2go.c
src/tss2-tcti/tcti-spidev.c
src/tss2-tcti/tcti-swtpm.c
src/tss2-tcti/tcti-tbs.c
src/tss2-tcti/tctildr.c
test/fuzz/tcti/tcti-fuzzing.c

Prepare 4.1.3

---

Makefile.am
_vscode/launch.json
_vscode/tasks.json
git.mk

This one might be opinionated.
So far there is no clean way to get first-class language support in vscode. Add make target for creating a [compilation database](https://clang.llvm.org/docs/JSONCompilationDatabase.html) using [bear](https://github.com/rizsotto/Bear). This enables you to do the following
```
make -j compile_commands.json
```
This file is recognized by many tools including e.g. clang-tidy and the vscode clangd extension. This way, the vscode language server knows *exactly* where symbols come from, which `#ifdefs` are compiled and where to find the right headers.
I also added a `launch.json` which lets you debug single unit and integration tests easily. What do you think of this?
Things I thought of but did not want to do in this first step:
* Automatic test discovery/running …

[RFC] vscode support

---

.cirrus.yml

13.2 is apparently no longer available

cirrus-ci update image-family to freebsd-14-0

---

.cirrus.yml

13.2 is apparently no longer available

cirrus-ci update image-family to freebsd-14-0 4.1.x

---

.cirrus.yml

13.2 is apparently no longer available

cirrus-ci update image-family to freebsd-14-0 (3.2.x)

---

src/tss2-fapi/fapi_util.c

%u was used for a 16 bit unsigned integer and %lu for sizeof. Fixes: #2856

FAPI: Fix wrong format directive in ifap_set_auth

---

src/tss2-fapi/api/Fapi_ChangeAuth.c
src/tss2-fapi/api/Fapi_NvWrite.c
src/tss2-fapi/fapi_util.c

* A duplicate write operation to the keystore was executed by Fapi_NvWrite.
* A write operation to the keystore was only needed after the first call of Fapi_NvWrite because the NV_WRITTEN bit was set.
* A write operation to the keystore by Fapi_ChangeAuth was only needed if the value of the attribute with_auth was changed.
Addresses: #2881

FAPI: Fix unnecessary writes to keystore.

---

bootstrap

With autoconf 2.72, the trailing / in bootstrap causes cryptic build failures to occur on MacOS. Removing these / allows autoconf to proceed.
And example of the error is:
```
Generating file lists: src_vars.mk
aminclude_static.am:63: warning: GITIGNOREFILES was already defined in condition TRUE, which includes condition AUTOCONF_CODE_COVERAGE_2019_01_06 and CODE_COVERAGE_ENABLED ...
Makefile.am:56:   'aminclude_static.am' included from here
Makefile.am:52: ... 'GITIGNOREFILES' previously defined here
Makefile.am: error: object 'src/tss2-esys/libtss2_esys_la-esys_crypto_mbed.lo' created by 'src/tss2-esys/esys_crypto_mbed.c' and 'src/tss2-esys//esys_crypto_mbed.c'
Makefile.am: error: object 'src/tss2-esys/libtss2_esys_la-esys_crypto_ossl.lo' created by 'src/tss2-esys/esys_crypto_ossl.c' and …
```

Remote trailing slash from bootstrap

---

INSTALL.md

I noticed that the code blocks in INSTALL.md weren't formatted right, so I fixed it

doc: Fix install.md code blocks

---

src/tss2-fapi/api/Fapi_ChangeAuth.c

The keystore has to be updated after Fapi_ChangeAuth for key objects because the private field is changed.
If not an HMAC error is produced when this key is used. Fixes: #2890

FAPI: Fix Fapi_ChangeAuth for keys.

---

.github/workflows/cifuzz.yml

cifuzz failed due to deprecated version of `actions/upload-artifact: v1`. 
https://github.com/actions/upload-artifact:
- v1/v2 were deprecated on June 30, 2024.
- v3 will be deprecated on November 30, 2024.

Update deprecated actions/upload-artifact@v1

---

.cirrus.yml
Makefile.am

* dlopen for swtpm failed after the upgrade from FreeBsd 14.0 to 14.1 As a workaround the configure option `--enable-nodl` is used for FreeBSD.
Addresses: #2907
* Initialisation of src_tss2_esys_libtss2_esys_la_LIBADD in Makefile.am is fixed.

CI: Fix cirrus ci after update of FreeBSD to 14.1

---

.cirrus.yml
m4/ld-version-script.m4

* The test macro gl_LD_VERSION_SCRIPT which not work on FreeBSD 14.1 is simplified and works now also on FreeBSD 14.1
* The option --enable-nodl, which was used as a workaround for this problem in the cirrus CI, is removed.

m4: fix test ld version script.

---

test/unit/tcti-spidev.c

The tests fail, similarly to how they failed due to _FILE_OFFSET_BITS == 64 as fixed in 932b1e78047ed0ddc09fcb06bff2e7cf96406976
```
FAIL: test/unit/tcti-spidev
===========================
[==========] tests: Running 1 test(s).
[ RUN      ] tcti_spi_init_test
ERROR:tcti:src/tss2-tcti/tcti-spidev.c:48:platform_spi_acquire() SPI acquire failed: Bad file descriptor
ERROR:tcti:src/tss2-tcti/tcti-spi-helper.c:164:spi_tpm_helper_log_register_access() READ register 0xd40f00 (4 bytes) failed in transaction start
ERROR:tcti:src/tss2-tcti/tcti-spidev.c:68:platform_spi_release() SPI release failed: Bad file descriptor
ERROR:tcti:src/tss2-tcti/tcti-spidev.c:48:platform_spi_acquire() SPI acquire failed: Bad file descriptor
ERROR:tcti:src/tss2-tcti/tcti-spi-helper.c:164:spi_tpm_helper_log_register_acces …
```

test: skip tcti-spidev on 32bit architectures with 64bit time_t

---

src/tss2-tcti/tcti-mssim.c
test/unit/tcti-mssim.c

* socket_xmit_buf was not called after successful marshalling.
* The result of the write function was not set in the wrapper function for write in the teardown function.
Fixes: #2915

tcti-msim: Fix call of socket_xmit_buf in send_sim_session_end.

---

src/tss2-fapi/api/Fapi_WriteAuthorizeNV.c
src/tss2-fapi/fapi_int.h
src/tss2-fapi/ifapi_helpers.c
src/tss2-mu/tpm2b-types.c

* Fix missing check of scanf result.
* Fix storing of local variable stored in non-local memory.
* MU: Remove unneeded cast in TPM2B_UNMARSHAL.

FAPI: fix problems detected by scanner.

---

.readthedocs.yml
sphinx/requirements.txt

Not all needed python packages to generate the index.html file were installed. Addresses: #2917

readthedocs: add requirement file.

---

sphinx/requirements.txt

Embedding of README.mv did not work in newer sphinx versions.

readthedocs: downgrade sphinx

---

src/tss2-fapi/ifapi_keystore.c

The error message "key not found" was misleading for the case when a NV object was not found.

FAPI: Fix misleading error message.

---

doc/tss-for-zephyr.md
include/tss2/tss2_tcti.h
src/tss2-tcti/tctildr-nodl.c
src/util-io/io.c
src/util/aux_util.h

WIP to prepare TSS for Zephyr integration.
@drandreas: I would like to have your opinion on this. I noticed that you [introduced Zephyr](https://github.com/tpm2-software/tpm2-tss/commit/7482d46f1fa017ee370aa132de10f6012dff588c) some time ago. This commit overwrites the void* TSS2_TCTI_POLL_HANDLE, since it was not working for me. Would this be a problem from your side?

Add support to use TSS with Zephyr

---

.github/workflows/main.yml

The fetch depth for test-coverage was accidentally set to 01.

ci: fix git fetch depth

---

.cirrus.yml

The resource projects/freebsd-org-cloud-dev/global/images/family/freebsd-14-1 was not found.

ci: Cirrus ci update freebsd-14-1 to freebsd-14-2

---

dist/fapi-profiles/P_ECCP256SHA256.json
dist/fapi-profiles/P_ECCP384SHA384.json
dist/fapi-profiles/P_RSA2048SHA256.json
dist/fapi-profiles/P_RSA3072SHA384.json
test/data/fapi/P_ECC.json
test/data/fapi/P_ECC384.json
test/data/fapi/P_ECC_error.json
test/data/fapi/P_ECC_sh_eh_policy.json
test/data/fapi/P_ECC_sh_eh_policy_sha384.json
test/data/fapi/P_ECC_system.json
test/data/fapi/P_RSA.json
test/data/fapi/P_RSA2.json
test/data/fapi/P_RSA3072.json
test/data/fapi/P_RSA_EK_persistent.json
test/data/fapi/P_RSA_nameAlg_sha1.json
test/data/fapi/P_RSA_sh_policy.json

The variable srk_persistent in the profile is no longer used. A persistent SRK will be created if the TPM handle is added to the variable srk_template.
E.g.:  "srk_template": "system,restricted,decrypt,0x81000001"

FAPI: Fix outdated fapi profiles.

---

Makefile-test.am
Makefile.am
configure.ac
include/tss2/tss2_esys.h
include/tss2/tss2_sys.h
include/tss2/tss2_tcti_null.h
lib/tss2-esys.def
lib/tss2-esys.map
lib/tss2-sys.def
lib/tss2-sys.map
lib/tss2-tcti-null.def
lib/tss2-tcti-null.map
lib/tss2-tcti-null.pc.in
src/tss2-esys/esys_cp_rp_hash.c
src/tss2-esys/esys_int.h
src/tss2-esys/esys_iutil.c
src/tss2-esys/esys_iutil.h
src/tss2-esys/tss2-esys.vcxproj
src/tss2-sys/api/Tss2_Sys_Abort.c
src/tss2-sys/api/Tss2_Sys_GetCpBuffer.c
src/tss2-sys/tss2-sys.vcxproj
src/tss2-tcti/tcti-null.c
src/tss2-tcti/tcti-null.h
test/integration/esys-cp-hash.int.c
test/tpmclient/tpmclient.int.c
tss2-dlopen/tss2-dlopen-esys.c

* The ESYS API is extended with the functions:
Esys_GetCpHash, Esys_GetRpHash, and Esys_Abort.
The cp hash can computed after the async call of a function. The rp hash
after the finish call. If only the async call is executed to to compute the cp hash
Esys_Abort has to be called to enable the execution of further ESYS commands.
* The function Tss2_Sys_Abort to reset the SYS sate is added.
*  The state handling of Tss2_Sys_GetCpBuffer is changed.
* An integration test is added.
* A tcti module which can only used for tcti initialization is added.
Addresses: #2930.

ESYS: Support of Cp and RpHashes from Esys Layer

---

Makefile.am

The --install option in ACLOCAL_AMFLAGS creates problems for Gentoo users using slibtool. ACLOCAL_AMFLAGS has been deprecated since Automake 1.13 in favor of AC_CONFIG_MACROS_DIR([m4]). This allows slibtool to work.

build: Removed deprecated ACLOCAL_AMFLAGS to support slibtool

---

src/tss2-tcti/tcti-pcap-builder.c

illumos needs a similar fix to FreeBSD for defining the clock source to use with pcap builder.

TCTI: Fix clock source on illumos in pcap builder

---

src/tss2-fapi/api/Fapi_GetPlatformCertificates.c

If no certificates are available no error code  (TSS2_FAPI_RC_NO_CERT) was returned.

FAPI: Fix Fapi_GetPlatformCertificates without certificates.

---

src/tss2-tcti/tcti-null.h

This struct can be used for quick access without requiring to call Tss2_Tcti_Null_Init() first.
Fixes: #2950

TCTI: Add Tss2_Tcti_Null_Context struct

---

src/tss2-fapi/ifapi_verify_cert_chain.c

An url was displayed after freeing the corresponding variable.

FAPI: Fix usage of variable after free.

---

src/tss2-fapi/api/Fapi_Sign.c

Fapi_Sign causes a memory leak when the optional public key output parameter is not provided. Fixes: #2962

FAPI: Fix leak in Fapi_Sign

---

configure.ac

As per specifications, config files shipped by upstream projects/distros/vendors need to go in /usr/lib/. /etc/ is reserved for local modifications by sysadmins.
https://www.freedesktop.org/software/systemd/man/latest/tmpfiles.d.html https://www.freedesktop.org/software/systemd/man/latest/sysusers.d.html https://uapi-group.org/specifications/specs/configuration_files_specification/

configure: install tmpfiles.d and sysusers.d in libdir

---

src/tss2-tcti/tcti-libtpms.c

mremap is merely unreachable when building for FreeBSD, which makes the compiler mad about the implicit function declaration.

libtpms: mock mremap to support FreeBSD with -Werror=implicit-function-declaration

---

Makefile.am

src/tss2-rc/tss2-rc.vcxproj is added to EXTRA_DIST files. Fixes: #2969

build: Fix file tss2-rc.vcxproj not in release.

---

.cirrus.yml
Makefile.am

* src/tss2-rc/tss2-rc.vcxproj is added to EXTRA_DIST files. Addresses: #2969
* --nodl removed for cirrus CI.

build: Fix file tss2-rc.vcxproj not in release (4.1.x)

---

src/tss2-fapi/ifapi_policy_callbacks.c

The cleanup function for the nv object to be authorized was called before authorization, and the wrong object was used for authorization.

FAPI: Fix nv object authorization for policy authorize nv.

---

src/tss2-fapi/ifapi_policy_callbacks.c

The cleanup function for the nv object to be authorized was called before authorization, and the wrong object was used for authorization.

FAPI: Fix nv object authorization for policy authorize nv 4.1.x

---

.appveyor.yml
.github/workflows/main.yml
src/tss2-fapi/ifapi_io.c
src/tss2-fapi/ifapi_keystore.c
test/integration/esys-check-auth-with-trailing-zero.int.c
test/integration/fapi-key-create-policy-pcr-sign.int.c
test/integration/main-fapi.c

* CI: Remove ubuntu 20.04, add arch-linux and ubuntu-24.04
* FAPI: Enable usage of links in fapi-io.c
* FAPI Test: fix scanbuild error produced by mkdtemp.
* ESYS Test: Fix return code check in check auth with trailing zeros.
* FAPI Test: Fix scanbuild warning fapi-key-create-policy-pcr-sign.

CI: update ubuntu and arch , fix scanbuild warnings

---

.appveyor.yml
src/tss2-esys/openssl.props
src/tss2-esys/tss2-esys.vcxproj

* Visual Studio 2019 changed to Visual Studio 2022
* Paths related to ossl3 where added to the props file.

ci appveyor: switch to ossl3
