tpm2-software/tpm2-tss

- README.md
Add pointer to the INSTALL instructions.
Fix link to the PDF README.
Use header for the resources section.
> Minor fixups to the README.md file.

- resourcemgr/Makefile.in
- sysapi/Makefile.in
- test/tpmclient/Makefile.in
> Use order-only prerequisite to make lib directory.

- .gitignore
- INSTALL
- Makefile.am
- bootstrap
- configure.ac
These two commits should resolve #6 and #23
> Libtool and pthread macro

- tcti/localtpm/localtpm.c
- tcti/tpmsockets/tpmsockets.cpp
- test/tpmclient/tpmclient.cpp
Fixed issues with debug messages in localtpm.c
fixed a couple compile errors caused by last merge.
> Fixed issues with debug messages in localtpm.c and compile errors.

- resourcemgr/resourceMgr.vcxproj
- test/tpmclient/tpmclient.vcxproj
> windows: Fixup reference to platformcommand.c

- test/tpmtest/tpmtest.cpp
> tpmtest: treat IBM software TPM as simulator

- test/tcti_device_test.c
This accounts for an API change from
748405322fc5b43d3123266f7f4a5a7a0ba5f30e
> tcti_device_test: Remove MAGIC and VERSION from Init call.

- test/tpmclient/tpmclient.cpp
> tpmclient: Add debug callback to device TCTI config.

- Makefile.am
- common/debug.c
- common/debug.h
- common/sockets.cpp
- common/sockets.h
- include/tcti/common.h
- include/tcti/tcti_socket.h
- resourcemgr/resourcemgr.c
- sysapi/include/tcti_util.h
- tcti/logging.h
- tcti/platformcommand.c
- tcti/tcti_socket.cpp
- test/tpmclient/tpmclient.cpp
- test/tpmtest/tpmtest.cpp
This series of patches removes global data from the socket code, including the socket TCTI.
> Socket global

- common/sockets.cpp
- tcti/tcti_socket.cpp
compiler error on Windows in common\sockets.cpp
use of non-existent commandCodeStrings array in tcti_socket.cpp
> fixed master branch:

- resourcemgr/criticalsection_linux.c
- resourcemgr/resourcemgr.c
- tcti/tcti_socket.cpp
> Fix compiler warnings that are being turned into errors when

- test/tpmtest/tpmtest.cpp
added in:
33 - SYMMETRIC ENCRYPT/DECRYPT TESTS
34 - ASYMMETRIC ENCRYPT/DECRYPT TESTS
35 - VERIFY SIGNATURE WITH EXTERNAL KEY TEST
36 - VERIFY SIGNATURE WITH CREATED KEY TEST
37 - NV EXTENSION TEST
38 - PCR EXTENDED TEST
39 - CLOCK/TIME TEST
> Added in use case & functional tests in tpmtest

- .gitignore
- Makefile.am
- sysapi/sysapi_util/CommandUtil.c
- test/CommonPreparePrologue_unit.c
> Common prepare prologue deref

- .gitignore
- Makefile.am
- include/sapi/implementation.h
- resourcemgr/getcommands.c
- test/GetNumHandles_unit.c
- test/getcommands-malloc-mock_unit.c
This resolves #250 and adds a unit test for the GetNum*Handles functions.
> Tpm cc final

- sysapi/include/sys_api_marshalUnmarshal.h
> Remove dead code in sys_api_marshalUnmarshal.h

- .travis.yml
> travis: dump unit test logs

- sysapi/include/sys_api_marshalUnmarshal.h
Using macros like this is generally a bad thing but I've added a pile of
comments to make things clear.
> Shrink the adapter macros in (un)?marshal with another macro.

- Makefile.am
> Link unit tests against libsapi instead of building source directly.

- Makefile.am
- configure.ac
- lib/debug_config.site
- lib/default_config.site
Replace use of CONFIG_SITE and hard coded flags in the Makefile.am with some configure.ac magic.
> Default flags

- configure.ac
> Add a few new flags and change -fPIC from LDFLAG to CFLAG.

- Makefile.am
- tcti/tcti_device.c
> libtcti-device: Replace use of CHANGE_ENDIAN_* with libmarshal.

- resourcemgr/resourcemgr.c
- sysapi/sysapi_util/CommandUtil.c
- test/common/sample/LoadExternalHMACKey.c
- test/common/sample/SessionHmac.c
- test/common/sample/TpmHash.c
- test/common/sample/TpmHmac.c
- test/tpmclient/tpmclient.c
- test/tpmtest/tpmtest.c
> More random fixes

- include/sapi/tss2_tpm2_types.h
I haven't worked out much of a strategy for pulling patches from master in to the 1.x branch but these are low risk: only a few changes to this header and all are very limited fixes.
> Cherry pick fixes to constants.

- README.md
> README: Remove mention of the old resourcemgr and its deprecation.

- sysapi/sysapi/ContextManagement.c
- sysapi/sysapi/DecryptParam.c
- tcti/commonchecks.c
- tcti/tcti_socket.c
- test/common/sample/Entity.c
- test/tpmclient/tpmclient.c
- test/tpmclient/tpmclient.h
@flihp
- Cleanup the usage of extern "C"
- Only use goto where is make sense
> More cleanups

- CONTRIBUTING.md
> Add instructions for contributing to the project.

- .gitignore
Add vim temp files, ctags, and *.patch
> gitignore updates for vi temp files

- Dockerfile
- INSTALL
- INSTALL.md
Added Dockerfile to allow for building in a container to
help those who are running on a system with hard to find
packages.
> Ubuntu dependencies in INSTALL files

- README.md
> README: Added documentation images for easy access

- CHANGELOG.md
> CHANGELOG.md: update for 1.1.0 release.

- Dockerfile
> Dockerfile: Removed simulator-xzy commands

- README.md
> README.md: Add section with info on the mailing list and IRC channel.

- test/tpmclient/DecryptEncrypt.c
This makes the function more readable for humans and coverity alike. In
the old form coverity complains about an issue. The new form doesn't
change the logic (tests still pass) but coverity no longer complains.
> tpmcliet: Re-write GenerateSessionEncryptDecryptKey for readability.

- sysapi/sysapi_util/CommandUtil.c
- tcti/sockets.cpp
- tcti/tcti_socket.cpp
- test/integration/context-util.c
- test/tpmclient/DecryptEncrypt.c
- test/tpmclient/tpmclient.int.cpp
This PR fixes all outstanding 'high' issues identified by coverity. The master branch already has all of these fixes. Some were cherry-picked directly.
> Coverity 1.x

- .travis.yml
- README.md
> README.md: Add coverity badge with link to scan results.

- Makefile.am
- test/integration/abi-version.int.c
- test/tpmclient/tpmclient.int.c
tpmclient.AbiVersionTest has been split out into the abi-version
integration test test/integration/abi-version.int.c
> abi-version: AbiVersionTest is now in integration

- .travis.yml
- test/unit/CommonPreparePrologue.c
- test/unit/CopyCommandHeader.c
- test/unit/GetNumHandles.c
- test/unit/UINT16-marshal.c
- test/unit/UINT32-marshal.c
- test/unit/UINT64-marshal.c
- test/unit/UINT8-marshal.c
- test/unit/marshal-TPM2B-simple.c
- test/unit/tcti-device.c
- test/unit/tcti-socket.c
convert unit tests to cmocka 1.0.1
> convert unit tests to new cmocka API

- Makefile.am
- test/unit/TPMA-marshal.c
- test/unit/UINT8-marshal.c
Add unit tests to marshaling TPM types
> Unit tests

- .travis.yml
- Makefile.am
- README.md
- configure.ac
- test/unit/CheckOverflow.c
- test/unit/CommonPreparePrologue.c
- test/unit/CopyCommandHeader.c
- test/unit/GetNumHandles.c
- test/unit/UINT16-marshal.c
- test/unit/UINT32-marshal.c
- test/unit/UINT64-marshal.c
- test/unit/UINT8-marshal.c
- test/unit/marshal-TPM2B-simple.c
- test/unit/marshal-UINT16.c
- test/unit/marshal-UINT32.c
- test/unit/tcti-device.c
- test/unit/tcti-socket.c
- test/unit/unmarshal-UINT16.c
- test/unit/unmarshal-UINT32.c
This is a collection of cherry-picks (with a few fixups) to get the build for the 1.x branch sync'd up with build fixes from master.
> Cherry picks 1.2.0

- MAINTAINERS
> MAINTAINERS: Remove Jimmy, add Tadeusz.

- Makefile.am
- test/unit/TPM2B-marshal.c
Add unit tests for TPM2B types
> Add unit tests for TPM2B types

- marshal/tpm2b-types.c
- marshal/tpml-types.c
- marshal/tpms-types.c
- marshal/tpmt-types.c
- marshal/tpmu-types.c
Don't need to add and then substruct the same thing in one statement.
> simplify offset calculation in marshal

- Makefile.am
- test/unit/TPMS-marshal.c
> Add unit test for TPMS type

- Makefile.am
- test/unit/TPML-marshal.c
> test: Add test for TPML type

- marshal/tpmt-types.c
* marshal: catch bad reference condition early in TPMT
* marshal: formating changes in TPMT
> TPMT updates

- Makefile.am
- test/unit/TPMT-marshal.c
- test/unit/TPMU-marshal.c
Add unit tests for TPMT and TPMU types
> Add unit tests for TPMT and TPMU types

- CONTRIBUTING.md
- doc/coding_standard_c.md
This should be merged into 1.x and then cherry-picked over to master.
Signed-off-by: Philip Tricca <flihp@twobit.us>
> CONTRIBUTING.md: Add coding standard and blurb about it.

- sysapi/sysapi/Tss2_Sys_HashSequenceStart.c
- sysapi/sysapi/Tss2_Sys_PolicySecret.c
Fix regression caused by Commit: c54e876b9.
Reported by @williamcroberts
> Regression fix

- Makefile.am
- include/sapi/implementation.h
- include/sapi/sys_api_part3.h
- sysapi/sysapi/Tss2_Sys_EncryptDecrypt2.c
- sysapi/sysapi_util/GetNumHandles.c
- test/integration/encrypt-decrypt-2.int.c
- test/integration/encrypt-decrypt.int.c
- test/integration/sapi-util.c
- test/integration/sapi-util.h
This PR adds support for this new function. It also adds a test case for the older EncryptDecrypt command as well as the new one and resolves issue #506
> Add support for EncryptDecrypt2 command

- sysapi/sysapi_util/CompareSizedByteBuffer.c
- sysapi/sysapi_util/ConcatSizedByteBuffer.c
- sysapi/sysapi_util/GetDigestSize.c
- sysapi/sysapi_util/GetNumHandles.c
Refactor outstanding sysapi util functions.
> sysapi: refactor sysapi util functions

- include/sapi/tpmb.h
- marshal/tpm2b-types.c
- sysapi/sysapi/authorizations.c
- sysapi/sysapi_util/ConcatSizedByteBuffer.c
- test/integration/asymmetric-encrypt-decrypt.int.c
- test/integration/create-keyedhash-sha1-hmac.int.c
- test/integration/encrypt-decrypt-2.int.c
- test/integration/encrypt-decrypt.int.c
- test/integration/get-random.int.c
- test/integration/hierarchy-change-auth.int.c
- test/integration/pcr-extension.int.c
- test/integration/sapi-util.c
- test/integration/sapi-util.h
- test/integration/start-auth-session.int.c
- test/tpmclient/CreateNullSession.c
- test/tpmclient/DecryptEncrypt.c
- test/tpmclient/Entity.c
- test/tpmclient/LoadExternalHMACKey.c
- test/tpmclient/SessionHmac.c
- test/tpmclient/StartAuthSession.c
- test/tpmclient/TpmCalcPHash.c
- test/tpmclient/TpmHandleToName.c
- test/tpmclient/TpmHash.c
- test/tpmclient/TpmHmac.c
- test/tpmclient/kdfa.c
- test/tpmclient/tpmclient.h
- test/tpmclient/tpmclient.int.c
- test/unit/TPM2B-marshal.c
- test/unit/TPMT-marshal.c
- test/unit/TPMU-marshal.c
> TPM2B simplification

- RELEASE.md
This set of requirements / instructions is taken nearly verbatim from
the tpm2-abrmd repo.
> RELEASE.md: Document release process.

- CONTRIBUTING.md
> CONTRIBUTING.md: Document requirements for commit message format & DCO.

- CONTRIBUTING.md
- README.md
- RELEASE.md
- configure.ac
> 1.x cherry picks for 1.3.0 rc1

- CONTRIBUTING.md
- doc/coding_standard_c.md
Add coding standards requirements.
> CONTRIBUTING.md: Add coding standards requirements.

- CHANGELOG.md
Quick update to the CHANGELOG.md before 1.3.0-rc1 goes out.
> CHANGELOG.md: Update for 1.3.0-rc1.

- .travis.yml
- Makefile.am
- configure.ac
Add support for code coverage measurement.
Also a minor tweak to build check_PROGRAMS independently running them.
> Add support for code-coverage

- marshal/tpms-types.c
> Marshal: fixed NULL pointer dereferencing

- marshal/tpms-types.c
> Use _MU_ RC layer in place of _TYPES_ layer removed in e66804b9ad58.

- Makefile.am
> build: Include README.md and friends in the release tarball.

- CHANGELOG.md
> CHANGELOG.md: Include data for version 1.3.0.

- .travis.yml
- script/int-log-compiler.sh
This resolves the race condition worked around in 24fb1306e0204c931bb0cab63d04c6534d49bb78 so we revert 24fb1306e0204c931bb0cab63d04c6534d49bb78 after we've fixed it.
> Master fix test race

- include/sapi/implementation.h
- include/sapi/sys_api_part3.h
- include/sapi/tss2_tpm2_types.h
- sysapi/include/sys_api_marshalUnmarshal.h
- sysapi/sysapi/Tss2_Sys_AC_GetCapability.c
- sysapi/sysapi/Tss2_Sys_AC_Send.c
- sysapi/sysapi/Tss2_Sys_Policy_AC_SendSelect.c
- sysapi/sysapi_util/GetNumHandles.c
- sysapi/sysapi_util/Unmarshal_TPML_AC_CAPABILITIES.c
- sysapi/sysapi_util/Unmarshal_TPMS_AC_OUTPUT.c
> sapi: backport AC commands to 1.x

- .travis.yml
- Makefile.am
- configure.ac
- include/sapi/sys_api_part3.h
- include/sapi/tss2_tpm2_types.h
- sysapi/sysapi/Tss2_Sys_PolicyTemplate.c
- sysapi/sysapi_util/GetNumHandles.c
- test/integration/policy-template.int.c
- test/integration/sapi-util.c
- test/integration/sapi-util.h
Add Tss2_Sys_PolicyTemplate() command
> Policy template

- README.md
> master README.md: Update travis badge for intel -> tpm2-software.

- marshal/tss2-mu.vcxproj
- sysapi/tss2-sapi.vcxproj
- tpm2-tss.sln
Visual Studio 64-bit build support.
Fixes issue #749.
> Add Visual Studio 64-bit build rules

- sysapi/sysapi/Tss2_Sys_Commit.c
- sysapi/sysapi/execute.c
these came out of the scans for ESAPI PR
> Coverity fixes

- include/sapi/sys_api_part3.h
- include/sapi/tss2_tpm2_types.h
- sysapi/sysapi/Tss2_Sys_PolicyAuthorizeNV.c
- sysapi/sysapi_util/GetNumHandles.c
Add support for TPM2_CCPolicyAuthorizeNV command.
> sapi: add TPM2PolicyAuthorizeNV command

- CHANGELOG.md
- Makefile.am
This PR picks over #777 and updates the changelog. These are the last changes to 1.x before the next minor release.
> 1.x cherry pick and changelog update

- INSTALL.md
> INSTALL.md: Fix broken formatting / bullet for OpenSSL dependency.

- include/sapi/tss2_tpm2_types.h
- test/integration/sapi-util.c
- test/integration/test.h
- test/tpmclient/tpmclient.h
Cleanup tss2_tpm2_types.h
Fixes: #675
Fixes: #735
> sapi: More header cleanups

- include/sapi/sys_api_part3.h
- include/sapi/tss2_tpm2_types.h
> Headers Cleanup

- include/sapi/tss2_sys.h
> sapi: cleanup tss2_sys.h

- tcti/tcti_device.c
This *should* be the last round of changes to the device TCTI for 2.0. Socket TCTI is next.
> Tcti device spec final

- esapi/esapi/Esys_ContextSave.c
- esapi/esapi/Esys_CreateLoaded.c
- esapi/esapi/Esys_EncryptDecrypt2.c
- esapi/esapi/Esys_FieldUpgradeData.c
- esapi/esapi/Esys_FieldUpgradeStart.c
- esapi/esapi/Esys_FirmwareRead.c
- esapi/esapi/Esys_FlushContext.c
- esapi/esapi/Esys_HMAC_Start.c
- esapi/esapi/Esys_HierarchyChangeAuth.c
- esapi/esapi/Esys_NV_ChangeAuth.c
- esapi/esapi/Esys_NV_ReadLock.c
- esapi/esapi/Esys_NV_UndefineSpace.c
- esapi/esapi/Esys_NV_WriteLock.c
- esapi/esapi/Esys_PolicyAuthorizeNV.c
- esapi/esapi/Esys_PolicyTemplate.c
- esapi/esapi/Esys_SequenceComplete.c
- esapi/esapi/Esys_StartAuthSession.c
- esapi/esapi_util/esys_int.h
- esapi/esapi_util/esys_iutil.c
- esapi/esapi_util/esys_iutil.h
- esapi/esapi_util/esys_mu.c
- esapi/esapi_util/esys_types.h
- include/esapi/tss2_esys.h
- include/sapi/sys_api_part3.h
- sysapi/sysapi/Tss2_Sys_FieldUpgradeData.c
- sysapi/sysapi/Tss2_Sys_FieldUpgradeStart.c
- test/integration/esys-clear.int.c
- test/integration/esys-hierarchychangeauth.int.c
Add support for TPM2.0 r1.38 functions and some minor fixes.
> Esapi r138 and minor fixed

- .travis.yml
- CHANGELOG.md
> CHANGELOG.md: Update for 1.4.0 release.

- script/int-log-compiler.sh
int-log-compiler.sh needs to detect degraded OS environments.
Specifically "Bash for Ubuntu for Windows" partially emulates /proc,
so the ps and netstat commands fail to show processes and open sockets.
Fixes #764.
> script: Add Sanity Checks to int-log-compiler.sh

- Makefile-test.am
- tcti/sockets.c
- tcti/sockets.h
- tcti/tcti_socket.c
- test/unit/socket.c
Fixup for #825. Already reviewed by @AndreasFuchsSIT
> Socket init close cleanup rebase

- test/unit/tcti-socket.c
This test ensures that the caller may provide a NULL buffer and a
non-NULL reference to a size variable when calling the TCTI receive
function. The this should return the required size of the response
buffer to the caller. A second call to receive providing a buffer of
this size will succeed.
> test: Add test to query size of response in socket TCTI.

- Makefile-test.am
- esapi/esapi/Esys_HMAC_Start.c
- esapi/esapi/Esys_HashSequenceStart.c
- esapi/esapi/Esys_HierarchyChangeAuth.c
- esapi/esapi/Esys_NV_ChangeAuth.c
- esapi/esapi/Esys_NV_DefineSpace.c
- esapi/esapi/esys_tr.c
- test/integration/esys-clear.int.c
- test/integration/esys-clockset.int.c
- test/integration/esys-create-fail.int.c
- test/integration/esys-create-password-auth.int.c
- test/integration/esys-create-session-auth.int.c
- test/integration/esys-createloaded.int.c
- test/integration/esys-evict-control-serialization.int.c
- test/integration/esys-hashsequencestart.int.c
- test/integration/esys-hmacsequencestart.int.c
- test/integration/esys-make-credential.int.c
- test/integration/esys-nv-ram-counter.int.c
- test/integration/esys-nv-ram-extend-index.int.c
- test/integration/esys-nv-ram-set-bits.int.c
- test/integration/esys-object-changeauth.int.c
- test/integration/esys-policy-nv-changeauth.int.c
- test/integration/esys-policy-password.int.c
- test/integration/esys-rsa-encrypt-decrypt.int.c
- test/integration/test-esapi.h
The latest series of patches for ESAPI.
Mostly very small and mostly easy patches, except for the last one that adds 8 new test cases.
> Various ESAPI updates

- src/tss2-sys/GetNumHandles.c
Fixes for two commands in getNumHandle
> GetHandle fixes

- Makefile.am
- include/tss2/tss2_tpm2_types.h
- src/tss2-sys/api/Tss2_Sys_Initialize.c
- test/integration/asymmetric-encrypt-decrypt.int.c
- test/integration/create-keyedhash-sha1-hmac.int.c
- test/integration/policy-authorizeNV.int.c
- test/integration/sapi-util.c
- test/integration/sys-initialize.int.c
- test/tpmclient/DecryptEncrypt.c
- test/tpmclient/LoadExternalHMACKey.c
- test/tpmclient/tpmclient.int.c
Two fixes for SAPI:
- abiVersion == NULL
- TPMA_OBJECT_SIGN
> SAPI: Two minor fixes

- src/tss2-mu/base-types.c
- src/tss2-mu/tpml-types.c
- src/tss2-mu/tpms-types.c
Fixes #847 
Fixes some new bug in base-type marshaling as well.
> Some reworks about libtss2-mu

- .travis.yml
- Makefile-test.am
> Tpm transientempty no tests

- Makefile-test.am
- src/tss2-esys/esys_iutil.c
- src/tss2-esys/esys_iutil.h
- src/tss2-esys/esys_mu.c
- src/tss2-esys/esys_tr.c
- remove dead code
- make all unmarshaling initialize dst to zero
- fix unused return code
- add test to makefile
> Some minor ESAPI fixes

- .gitignore
- Doxyfile.in
- configure.ac
- doc/doxygen.dox
Update Doxygen files wrt to the new directory structure.
Now generating documentation for those parts that are documented.
Fixes #912
> Doc: Fix doxygen

- INSTALL.md
Document how to build with Doxygen to generate documentation from function
headers and other information in INSTALL.md.
Fixes #959.
> INSTALL.md: Document Doxygen Builds

- MAINTAINERS
> MAINTAINERS: Add Andreas.

- .travis.yml
This PR resolves two issues: #816 and #999
> Travis intel mirror & fix hash check

- .travis.yml
- test/integration/sapi-session-util.c
> Travis: Add scan-build Static Code Analysis

- Makefile.am
- configure.ac
> Build: Make TCTIs optional

- Makefile-test.am
- src/tss2-esys/api/Esys_ContextLoad.c
- src/tss2-esys/api/Esys_ContextSave.c
- src/tss2-esys/api/Esys_NV_UndefineSpaceSpecial.c
- src/tss2-esys/esys_context.c
- src/tss2-esys/esys_int.h
- src/tss2-esys/esys_iutil.c
- src/tss2-esys/esys_iutil.h
- src/tss2-esys/esys_mu.c
- src/tss2-esys/esys_mu.h
- src/tss2-esys/esys_tr.c
- src/tss2-esys/esys_types.h
- test/integration/esys-create-session-auth.int.c
- test/unit/esys-nulltcti.c
Mostly very small commits.
Some error fixing in session handling and esys context.
> Some ESAPI Updates

- README.md
> README.md: Note deviation from current draft spec in TPM2_NUM_PCR_BANKS.

- Dockerfile
Use latest TPM simulator (ibmtpm1119.tar.gz)
Install OpenSSL 1.1 (required by simulator)
> Update Dockerfile to latest simulator

- src/tss2-esys/esys_iutil.c
- src/tss2-sys/api/Tss2_Sys_LoadExternal.c
- src/tss2-sys/api/Tss2_Sys_ObjectChangeAuth.c
- src/tss2-sys/sysapi_util.c
- test/integration/esys-create-password-auth.int.c
- test/integration/esys-create-session-auth.int.c
- test/integration/esys-createloaded.int.c
- test/integration/esys-encrypt-decrypt.int.c
- test/integration/esys-firmware-read.int.c
- test/integration/esys-get-time.int.c
- test/integration/esys-nv-certify.int.c
- test/integration/esys-nv-ram-extend-index.int.c
- test/integration/esys-nv-ram-ordinary-index.int.c
- test/integration/esys-object-changeauth.int.c
- test/integration/esys-save-and-load-context.int.c
- test/integration/esys-tpm-tests.int.c
- test/integration/sapi-hierarchy-change-auth.int.c
- test/integration/sapi-session-util.c
- test/integration/test-esapi.h
- test/tpmclient/tpmclient.int.c
According to the [coding standard](https://github.com/tpm2-software/tpm2-tss/blob/master/doc/coding_standard_c.md#whitespace), all indentation must be multiples of 4 spaces (and not tabs). Fixes #1053
> Fix indentation problems

- src/tss2-tcti/tcti-mssim.c
Patches to address issue:
https://github.com/tpm2-software/tpm2-tss/issues/1064
> Including header 'string.h' explicitly.

- INSTALL.md
Adds explanation of how to mount local tpm2-tss directory as a volume
for building  in a container.
> INSTALL.md: Rebuild with local changes in docker

- test/integration/esys-policy-regression.int.c
Addressing #1030.
This is another occasion where defined NV space is not undefined.
Furthermore, this tests contains a number of possibly unsupported commands. Some of them are checked for, others are not (e.g. PolicyPhysicalPresence is optional in the PC Client Spec, however its RC is not checked for TPM_RC_COMMAND)
This can be seen as a proposal of how the tests in general could behave:
* Have a cleanup label to remove/revert anything that would have lasting impact on the TPM
* Before returning an error, always check for TPM_RC_COMMAND and skip if necessary
Since this would have an impact on a number of tests at least, any suggestions on how to improve this are welcome. I could imagine that the code under the exit label would make sense to be in a macro, for example.
> test: Undefine NV space and make sure the cleanup is called in any case

- src/tss2-sys/api/Tss2_Sys_SetDecryptParam.c
Pull same code duplicated in if else blocks into a common block
to avoid duplication. Change some of the local variables to
comply with the coding standards.
I had this on a branch sitting and waiting for after 2.0.
> sapi: refactor SetDecryptParam

- test/integration/esys-policy-regression.int.c
- test/integration/sapi-command-cancel.int.c
- test/integration/sapi-encrypt-decrypt-2.int.c
- test/integration/sapi-encrypt-decrypt.int.c
Use defined value for skipped tests.
> test: use defined return value for skipped tests

- .travis.yml
- README.md
This reverts commit 847234899fa6522bd96376f0e2e7ad906b283ef1.
> Revert "build: Remove use of coveralls"

- test/integration/esys-policy-regression.int.c
* If the digest comparison fails the test did return 0 because only
the return code of the last ESAPI call was checked to determine
the result.
* The test was also adapted to the cleanup scheme of the other esys
tests.
> TEST ESYS: Fix digest comparison in policy regression test.

- configure.ac
> configure.ac: clean old simulatorbin

- Makefile.am
- configure.ac
- src/tss2-esys/esys_tcti_default.c
> tcti: fix compilation with --disable-tcti-mssim

- src/util/io.c
> util: io: error in parsing socket address

- src/tss2-esys/esys_tr.c
* The macro goto_if_error, not needed in this case, was replaced with goto error.
* Also some minor formatting issues were fixed.
> ESYS: Fix deadcode defect detected by coverity.

- Makefile-test.am
- configure.ac
- src/tss2-tcti/tcti-device.c
- test/unit/tcti-device.c
Change device tcti to nonblocking mode of operation.
> tcti-device: change device tcti to nonblocking mode

- MAINTAINERS
> MAINTAINERS: Remove Philip Tricca.

- src/util/log.c
tpm2-tss is supposed to be ISO-C99 compatible. So far, util/log.c
used the function `strncasecmp`, which is part of the POSIX- and
BSD-standard but not of the ISO-C99-standard.
Therefore, a new function, `caseInsensitiveStrncmp` is introduced. It
creates lowercase-variants of the strings to compare and calls
the C99-compatible standard function `strncmp` on them. This
mimicks the behavior of `strncasecmp` but remains compatible with
C99.
* Introduced caseInsensitiveStrncmp
* Replaced all calls of strncasecompare with it
* Adjusted names and indentations
> util: C99 compatible logging

- src/util/log.c
Fix some format problems in log.c file.
> util: fix formatting in log.c

- include/tss2/tss2_esys.h
- lib/tss2-esys.def
- src/tss2-esys/esys_free.c
- test/unit/esys-crypto.c
Capitalize esys_free to Esys_Free.
> esys: Capitalize esys_free to Esys_Free

- src/tss2-mu/tpm2b-types.c
Fixes an issue found during fuzzing
> Fix for Tpm2b marshaling code

- Dockerfile
This 4 commits change the Dockerfile to keep it more in-line with the [best practices for Dockerfiles](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/). They should not introduce any functional change.
> Dockerfile: Apply best practices

- README.md
So people have a link to click - needed for cii badge.
> Link Contribution.md in README.md

- README.md
Signed-off-by: Joshua Lock <joshua.g.lock@intel.com>
> README.md: Fix link to CONTRIBUTING.md

- Dockerfile
Added the missing wget command in line 15
> Dockerfile: Fixed missing wget

- .travis.yml
- configure.ac
> configure: add check for doxygen

- .travis.yml
- configure.ac
- src/tss2-sys/api/Tss2_Sys_Execute.c
- src/tss2-tcti/tcti-common.h
- src/tss2-tcti/tcti-device.c
- test/integration/main-esapi.c
- test/unit/io.c
This adds partial reads support for TCTI-device
> Partial reads

- test/integration/esys-evict-control-serialization.int.c
- test/integration/esys-policy-ticket.int.c
Fix two leaks found by coverity
> test: esys: fix leaks found by coverity scan

- src/tss2-sys/api/Tss2_Sys_Initialize.c
> sys: fix SAPI version in error message

- .gitignore
- Makefile.am
- config.h
- configure.ac
- src/tss2-esys/esys_iutil.h
- src/tss2-mu/base-types.c
- src/tss2-mu/tpm2b-types.c
- src/tss2-mu/tpma-types.c
- src/tss2-mu/tpml-types.c
- src/tss2-mu/tpms-types.c
- src/tss2-mu/tpmt-types.c
- src/tss2-mu/tpmu-types.c
- src/tss2-sys/sysapi_util.h
- src/tss2-tcti/tcti-common.h
- src/util/log.h
> AC config header

- Makefile.am
- README.md
- doc/archandlayout.md
Removed unneeded doc/archandlayout.md file, add missing doc files to EXTRA_DIST, and add a reference to logging.md to README.md.
> Doc updates

- src/tss2-esys/esys_crypto_ossl.c
in OSSL versions less than 1.1.0, rsa is non-opaque and
the code assigning to rsa->n assumed n was not initialized
and thus orphaned the pointer. Rather than duplicate memory,
just use the BN *ret argument to BN_bin2bn() to specify
setting that value.
> esys: dont orphan rsa->n in iesys_cryptossl_pk_encrypt

- lib/tss2-sys.def
- src/tss2-esys/esys_iutil.c
- src/tss2-esys/esys_types.h
- src/tss2-sys/api/Tss2_Sys_GetEncryptParam.c
- src/tss2-sys/tss2-sys.vcxproj
- test/tpmclient/tpmclient.int.c
Update session enc/dec flags depending on what is supported by the command.
> Update session flags

- Makefile-test.am
- src/tss2-esys/esys_crypto.c
- src/tss2-esys/esys_crypto_gcrypt.c
- src/tss2-esys/esys_crypto_ossl.c
- src/tss2-esys/esys_int.h
- src/tss2-esys/esys_iutil.c
- test/integration/esys-auto-session-flags.int.c
* Updated logic on the session restore flags.
* Added a new integration test to verify the auto adjusting of session flags
> Session flags

- src/tss2-esys/api/Esys_EvictControl.c
* A resource object for the key was created twice.
* The first object created was not used and deleted by Esys_Finalize.
* The code for creating this unused object was removed.
> ESYS: Remove unnecessary code from Esys_EvictControl.

- src/tss2-esys/esys_iutil.c
- test/integration/esys-session-attributes.int.c
Add fix and testcase.
Fixes: #1332
> ESYS: Fix session attribute automation problems

- src/tss2-esys/esys_crypto_ossl.c
1. bignum contexts are optional, OSSL can handle it for you.
2. bignum context wasn't always used. In one instance, bctx was NULL
indicating to let OSSL handle the context, then initialized later.
3. bctx initialization wasn't always checked for error.
Just remove it since OSSL can handle it for you.
> esys: openssl stop using bignum context

- .codecov.yml
This is a testing-PR mostly for checking the settings of the codecov config file.
Fixes: #1377
> CI: configure codecov

- Makefile.am
This is another bit of work related to #1348.
> build: Include MAINTAINERS file in dist tarballs.

- .travis.yml
If this works fine, next step is to extend this to the other projects.
More information about ccache and other cachings in travis:
[https://docs.travis-ci.com/user/caching/](https://docs.travis-ci.com/user/caching/)
> Add ccache to speed up travis.

- src/tss2-esys/tss2-esys.vcxproj
- src/tss2-mu/tss2-mu.vcxproj
- src/tss2-sys/tss2-sys.vcxproj
- src/tss2-tcti/tss2-tcti-mssim.vcxproj
- src/tss2-tcti/tss2-tcti-tbs.vcxproj
After AppVeyor latest changes this needs to be updated also
> appveyor: update to later version of tools

- CHANGELOG.md
- configure.ac
- src/tss2-esys/esys_iutil.c
- test/integration/esys-policy-password.int.c
- Fixed PolicyPassword handling of session Attributes
> Release 2.1.4 rc2

- CHANGELOG.md
- configure.ac
- src/tss2-esys/esys_iutil.c
- test/integration/esys-policy-password.int.c
- Fixed PolicyPassword handling of session Attributes
> Release 2.2.3 rc2

- .travis.yml
- Dockerfile
- Doxyfile.in
- README.md
- doc/coding_standard_c.md
- doc/doxygen.dox
- doc/logging.md
- src/tss2-esys/api/Esys_StartAuthSession.c
- src/util/log.c
- test/integration/esys-change-eps.int.c
- test/integration/esys-clear.int.c
- test/integration/esys-clockset.int.c
- test/integration/esys-ecc-parameters.int.c
- test/integration/esys-field-upgrade.int.c
- test/integration/esys-firmware-read.int.c
- test/integration/esys-get-random.int.c
- test/integration/esys-lock.int.c
- test/integration/esys-set-algorithm-set.int.c
- test/integration/esys-stir-random.int.c
- test/integration/esys-testparms.int.c
- test/integration/esys-tpm-tests.int.c
- test/integration/main-esapi.c
- test/integration/sapi-asymmetric-encrypt-decrypt.int.c
- test/integration/sapi-pcr-extension.int.c
- test/integration/sapi-self-test.int.c
- test/unit/UINT8-marshal.c
- test/unit/esys-crypto.c
- test/unit/esys-sequence-finish.c
- test/unit/log.c
Inspired by @diabonas https://github.com/tpm2-software/tpm2-tools/pull/1502
> Remove trailing whitespaces and empty lines and add to CI

- RELEASE.md
This is an RFC for a policy to be implemented.
It's stay open for a week or two so people have time to give feedback.
All feedback welcome.
> RFC: Add release maintainance and schedule info

- MAINTAINERS
This should be limited to ~3-4 weeks.
> MAINTAINERS: Add myself as coverage for Tadeusz while he is out.

- .lgtm.yml
- README.md
- src/tss2-esys/esys_crypto_ossl.h
- src/util/key-value-parse.h
As discussed in #1475, add a [LGTM](https://lgtm.com/) configuration and badge to the project. Also fix the two minor problems regarding header guards it reported.
> ci: add LGTM

- Makefile.am
> Install hook

- test/integration/esys-commit.int.c
Signed-off-by: Alexander Steffen <Alexander.Steffen@infineon.com>
> test: Skip esys-commit if ECDAA scheme is not supported

- test/integration/sapi-policy-authorizeNV.int.c
Signed-off-by: Alexander Steffen <Alexander.Steffen@infineon.com>
> test: Skip sapi-policy-authorizeNV if Encrypt/Decrypt command is missing

- README.md
> README: add readthedocs.org badge

- src/tss2-tcti/tcti-device.c
Signed-off-by: Jeffrey Ferreira <jeffpferreira@gmail.com>
> tcti-device: getPollHandles should allow num_handles query

- src/tss2-esys/api/Esys_CreateLoaded.c
- test/integration/esys-createloaded.int.c
The name calculated and cached for the ESYS_TR resource object was based
on the user supplied TPMT_PUBLIC. However, this template is often
missing data that the TPM fills in and returns in the TPM2B_PUBLIC
structure. Because of this, the cached name returned from
Esys_TR_GetName() and the name read from Esys_ReadPublic() would differ.
Add a test to detect this condition and correct it by copying the
returned TPM2B_PUBLIC to the ESYS_TR resource nodes TPM2B_PUBLIC cache
and calculate the name off of that.
Fixes: #1516
> Esys_CreateLoaded: fix resource name calculation

- README.md
Our mailman instance got an upgrade and someone decided to change the
URL too.
> docs: Update URL for mailing list in README.md

- MAINTAINERS
> MAINTAINERS: add Bill

- lib/tss2-mu.def
- lib/tss2-mu.map
fixes https://github.com/tpm2-software/tpm2-tss/issues/1565
> build: update exported symbols map for libtss2-mu

- src/tss2-tcti/tctildr.c
- test/unit/tctildr.c
> Return proper error code on memory allocation failure

- src/tss2-tcti/tcti-mssim.c
> tcti-mssim: Fix potential buffer overflow in tcti_mssim_receive

- configure.ac
> configure: Only use CXX when fuzzing

- configure.ac
Reverts tpm2-software/tpm2-tss#1579
> Revert "configure: Only use CXX when fuzzing"

- src/tss2-tcti/tctildr-dl.c
Closes https://github.com/tpm2-software/tpm2-tss/issues/1553
> tcti: fix tctildr-dl description typos

- test/unit/TPM2B-marshal.c
> test: remove upcasting from tpm2b marshal unit test

- src/tss2-esys/esys_crypto_gcrypt.c
> esys: fix potential leak in iesys_cryptogcry_sym_aes_[en|de]crypt

- src/tss2-fapi/fapi_int.h
@tstruk We don't have any more functional changes Queued.
From my side, we can roll the final RC based on this release.
> FAPI: Remove unused declarations.

- src/tss2-fapi/ifapi_get_intl_cert.c
- src/tss2-fapi/ifapi_helpers.c
Add more info on what happens in curl get cert in
we are in the trace loglevel.
> FAPI: add more log info in the trace loglevel

- configure.ac
- src/tss2-tcti/tctildr.c
> tctildr: remove the private implementation of strndup

- src/tss2-fapi/ifapi_get_intl_cert.c
Intel PTT EK certs on the host website are json encoded
where the cert data in "certificate:" tags. To get the cert
it needs to be parsed out of the json format before converting
to a binary PEM cert. An example can be seen here:
https://ekop.intel.com/ekcertservice/WVEG2rRwkQ7m3RpXlUphgo6Y2HLxl18h6ZZkkOAdnBE%3D
> FAPI: Parse certificate data out of encoded format

- src/util/log.c
For big blobs don't allocate the whole buffer on the stack
at once, but process one line at a time, with a fixed length
buffer. Make the output more hexdump like, with indexes and ascii
output, which is quite helpful when debugging data containing
strings, like PEM certs, etc.
> log: improve blob printout format

- INSTALL.md
> doc: update windows dependecies

- git.mk
Add few more files to the auto-generated .gitignore file.
> build: update git.mk

- .cirrus.yml
- Makefile.am
* build: make 'make_man' more portable 
* ci: change cirrus.yml to run 'make distcheck'
> Update FreeBSD CI

- man/Tss2_Tcti_Device_Init.3.in
- man/Tss2_Tcti_Mssim_Init.3.in
- man/man-postlude.troff
- man/tss2-tcti-device.7.in
- man/tss2-tcti-mssim.7.in
> man: update tss2-tcti-device and tss2-tcti-mssim

- .cirrus.yml
We use git to generate AUTHORS file.
> ci: cirrus.yml add git

- src/tss2-fapi/api/Fapi_Provision.c
- src/tss2-fapi/ifapi_config.c
- src/tss2-fapi/ifapi_helpers.c
- src/tss2-fapi/ifapi_keystore.c
- src/util/aux_util.h
- src/util/log.c
- src/util/tpm2b.h
- test/integration/sapi-session-util.c
- Use modern flex-array style
- make getenv() returns const
- Remove unused macro
- Use strtok_r instead of strtok
> Some minor things regarding good style

- src/tss2-fapi/ifapi_policy_json_deserialize.c
- src/tss2-fapi/ifapi_policy_json_serialize.c
- src/tss2-fapi/tpm_json_deserialize.c
- src/tss2-fapi/tpm_json_deserialize.h
- src/tss2-fapi/tpm_json_serialize.c
- src/tss2-fapi/tpm_json_serialize.h
- test/unit/fapi-json.c
* Several unit tests were added to check error cases and different algorithms.
* Some unused functions were removed.
> FAPI Improve test coverage

- CHANGELOG.md
> CHANGELOG: update for Esys_TestParams

- Makefile-test.am
- doc/doxygen.dox
- include/tss2/tss2_fapi.h
- lib/tss2-fapi.def
- lib/tss2-fapi.map
- src/tss2-fapi/api/Fapi_GetEsysBlob.c
- src/tss2-fapi/fapi_int.h
- test/integration/fapi-get-esys-blobs.int.c
* The function gets blobs from FAPI objects which can be used to create ESAPI objects. 
* Also an integration test was added.
> FAPI: Add new function Fapi_GetEsysBlob

- .travis.yml
> travis: add ubuntu-20.04 build

- Makefile.am
- configure.ac
This is done automagically by pkg
> build: no need to add user or change perms on FreeBSD

- src/tss2-esys/esys_tr.c
> BugFix: Shared secret calculation is not spec compliant.

- src/tss2-fapi/api/Fapi_GetCertificate.c
- src/tss2-fapi/api/Fapi_NvRead.c
- src/tss2-fapi/api/Fapi_PcrRead.c
- src/tss2-fapi/api/Fapi_Provision.c
- src/tss2-fapi/api/Fapi_Sign.c
- src/tss2-fapi/fapi_int.h
- src/tss2-fapi/fapi_util.c
- src/tss2-fapi/fapi_util.h
- src/tss2-fapi/ifapi_helpers.c
* The hierarchy usage in Fapi_Provision was fixed.
* A segfault Fapi_GetCertificate for objects which are not of type key was fixed.
* Some segfault and leak problems were fixed.
> 2.4.x fixes

- src/tss2-rc/tss2_rc.c
The description for this new RC was added.
> TSS2_RC: Add new return code TSS2_BASE_RC_NOT_PROVISIONED.

- include/tss2/tss2_common.h
- src/tss2-fapi/api/Fapi_Delete.c
- src/tss2-fapi/api/Fapi_Encrypt.c
- src/tss2-fapi/api/Fapi_Provision.c
- src/tss2-fapi/api/Fapi_Quote.c
- src/tss2-fapi/ifapi_helpers.c
- src/tss2-rc/tss2_rc.c
- test/integration/fapi-nv-set-bits.int.c
- Add FAPI_RC_ALREADY_PROVISIONED for Fapi_Provision
- Add some hints in logging for certain common errors
> Better logs in FAPI

- src/tss2-fapi/api/Fapi_AuthorizePolicy.c
- src/tss2-fapi/api/Fapi_Import.c
- src/tss2-fapi/api/Fapi_Quote.c
- src/tss2-fapi/api/Fapi_VerifyQuote.c
- src/tss2-fapi/ifapi_json_serialize.c
Backport of https://github.com/tpm2-software/tpm2-tss/pull/1801
> FAPI: Fix memory leaks on error paths (backported)

- src/tss2-tcti/tcti-device.c
- test/unit/tcti-device.c
> Fix timing issue in partial read probe

- src/tss2-fapi/api/Fapi_ChangeAuth.c
- src/tss2-fapi/api/Fapi_Encrypt.c
- src/tss2-fapi/api/Fapi_Provision.c
- src/tss2-fapi/fapi_util.c
- src/tss2-fapi/ifapi_keystore.c
- src/tss2-fapi/ifapi_keystore.h
- src/tss2-fapi/ifapi_policy_execute.c
- src/tss2-fapi/ifapi_policy_instantiate.c
- src/tss2-fapi/ifapi_policy_store.c
- src/tss2-fapi/ifapi_policyutil_execute.c
- src/tss2-sys/api/Tss2_Sys_Execute.c
- src/tss2-tcti/tcti-cmd.c
- src/tss2-tcti/tcti-mssim.c
* Policy execution was fixed.
* Pathname check was added for policy files.
* New provisioning after deleting /HS was enabled.
* A missing return code check for ChangeAuth was added.
* Logs were added to sys and tcti to check cirrus ci error.
> Fapi several fixes2

- src/tss2-fapi/api/Fapi_CreateNv.c
An NV index defined by the user in the type parameter of Fapi_NvCreate was ignored.
The user defined index now will be used if the index is in valid range.
> FAPI: Fix usage of user defined NV index (Fixes #1847).

- CHANGELOG.md
- src/tss2-fapi/ifapi_policy_callbacks.c
- test/integration/fapi-key-create-policy-pcr-sign.int.c
> FAPI: Fix policyPCR calculation

- CHANGELOG.md
- configure.ac
- src/tss2-fapi/ifapi_policy_callbacks.c
> Fix PolicyPCR calculation on 3.0.x

- CHANGELOG.md
- configure.ac
- src/tss2-fapi/ifapi_policy_callbacks.c
> Fix PolicyPcr calculation on 2.4.x

- lib/tss2-esys.pc.in
- lib/tss2-fapi.pc.in
- lib/tss2-mu.pc.in
- lib/tss2-rc.pc.in
- lib/tss2-sys.pc.in
- lib/tss2-tcti-cmd.pc.in
- lib/tss2-tcti-device.pc.in
- lib/tss2-tcti-mssim.pc.in
- lib/tss2-tcti-swtpm.pc.in
- lib/tss2-tctildr.pc.in
Replace false $includedir/tss with $includedir/tss2.
Fixes: #1876
> PKG-CONFIG: Fix include-dir

- src/tss2-fapi/api/Fapi_Import.c
- src/tss2-fapi/fapi_util.c
- src/tss2-fapi/ifapi_policy_instantiate.c
Fix a memory leak if FAPI caused by free after sync return.
> Fapi: Fix coverity bugs

- CHANGELOG.md
- configure.ac
> Release Candidate 2.4.4-rc0

- CHANGELOG.md
- configure.ac
> Release Candidate 3.0.2-rc0

- CHANGELOG.md
- configure.ac
> Release Candidate 3.0.3-rc0

- CHANGELOG.md
- configure.ac
> Release Candidate 2.4.5-rc0

- Makefile-test.am
- src/tss2-fapi/fapi_util.c
- src/tss2-fapi/ifapi_helpers.c
- src/tss2-fapi/ifapi_policy_callbacks.c
- src/tss2-fapi/ifapi_policy_types.h
- src/tss2-fapi/ifapi_policyutil_execute.c
- test/integration/fapi-key-create2-sign.int.c
* Remove unused functions and fields.
* Fix error cleanup for key loading and policy execution.
* Test cleanup for key loading with policy usage.
> FAPI: Fix cleanup for key loading with policy usage.

- src/tss2-esys/api/Esys_StartAuthSession.c
If ESYS_TR_RH_NULL was used as bind parameter for Esys_StartAuthSession the wrong HMAC
was computed, because the session was not treated as unbound session.
It will be checked whether no tpm key is passed and ESYS_TR_RH_NULL is used as bind
parameter to skip KDF computation of the session key.
> ESYS: Fix binding of ESYS_TR_RH_NULL 3.0.x (Fixes #1993)

- src/tss2-esys/api/Esys_StartAuthSession.c
If ESYS_TR_RH_NULL was used as bind parameter for Esys_StartAuthSession the wrong HMAC
was computed, because the session was not treated as unbound session.
It will be checked whether no tpm key is passed and ESYS_TR_RH_NULL is used as bind
parameter to skip KDF computation of the session key.
Fixes #1993.
> ESYS: Fix binding of ESYS_TR_RH_NULL 2.4.x

- src/tss2-fapi/ifapi_config.c
- src/tss2-fapi/ifapi_keystore.c
- test/unit/fapi-config.c
* $HOME and ~ in files defined in the FAPI config file will be interpreted
as home directory.
Fixes #1980
* The unit test fapi-config was adapted to check this expansion.
* The unnecessary expansion in ifapi_keystore_initialize was removed.
> FAPI: Support ~ in paths.

- configure.ac
- script/int-log-compiler.sh
Use shasum -a256 instead of sha256sum for compatibility
> test: use shasum -a256 instead of sha256sum

- Makefile.am
Add JSONC and CURL specific CFLAGS to fapi CFLAGS.
> build: add json and curl cflags to fapi

- README.md
Hi @williamcroberts, @idesai,
Varun suggested adding our weekly call to the readme.
Signed-off-by: Dimitar Tomov <dimi@tpm.dev>
> Add TPM developer community call information to README.md

- src/tss2-tcti/tctildr.c
> tcti: quiet tcti ldr noise

- src/tss2-fapi/ifapi_io.c
Reverts tpm2-software/tpm2-tss#2074
> Revert "fix for possible dual freeing."

- src/tss2-fapi/fapi_crypto.c
* If the downloaded intermediate certificate can't be converted do X509 format
an error message with the blob of the downloaded certificate will be displayed.
* If display of debugging information is activated the EK certificate and the corresponding
intermediate certificate will be displayed.
> FAPI: Add logging for certificate verification.

- test/integration/fapi-ext-public-key.int.c
This PR should work with OpenSSL 1.0.0 through 3.0.0.
The EVP_PKEY_sign functions are available since OpenSSL 1.0.0.
The RSA_sign function is deprecated in OpenSSL 3.0.0.
Note also that OpenSSL's `xxx_free` functions check for NULL, so there is no need to have the check here.
> FAPI Test: Change RSA_sign to EVP_PKEY_sign

- src/tss2-fapi/tpm_json_deserialize.c
This fixes the issue in tpm2-tools test:
- https://github.com/tpm2-software/tpm2-tools/issues/2808
It also checks for a potential NPD issue and removes a level of indentation.
> Fix fapi json

- MAINTAINERS
Add Juergen to maintainer file.
> MAINTAINERS: Add Juergen

- src/tss2-esys/esys_crypto_ossl.c
- src/tss2-fapi/fapi_crypto.c
The TPM2 provider may be loaded in the global library context. As we don't want the TPM to be called for some operations, we have to initialize own library context with the default provider. This is similar to the RAND_set_rand_method dance with older OpenSSL.
Also, I suggest to remove the second `struct` from the context union as the second is exactly the same as the first. I see no point in having the same struct twice.
Fixes: #2150
> Use default OpenSSL context for internal crypto operations

- src/tss2-fapi/ifapi_get_intl_cert.c
> license: fix bsd3 to 2

- test/integration/test-fapi.h
> test: Fix the double free problem in CHECK_JSON_LIST(3.0.x)

- test/integration/test-fapi.h
> test: Fix the double free problem in CHECK_JSON_LIST(3.1.x)

- CHANGELOG.md
- src/tss2-fapi/api/Fapi_Quote.c
- src/tss2-fapi/ifapi_io.c
* CHANGELOG: Update fixes.
* FAPI: Fix leak in Fapi_Quote.
* FAPI: Fix file locking in ifapi io.
> Update backports 3.0.x

- CHANGELOG.md
- src/tss2-fapi/api/Fapi_Quote.c
* CHANGELOG: Update fixes.
* FAPI: Fix leak in Fapi_Quote.
> Update backports 3.1.x

- CHANGELOG.md
I forgot to add those earlier. It's quite important to mention them.
Plus one minor typo of the first Added line.
> CHANGELOG: Add OpenSSL 3 related entries

- src/tss2-fapi/tpm_json_deserialize.c
- src/tss2-fapi/tpm_json_serialize.c
> fapi:Support Camellia Algorithm

- CODE_OF_CONDUCT.md
> CODE_OF_CONDUCT: initial commit

- include/tss2/tss2_tpm2_types.h
- src/tss2-esys/esys_iutil.c
- test/helper/tpm_getek.c
- test/helper/tpm_getek_ecc.c
- test/helper/tpm_writeekcert.c
- test/integration/sys-asymmetric-encrypt-decrypt.int.c
- test/integration/sys-create-keyedhash-sha1-hmac.int.c
- test/integration/sys-create-loaded.int.c
- test/integration/sys-evict-ctrl.int.c
- test/integration/sys-hierarchy-change-auth.int.c
- test/integration/sys-hmac-auth.int.c
- test/integration/sys-nv-policy-locality.int.c
- test/integration/sys-nv-readwrite.int.c
- test/integration/sys-param-encrypt-decrypt.int.c
- test/integration/sys-pcr-extension.int.c
- test/integration/sys-policy-authorizeNV.int.c
- test/integration/sys-policy-template.int.c
- test/integration/sys-util.c
- test/tpmclient/tpmclient.int.c
- test/unit/TPMU-marshal.c
> Fix RS_PW to RH_PW

- src/tss2-esys/esys_tr.c
> ESYS: Fixed annotation error of Esys_TR_Deserialize

- src/tss2-fapi/api/Fapi_Delete.c
- src/tss2-fapi/api/Fapi_GetEsysBlob.c
> Clean up the allocated variables when Fapi_GetEsysBlob_Async and Fapi_Delete_Async failed

- src/tss2-fapi/api/Fapi_VerifyQuote.c
It was not checked whether the qualifying data is equal to the extraData
field in the quoteInfo.
> FAPI: Fix check of qualifying data in Fapi_VerifyQuote 3.0.x

- src/tss2-fapi/api/Fapi_VerifyQuote.c
It was not checked whether the qualifying data is equal to the extraData
field in the quoteInfo.
> FAPI: Fix check of qualifying data in Fapi_VerifyQuote 3.1.x

- CHANGELOG.md
> Update Changelog for 3.0.5-rc0

- CHANGELOG.md
> Update Changelog for 3.1.1-rc0

- CHANGELOG.md
> Update Changelog for 3.2.0-rc0

- src/tss2-mu/tpm2b-types.c
> MU: Fix buffer upcast leading to misalignment

- CHANGELOG.md
> Update Changelog for 3.0.5-rc1

- CHANGELOG.md
> Update Changelog for 3.2.0-rc1

- src/tss2-fapi/ifapi_helpers.c
Errors did occur for urls which where not escaped since curl version 7.80. Now the escaping
is executed before executing the download.
> FAPI: Fix usage of curl url.

- src/tss2-tcti/tctildr-dl.c
Signed-off-by: JerryDevis <89641128+JerryDevis@users.noreply.github.com>
> tcti: Use heap instead of stack when tcti initialize

- .github/workflows/main.yml
> ci: add ubuntu-22.04

- src/tss2-tcti/tctildr.c
> tcti: Fix stack usage is too large when tcti initialize

- src/tss2-esys/esys_crypto_mbed.c
Updated to mbedTLS 3.0 with backwards compatibility to older versions
Note: MBEDTLS_PRIVATE is used quite a lot. It's not recommended but currently there is no other way. There are open issues at mbedTLS which will add accessor functions.
Fixes #2266 
Signed-off-by: Benjamin Bigler <benjamin.bigler@securiton.ch>
> ESYS: Updated to mbedTLS 3.0

- test/integration/esys-field-upgrade.int.c
- test/integration/esys-firmware-read.int.c
Update some log messages in case of command not supported
Signed-off-by: LCH35 <55393831+LCH35@users.noreply.github.com>
> Update some integration tests log messages

- CONTRIBUTING.md
- SECURITY.md
> SECURITY: initial commit

- include/tss2/tss2_common.h
- include/tss2/tss2_policy.h
- src/tss2-fapi/ifapi_policy_execute.c
- src/tss2-fapi/ifapi_policy_instantiate.c
- src/tss2-policy/tss2_policy.c
> policy: add null checks on exec callbacks

- src/tss2-esys/esys_tr.c
Signed-off-by: Imran Desai <imran.desai@intel.com>
> Resource leaks breaks tpm2-tools CI

- src/tss2-esys/esys_tr.c
Signed-off-by: Imran Desai <imran.desai@intel.com>
> tss2-esys/esys_tr.c: fix resource leaks

- include/tss2/tss2_rc.h
- lib/tss2-rc.def
- lib/tss2-rc.map
- src/tss2-rc/tss2_rc.c
- test/unit/test_tss2_rc.c
This should enable developers to extract response code information and provide better logging/error messages based on application specific context
> rc: add function to decode the bitfields in TSS2_RC

- test/integration/policy-execute.int.c
When running the testcase against a real device, PCR 8 might have been extended (typically by GRUB) causing the test to fail due to unexpected preconditions. Skip the policy check in this case.
Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>
> fapi: Skip policy check if PCR value is not expected

- src/tss2-esys/esys_tr.c
> ESAPI: fix spelling in esys_tr.c

- src/tss2-fapi/api/Fapi_ExportKey.c
All other appearances are fine.
Signed-off-by: Xavier Yin <bug313@gmail.com>
> Fix typo checking ifapi_session_init() return.

- Makefile-test.am
- src/tss2-esys/esys_iutil.c
- test/integration/esys-tr-getName.int.c
Signed-off-by: malikabhi05 <abhishek.malik@intel.com>
> esys_iutil.c: Adding range for ACs

- CHANGELOG.md
> CHANGELOG: update for 4.0.0-rc0

- src/tss2-fapi/ifapi_curl.c
- src/util/log.c
Fixes: #2523
Note we could even add an assert to doLogBuf so debug builds will abort.
> Fix curl uaf

- doc/fapi-profile.md
- man/fapi-profile.5.in
An example for usage of the PCR bank SHA1 was added.
> FAPI: Improve documentation fapi-profile.

- configure.ac
- include/tss2/tss2_esys.h
- src/tss2-esys/esys_crypto.c
- src/tss2-esys/esys_crypto.h
- src/tss2-esys/esys_crypto_mbed.h
- src/tss2-esys/esys_crypto_ossl.c
- src/tss2-esys/esys_crypto_ossl.h
- src/tss2-esys/esys_iutil.c
- test/integration/esys-crypto.int.c
- test/unit/esys-crypto.c
> esys: add SM4 algorithm support.

- INSTALL.md
Some missing steps for the Fedora installation were added. Fixes: #2589
> INSTALL.md Update Fedora installation.

- test/data/fapi/policy/pol_signed_keyedhash_sha384.json
- test/integration/fapi-key-create-policy-pcr-sign.int.c
- test/integration/fapi-key-create-policy-signed-keyedhash.int.c
Tested in a VM with a virtual TPM provided by swtpm.
> Test fixes when configured with --with-default-test-fapi-profile=P_ECC384

- src/tss2-fapi/ifapi_json_eventlog_serialize.c
you should close fp before return
Signed-off-by: xiongyi <xiongyi@uniontech.com>
> fix resource leak fp

- src/tss2-tcti/tcti-spi-lt2go.c
- test/unit/tcti-spi-lt2go.c
Change VID and PID to final values
Signed-off-by: Paul Kissinger <paul.kissinger@letstrust.de>
> TCTI-SPI-LT2GO: Change VID and PID to final values

- Makefile.am
Mssing UUID cand CRYPTO flags caused problems during cross compilation.
Fixes #2743
> Makefile.am add missing flags.

- src/tss2-rc/tss2_rc.c
The error messages for TPM2_RC_FW_LIMITED and TPM2_RC_SVN_LIMITED are added.
> rc: add new return codes.

- src/tss2-esys/api/Esys_NV_ChangeAuth.c
- src/tss2-esys/api/Esys_ObjectChangeAuth.c
- src/tss2-fapi/api/Fapi_List.c
- src/tss2-fapi/fapi_crypto.c
- src/tss2-fapi/fapi_util.c
- src/tss2-fapi/ifapi_eventlog_system.c
- src/tss2-fapi/ifapi_helpers.c
- src/tss2-fapi/ifapi_policy_calculate.c
- src/tss2-tcti/tcti-i2c-helper.c
- src/tss2-tcti/tcti-spi-ltt2go.c
Several problems detected in the coverity scan are fixed.
> Fix coverity scan errors

- test/integration/sys-pcr-extension.int.c
The test failed when a physical TPM was used and the TPM did not support a SHA1 bank.
The hash alg is changed to SHA256 and it's checked whether the TPM supports the selected bank.
> sys test: change hashalg from sha1 to sha256 for pcr extend test.

- src/tss2-esys/api/Esys_NV_ChangeAuth.c
- src/tss2-esys/api/Esys_ObjectChangeAuth.c
- src/tss2-esys/esys_crypto.c
- src/tss2-esys/esys_tr.c
- src/tss2-fapi/api/Fapi_Provision.c
- src/tss2-fapi/fapi_crypto.c
- src/tss2-fapi/fapi_util.c
- src/tss2-fapi/ifapi_ima_eventlog.c
- src/tss2-fapi/ifapi_json_deserialize.c
- src/tss2-fapi/ifapi_json_eventlog_serialize.c
- src/tss2-fapi/ifapi_policy_json_deserialize.c
- src/tss2-sys/api/Tss2_Sys_GetCapability.c
- src/tss2-tcti/tcti-spi-helper.c
- src/tss2-tcti/tcti-swtpm.c
Coverity errors are fixed for TCTI, SYS, ESYS, and FAPI.
> Fix coverity errors

- src/tss2-fapi/fapi_util.c
- src/tss2-fapi/ifapi_ima_eventlog.c
- src/tss2-tcti/tcti-device.c
> Coverity scan

- .cirrus.yml
- .github/workflows/main.yml
- src/tss2-esys/esys_tr.c
- src/tss2-fapi/api/Fapi_List.c
- src/tss2-fapi/fapi_util.c
- src/tss2-fapi/ifapi_policy_json_deserialize.c
- src/tss2-fapi/ifapi_policy_json_serialize.c
- src/tss2-fapi/tpm_json_deserialize.c
- src/tss2-tcti/tcti-device.c
- src/util/aux_util.h
- test/integration/esys-act-set-timeout.int.c
- test/integration/esys-certifyX509.int.c
- test/integration/esys-pcr-auth-value.int.c
- test/integration/fapi-key-create-policies-sign.int.c
- test/unit/tcti-libtpms.c
The missing bug fixes for 4.1.0 are cherry picked.
> 3.2.x update backportsThe bug fixes for 4.1.0 are cherry picked.

- script/int-log-compiler-common.sh
See https://lwn.net/Articles/874049/
> int-log-compiler-common.sh: Remove dependency on which

- .cirrus.yml
13.2 is apparently no longer available
> cirrus-ci update image-family to freebsd-14-0

- sphinx/sphinx-finished.sh
A script to fix index.html is added.
> readthedocs: add sphinx-finished.sh

- .github/workflows/codeql.yml
CodeQL action was outdated.
Fixes: #2954
> codeql: update v2 to v3
